'use strict';
const assert=require('node:assert/strict');
const {createCore,nacl}=require('./fixtures/core_vm.cjs');
global.nacl=nacl;
const discovery=require('../js/route_discovery_v4.js');
const profile=require('../js/account_handshake_v4.js'),Session=require('../js/account_session_v4.js');
const hex=profile.hex,recipient=require('../js/recipient_payload_v4.js');
let now=1800000000;
async function pair(){
 const [a,b]=await Promise.all([createCore({kyber:true}),createCore({kyber:true})]);
 for(const [local,peer] of [[a,b],[b,a]]){
  local.value=null;local.revision=0;local.current=true;local.failWrite=false;local.sent=[];
  local.codec=profile.createCodec({nacl,discovery,clock:()=>now});
  local.owner={context:()=>({local:local.core.keys.pub_hex,peer:peer.core.keys.pub_hex,bindingDigest:'11'.repeat(32),bindingGeneration:1,requiredSuite:profile.SUITE}),assertCurrent:()=>{if(!local.current)throw Error('STALE_OWNER');},signingKey:()=>local.core.keys.sign.secretKey};
  local.store={load:async()=>({revision:local.revision,value:structuredClone(local.value)}),commit:async(revision,value,guard)=>{guard();assert.equal(revision,local.revision);if(local.failWrite)throw Error('WRITE_FAILED');local.value=structuredClone(value);local.revision++;guard();}};
  local.restart=()=>local.session=new Session({codec:local.codec,profile,nacl,kem:local.ctx.DmashKyberWasm,store:local.store,owner:local.owner,clock:()=>now});local.restart();
 }
 return [a,b];
}
const intent=(a,kind)=>a.value.intents.find(i=>JSON.parse(i.raw).kind===kind)?.raw;
async function establish(a,b){await a.session.initiate();const init=intent(a,'INIT');await b.session.receive(init);const final=intent(b,'FINAL');await a.session.receive(final);assert.equal((await a.session.status()).phase,'INITIATOR_CONFIRM_PENDING');assert.equal(a.value.confirmed,null);const confirm=intent(a,'CONFIRM');await b.session.receive(confirm);const ack=intent(b,'CONFIRM_ACK');await a.session.receive(ack);assert.equal(a.value.confirmed.root,b.value.confirmed.root);assert.equal((await a.session.status()).phase,'ESTABLISHED');return {init,final,confirm,ack};}
(async()=>{
 const [a,b]=await pair();const exchange=await establish(a,b);const receiver=nacl.box.keyPair();for(const raw of Object.values(exchange)){const blob=recipient.sealPayload(receiver.publicKey,raw),bytes=Buffer.from(blob,'base64').length,wrapped=Buffer.byteLength(JSON.stringify({type:'RECIPIENT_PAYLOAD',version:2,packet_id:'00'.repeat(32),payload:raw}));assert.equal(bytes,wrapped+72,'recipient JSON escaping and72byte overhead');assert(bytes<=16384);assert.equal(recipient.openPayload([receiver.secretKey],blob).payload,raw);}
 await b.session.receive(exchange.confirm);assert.equal(intent(b,'CONFIRM_ACK'),exchange.ack,'exact ACK retry');await a.session.receive(exchange.ack);
 const root=b.value.confirmed.root,oldSid=b.value.ledger.session_id;
 // Narrow active session loss preserves independently durable authority ledger.
 a.value.confirmed=null;a.restart();await a.session.initiate({recover:true});const fresh=intent(a,'INIT'),request=intent(a,'RECOVERY_REQUEST');
 await b.session.receive(fresh);assert.equal(b.value.confirmed.root,root);assert.equal(b.value.pending,null);
 await b.session.receive(request);const challenge=intent(b,'RECOVERY_CHALLENGE');await b.session.receive(request);assert.equal(intent(b,'RECOVERY_CHALLENGE'),challenge);
 await a.session.receive(challenge);const proof=intent(a,'RECOVERY_PROOF');await b.session.receive(intent(a,'INIT'));await b.session.receive(proof);const final=intent(b,'FINAL');assert.equal(b.value.confirmed.root,root,'pending recovery never replaces established root');
 b.restart();await b.session.receive(proof);assert.equal(intent(b,'FINAL'),final,'consumed ticket exact retry after restart');await a.session.receive(final);const confirm=intent(a,'CONFIRM');await b.session.receive(confirm);const ack=intent(b,'CONFIRM_ACK');await a.session.receive(ack);assert.equal(a.value.confirmed.root,b.value.confirmed.root);assert.notEqual(b.value.confirmed.root,root);assert.equal(b.value.ledger.generation,2);assert(b.value.retired.includes(oldSid));
 await b.session.receive(confirm);assert.equal(intent(b,'CONFIRM_ACK'),ack);await assert.rejects(()=>b.session.receive(proof),/RECOVERY_CONTEXT/);await b.session.receive(exchange.init);assert.equal(b.value.confirmed.root,a.value.confirmed.root,'stale proposal cannot replace root');
 // Initial simultaneous proposals choose one durable deterministic transcript.
 const [c,d]=await pair();await Promise.all([c.session.initiate(),d.session.initiate()]);const ci=intent(c,'INIT'),di=intent(d,'INIT');await c.session.receive(di);await d.session.receive(ci);const responder=c.value.pending.role==='responder'?c:d,initiator=responder===c?d:c;await initiator.session.receive(intent(responder,'FINAL'));await responder.session.receive(intent(initiator,'CONFIRM'));await initiator.session.receive(intent(responder,'CONFIRM_ACK'));assert.equal(c.value.confirmed.root,d.value.confirmed.root);
 // Failed state publication leaks no outbound intent and leaves old data intact.
 const [e,f]=await pair();e.failWrite=true;await assert.rejects(()=>e.session.initiate(),/WRITE_FAILED/);assert.equal(e.value,null);assert.equal(e.sent.length,0);e.failWrite=false;await e.session.initiate();const eInit=intent(e,'INIT');await e.session.initiate();assert.equal(intent(e,'INIT'),eInit);
 f.failWrite=true;await assert.rejects(()=>f.session.receive(eInit),/WRITE_FAILED/);assert.equal(f.value,null);f.failWrite=false;await f.session.receive(eInit);const ff=intent(f,'FINAL');f.restart();await f.session.receive(eInit);assert.equal(intent(f,'FINAL'),ff,'exact FINAL retry');
 await f.session.flush({submitIntent:async ({frame})=>{f.sent.push(frame);return false;}});assert.equal(intent(f,'FINAL'),ff);assert.equal(f.sent.length,1);await f.session.flush({submitIntent:async()=>assert.fail('backoff')});now+=5;await f.session.flush({submitIntent:async({frame})=>f.sent.push(frame)});assert.equal(f.sent[0],f.sent[1]);
 e.current=false;await assert.rejects(()=>e.session.receive(ff),/STALE_OWNER/);e.current=true;
 const tampered=JSON.parse(ff);tampered.body.mac='00'.repeat(32);const forged=f.codec.sign(Object.fromEntries(Object.entries(tampered).filter(([k])=>k!=='signature')),f.core.keys.sign.secretKey);await assert.rejects(()=>e.session.receive(forged),/KEY_CONFIRMATION/);assert.equal(e.value.pending.phase,'INIT_PREPARED');
 // Pending initiator state loss: responder has no confirmed ledger yet.
 const [g,h]=await pair();await g.session.initiate();await h.session.receive(intent(g,'INIT'));const orphanFinal=intent(h,'FINAL');g.value.pending=null;g.value.intents=[];g.restart();await g.session.initiate({recover:true});await h.session.receive(intent(g,'INIT'));await h.session.receive(intent(g,'RECOVERY_REQUEST'));await g.session.receive(intent(h,'RECOVERY_CHALLENGE'));await h.session.receive(intent(g,'INIT'));await h.session.receive(intent(g,'RECOVERY_PROOF'));const recoveredFinal=intent(h,'FINAL');assert.notEqual(recoveredFinal,orphanFinal);await g.session.receive(recoveredFinal);await h.session.receive(intent(g,'CONFIRM'));await g.session.receive(intent(h,'CONFIRM_ACK'));assert.equal(g.value.confirmed.root,h.value.confirmed.root);
 // Both retained ledgers request recovery concurrently: same identity winner.
 const [j,k]=await pair();await establish(j,k);j.value.confirmed=null;k.value.confirmed=null;await j.session.initiate({recover:true});await k.session.initiate({recover:true});const ji=intent(j,'INIT'),ki=intent(k,'INIT'),jr=intent(j,'RECOVERY_REQUEST'),kr=intent(k,'RECOVERY_REQUEST');await j.session.receive(ki);await k.session.receive(ji);await j.session.receive(kr);await k.session.receive(jr);const challenger=j.value.recovery.role==='authority'?j:k,requester=challenger===j?k:j;await requester.session.receive(intent(challenger,'RECOVERY_CHALLENGE'));await challenger.session.receive(intent(requester,'INIT'));await challenger.session.receive(intent(requester,'RECOVERY_PROOF'));await requester.session.receive(intent(challenger,'FINAL'));await challenger.session.receive(intent(requester,'CONFIRM'));await requester.session.receive(intent(challenger,'CONFIRM_ACK'));assert.equal(j.value.confirmed.root,k.value.confirmed.root);
 // Stale retained ledger learns a newer predecessor only through fresh challenge.
 const staleLedger={session_id:oldSid,generation:1};a.value.ledger=staleLedger;a.value.confirmed=null;a.value.pending=null;a.value.recovery=null;a.value.intents=[];a.restart();await a.session.initiate({recover:true});const proposal=intent(a,'INIT');await b.session.receive(proposal);await b.session.receive(intent(a,'RECOVERY_REQUEST'));await a.session.receive(intent(b,'RECOVERY_CHALLENGE'));const authorized=intent(a,'INIT');assert.notEqual(proposal,authorized);assert.equal(JSON.parse(authorized).session_generation,3);assert.equal(JSON.parse(authorized).body.ephemeral,JSON.parse(proposal).body.ephemeral);await b.session.receive(authorized);await b.session.receive(intent(a,'RECOVERY_PROOF'));await a.session.receive(intent(b,'FINAL'));await b.session.receive(intent(a,'CONFIRM'));await a.session.receive(intent(b,'CONFIRM_ACK'));assert.equal(a.value.confirmed.root,b.value.confirmed.root);assert.equal(a.value.ledger.generation,3);
 // Expiry is durable/truthful. New randomness requires explicit retry after cooldown.
 const [m,n]=await pair();await m.session.initiate();const oldInit=intent(m,'INIT');await n.session.receive(oldInit);const lateFinal=intent(n,'FINAL');now+=86401;assert.equal((await m.session.status()).phase,'EXPIRED');assert.equal((await m.session.initiate()).phase,'EXPIRED');assert.equal(m.value.pending.kemSecret,undefined);await assert.rejects(()=>m.session.receive(lateFinal),/EXPIRED/);now+=5;await m.session.initiate({retry:true});assert.notEqual(intent(m,'INIT'),oldInit);assert(m.value.superseded.includes(await m.codec.frameDigest(oldInit)));
 // Signed refusal is accepted only for current exact outbound/context.
 const current=JSON.parse(intent(m,'INIT')),refusal={...current,sender:current.recipient,recipient:current.sender,kind:'REFUSE',body:{reference_digest:'ee'.repeat(32),reason:'SUITE_REQUIRED',supported_version:4,supported_suites:[profile.SUITE]}};delete refusal.signature;const wrongRef=n.codec.sign(refusal,n.core.keys.sign.secretKey);await assert.rejects(()=>m.session.receive(wrongRef),/REFUSAL_CONTEXT/);refusal.body.reference_digest=await m.codec.frameDigest(intent(m,'INIT'));const goodRef=n.codec.sign(refusal,n.core.keys.sign.secretKey);assert.equal((await m.session.receive(goodRef)).phase,'REFUSED');
 // Fault every durable initial transition, then crash/restart and duplicate delivery.
 const [u,v]=await pair();const transitions=[{target:u,run:()=>u.session.initiate()},{target:v,run:()=>v.session.receive(intent(u,'INIT'))},{target:u,run:()=>u.session.receive(intent(v,'FINAL'))},{target:v,run:()=>v.session.receive(intent(u,'CONFIRM'))},{target:u,run:()=>u.session.receive(intent(v,'CONFIRM_ACK'))}];
 for(const step of transitions){const before=JSON.stringify(step.target.value);step.target.failWrite=true;await assert.rejects(step.run,/WRITE_FAILED/);assert.equal(JSON.stringify(step.target.value),before,'failed transition changed state');step.target.failWrite=false;await step.run();const after=JSON.stringify(step.target.value);step.target.restart();await step.run();assert.equal(JSON.stringify(step.target.value),after,'duplicate regenerated durable capsule');}
 assert.equal(u.value.confirmed.root,v.value.confirmed.root);
 // Valid but expired proof cannot consume ticket or replace surviving session.
 await u.session.initiate({recover:true});await v.session.receive(intent(u,'INIT'));await v.session.receive(intent(u,'RECOVERY_REQUEST'));await u.session.receive(intent(v,'RECOVERY_CHALLENGE'));const expiredProof=intent(u,'RECOVERY_PROOF'),authorizedInit=intent(u,'INIT'),survivor=v.value.confirmed.root;await v.session.receive(authorizedInit);now+=601;await assert.rejects(()=>v.session.receive(expiredProof),/EXPIRED/);assert.equal(v.value.confirmed.root,survivor);assert.equal(v.value.recovery.consumed,false);
 // Owner invalidation during asynchronous cryptography cannot publish any state.
 const [w,z]=await pair();let entered,release;const gate=new Promise(r=>entered=r),originalDigest=w.codec.frameDigest;w.codec={...w.codec,frameDigest:async raw=>{entered();await new Promise(r=>release=r);return originalDigest(raw);}};w.restart();const late=w.session.initiate();await gate;w.current=false;release();await assert.rejects(()=>late,/STALE_OWNER/);assert.equal(w.value,null);w.current=true;
 // Consumed recovery ticket survives responder pending-state loss. Signed refusal
 // drives an explicit fresh workflow, never regeneration under the consumed ticket.
 const [aa,bb]=await pair();await establish(aa,bb);await aa.session.initiate({recover:true});await bb.session.receive(intent(aa,'INIT'));await bb.session.receive(intent(aa,'RECOVERY_REQUEST'));await aa.session.receive(intent(bb,'RECOVERY_CHALLENGE'));await bb.session.receive(intent(aa,'INIT'));const consumedProof=intent(aa,'RECOVERY_PROOF');await bb.session.receive(consumedProof);const abandonedFinal=intent(bb,'FINAL'),preservedRoot=bb.value.confirmed.root;bb.value.pending=null;bb.value.intents=[];bb.restart();assert.equal((await bb.session.receive(consumedProof)).phase,'RECOVERY_STATE_LOST');assert.equal(bb.value.confirmed.root,preservedRoot);await aa.session.receive(intent(bb,'REFUSE'));assert.equal((await aa.session.status()).phase,'REFUSED');now+=5;await aa.session.initiate({retry:true});await bb.session.receive(intent(aa,'INIT'));await bb.session.receive(intent(aa,'RECOVERY_REQUEST'));await aa.session.receive(intent(bb,'RECOVERY_CHALLENGE'));await bb.session.receive(intent(aa,'INIT'));await bb.session.receive(intent(aa,'RECOVERY_PROOF'));assert.notEqual(intent(bb,'FINAL'),abandonedFinal);await aa.session.receive(intent(bb,'FINAL'));await bb.session.receive(intent(aa,'CONFIRM'));await aa.session.receive(intent(bb,'CONFIRM_ACK'));assert.equal(aa.value.confirmed.root,bb.value.confirmed.root);
 console.log('Account session V4 real fresh X25519 + bundled Kyber: confirmation, stable retry, simultaneous init, one-sided recovery, stale replay, restart, storage failure, owner guard PASS; inactive modules, not browser/production acceptance');
})().catch(e=>{console.error(e);process.exitCode=1;});
