'use strict';
const assert=require('node:assert/strict'),{spawnSync}=require('node:child_process'),path=require('node:path');
global.nacl=require('../js/vendor/nacl-fast.min.js');const nacl=global.nacl,discovery=require('../js/route_discovery_v4.js'),profile=require('../js/account_handshake_v4.js');
const codec=profile.createCodec({nacl,discovery,clock:()=>1800000000}),a=nacl.sign.keyPair.fromSeed(new Uint8Array(32).fill(1)),b=nacl.sign.keyPair.fromSeed(new Uint8Array(32).fill(2)),x=nacl.box.keyPair.fromSecretKey(new Uint8Array(32).fill(3));
const base={type:'ACCOUNT_HANDSHAKE',version:4,suite:profile.SUITE,kind:'INIT',binding_digest:'22'.repeat(32),binding_generation:1,session_generation:1,attempt_id:'33'.repeat(32),sender:profile.hex(a.publicKey),recipient:profile.hex(b.publicKey),issued_at:1800000000,expires_at:1800000600,previous_session:null,body:{suites:[profile.SUITE],ephemeral:profile.hex(x.publicKey),kem_public:'44'.repeat(1184),nonce:'55'.repeat(32),authorization:null}};
const context={peer:base.sender,local:base.recipient,bindingDigest:base.binding_digest,bindingGeneration:1,requiredSuite:profile.SUITE};
(async()=>{const raw=codec.sign(base,a.secretKey);assert.equal(codec.verify(raw,context).kind,'INIT');assert.equal(codec.sign(base,a.secretKey),raw);assert.throws(()=>codec.verify(raw,{}),/PINNED_CONTEXT/);assert.throws(()=>codec.verify(raw,{...context,requiredSuite:'HYBRID_MLKEM768_V2'}),/SUITE_REQUIRED/);assert.throws(()=>codec.verify(' '+raw,context),/NON_CANONICAL/);assert.throws(()=>codec.verify(raw.replace('"version":4','"version":4,"version":4'),context),/NON_CANONICAL/);
for(const change of [{version:3},{suite:'CLASSICAL'},{sender:base.recipient},{binding_digest:'66'.repeat(32)},{extra:1},{expires_at:1800000000}])assert.throws(()=>codec.verify(JSON.stringify({...JSON.parse(raw),...change}),context));
for(const ephemeral of ['00'.repeat(32),'01'+'00'.repeat(31),'ff'.repeat(32),base.sender]){const bad=codec.sign({...base,body:{...base.body,ephemeral}},a.secretKey);assert.throws(()=>codec.verify(bad,context));}
const finalCore={init_digest:await codec.frameDigest(raw),ephemeral:profile.hex(nacl.box.keyPair.fromSecretKey(new Uint8Array(32).fill(4)).publicKey),capsule:'77'.repeat(1088),nonce:'88'.repeat(32)},sid=await codec.sessionTranscript(raw,finalCore),keys=await codec.derive(new Uint8Array(32).fill(9),new Uint8Array(32).fill(10),sid),mac=await codec.mac(keys.final,'FINAL',sid,finalCore.init_digest);assert.equal(new Set(Object.values(keys).map(profile.hex)).size,4);await codec.verifyMac(keys.final,'FINAL',mac,sid,finalCore.init_digest);await assert.rejects(()=>codec.verifyMac(keys.confirm,'FINAL',mac,sid,finalCore.init_digest),/KEY_CONFIRMATION/);await assert.rejects(()=>codec.derive(new Uint8Array(32),new Uint8Array(32).fill(10),sid),/SECRET/);
if(process.env.DMASH_HANDSHAKE_PYTHON==='1'){
 const script=`import sys,json,struct,hashlib,hmac\nfrom nacl.signing import VerifyKey\np=json.load(sys.stdin)\ndef canon(x):return json.dumps(x,separators=(',',':')).encode()\ndef domain(name,*parts):return b'D-MASH|ACCOUNT-HANDSHAKE|V4|'+name.encode()+bytes([0])+b''.join(struct.pack('>I',len(x))+x for x in parts)\nf=json.loads(p['raw']);sig=bytes.fromhex(f.pop('signature'));VerifyKey(bytes.fromhex(f['sender'])).verify(domain(f['kind'],canon(f)),sig)\nfd=hashlib.sha256(domain('FRAME',p['raw'].encode())).hexdigest();assert fd==p['core']['init_digest']\nsid=hashlib.sha256(domain('SESSION',p['raw'].encode(),canon(p['core']))).hexdigest();assert sid==p['sid']\nikm=struct.pack('>I',32)+bytes([9])*32+struct.pack('>I',32)+bytes([10])*32\nprk=hmac.new(bytes.fromhex(sid),ikm,hashlib.sha256).digest()\nfor label in ['root','final','confirm','ack']:\n info=domain('KEY|'+label,f['suite'].encode());key=hmac.new(prk,info+bytes([1]),hashlib.sha256).digest();assert key.hex()==p['keys'][label]\n if label=='final':assert hmac.new(key,domain('CONFIRM|FINAL',bytes.fromhex(sid),bytes.fromhex(fd)),hashlib.sha256).hexdigest()==p['mac']\nprint('Python/libsodium canonical signature + transcript + HKDF + HMAC vectors PASS')`;
 const result=spawnSync(process.env.DMASH_PYTHON||path.resolve(__dirname,'../../../.venv/bin/python'),['-c',script],{encoding:'utf8',input:JSON.stringify({raw,core:finalCore,sid,keys:Object.fromEntries(Object.entries(keys).map(([k,v])=>[k,profile.hex(v)])),mac})});assert.equal(result.status,0,result.stderr||result.error?.message);console.log(result.stdout.trim());}
console.log('Account handshake V4 strict pinned codec and separated confirmation keys PASS');})().catch(e=>{console.error(e);process.exitCode=1;});
