'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const nacl=require('../js/vendor/nacl-fast.min.js');
const material=pass=>new Uint8Array(128).fill(pass==='correct'?7:9);
const pk=pass=>Buffer.from(nacl.sign.keyPair.fromSeed(material(pass).slice(64,96)).publicKey).toString('hex');
function fixture(){
 const calls={vault:0,register:0,migration:0,material:0,launch:0};const root={root:new Uint8Array(32),identity:{deviceId:'root',fingerprints:{},signing:{},agreement:{}}};
 const storage={masterKey:{old:true},getRegistryAccount:async()=>({pk:pk('correct')+'a'.repeat(128)}),initGamma:async(_,{isCurrent})=>{assert(isCurrent());calls.vault++;},registerAccount:async()=>calls.register++};
 const win={location:{},addEventListener(){},nacl,argon2:{argon2id:2,hash:async({pass})=>({hash:material(pass)})},DeviceRoot:{state:root,deviceMaterial:async()=>{calls.material++;return new Uint8Array(3584);},migrateLegacy:async()=>{calls.migration++;return root;}},ui:{show_gate:async()=>{},update(){}}};
 const local={getItem:()=>null,setItem(){},removeItem(){},clear(){}};
 const c={console,Promise,Array,Map,Set,Object,Uint8Array,TextEncoder,window:win,ui:win.ui,document:{getElementById:()=>null},localStorage:local,sessionStorage:local,crypto,URL,Storage:storage,KyberWasm:{init(){}}};vm.createContext(c);vm.runInContext(fs.readFileSync(require.resolve('../js/core_engine.js'),'utf8'),c);
 const core=win.Core;core.deviceState=root;core.launchWorkspace=async()=>calls.launch++;core.advertiseActiveAccountPrivateRoutes=async()=>{};core.killAllMedia=()=>{};core.closeModal=()=>{};core.callState='idle';return{core,win,storage,calls,root};
}
(async()=>{
 const f=fixture(),original=f.core.keys,master=f.storage.masterKey;
 await assert.rejects(f.core.boot('saved','wrong',{register:true}),/Неверный ключ/);
 assert.equal(f.core.keys,original);assert.equal(f.storage.masterKey,master);assert.deepEqual(f.calls,{vault:0,register:0,migration:0,material:0,launch:0});assert.equal(f.core.activeIdentity,null);
 f.root.legacy=true;await assert.rejects(f.core.boot('saved','wrong'),/Неверный ключ/);assert.equal(f.calls.migration,0);delete f.root.legacy;
 await f.core.boot('saved','correct',{register:true});assert.equal(f.core.keys.server_id,pk('correct'));assert.equal(f.calls.vault,1);assert.equal(f.calls.register,1);assert(f.core.gammaKeys.master.some(x=>x!==0));
 const broken=fixture();broken.storage.getRegistryAccount=async()=>({pk:'corrupt'});await assert.rejects(broken.core.boot('saved','correct'),/Неверный ключ/);assert.equal(broken.calls.vault,0);
 const unavailable=fixture();unavailable.storage.getRegistryAccount=async()=>{throw Error('registry decrypt failed');};await assert.rejects(unavailable.core.boot('saved','correct'),/registry decrypt/);assert.equal(unavailable.calls.vault,0);
 const cancel=fixture();let release,started;const ready=new Promise(r=>started=r);cancel.win.argon2.hash=()=>new Promise(r=>{release=r;started();});const boot=assert.rejects(cancel.core.boot('saved','correct'),/ОТМЕНЁН/);await ready;await cancel.core.accountLogout();release({hash:material('correct')});await boot;assert.equal(cancel.calls.vault,0);assert.equal(cancel.core.activeIdentity,null);
 const concurrent=fixture();let finishFirst,entered;const firstReady=new Promise(r=>entered=r);let n=0;concurrent.win.argon2.hash=async()=>{if(++n===1)return new Promise(r=>{finishFirst=r;entered();});return {hash:material('correct')};};const first=assert.rejects(concurrent.core.boot('A','correct'),/ОТМЕНЁН/);await firstReady;await concurrent.core.boot('B','correct');finishFirst({hash:material('correct')});await first;assert.equal(concurrent.core.activeIdentity,'B');assert.equal(concurrent.calls.vault,1);
 const locked=fixture();let finishKdf,startedKdf;const kdfReady=new Promise(r=>startedKdf=r);locked.win.argon2.hash=()=>new Promise(r=>{finishKdf=r;startedKdf();});const lockedBoot=assert.rejects(locked.core.boot('saved','correct'),/ОТМЕНЁН/);await kdfReady;locked.win.DeviceRoot.state=null;finishKdf({hash:material('correct')});await lockedBoot;assert.equal(locked.calls.vault,0);assert.equal(locked.calls.launch,0);
 const opening=fixture();let finishOpen,startedOpen;const openReady=new Promise(r=>startedOpen=r);opening.storage.initGamma=async(_,{isCurrent})=>{await new Promise(r=>{finishOpen=r;startedOpen();});if(!isCurrent())throw Error('vault opening cancelled');opening.calls.vault++;};const openingBoot=assert.rejects(opening.core.boot('saved','correct',{register:true}),/cancelled/);await openReady;opening.win.DeviceRoot.state=null;finishOpen();await openingBoot;assert.equal(opening.calls.vault,0);assert.equal(opening.calls.register,0);assert.equal(opening.calls.launch,0);
 // Exercise the real Storage adapter's deferred commit, not a boot stub.
 let alive=true,request,closed=false;const storageContext={window:{crypto:{subtle:{importKey:async()=>({candidate:true})}}},indexedDB:{open(){request={};return request;}},console,Promise,Uint8Array};vm.createContext(storageContext);vm.runInContext(fs.readFileSync(require.resolve('../js/storage.js'),'utf8'),storageContext);const realStorage=storageContext.window.DMashStorage,oldMaster={existing:true};realStorage.masterKey=oldMaster;const pendingVault=assert.rejects(realStorage.initGamma(new Uint8Array(32),{isCurrent:()=>alive}),/cancelled/);await new Promise(r=>setImmediate(r));assert(request);alive=false;request.onsuccess({target:{result:{close(){closed=true;}}}});await pendingVault;assert.equal(realStorage.masterKey,oldMaster);assert.equal(realStorage.db,null);assert(closed);
 console.log('PASS saved Account identity refuses wrong/corrupt/unreadable binding before mutation; correct key, logout cancellation and concurrent login ownership');
})().catch(e=>{console.error(e);process.exitCode=1;});
