'use strict';
const assert=require('node:assert/strict');global.nacl=require('../js/vendor/nacl-fast.min.js');require('../js/secure_session.js');const discovery=require('../js/route_discovery_v4.js'),pairing=require('../js/account_pairing_v2.js').createCodec({nacl,discovery});const now=Math.floor(Date.now()/1000),binding=require('../js/account_route_binding_v2.js').createBindingCodec({nacl,discovery,pairing,clock:()=>now}),codec=require('../js/node_public_bootstrap_control_v4.js').createCodec({pairing,binding,clock:()=>now});
const hex=b=>Buffer.from(b).toString('hex');
function person(n){const key=()=>nacl.sign.keyPair(),box=()=>nacl.box.keyPair();return {account:key(),box:box(),route:key(),sign:key(),discovery:box(),recipient:box(),n};}
const a=person(1),b=person(2);
function bundle(p,target=null){const certificate=discovery.issueCertificate(p.route,p.sign.publicKey,p.discovery.publicKey,p.recipient.publicKey,{generation:1,issuedAt:now,expiresAt:now+3600});return pairing.sign({type:'DMASH_PAIRING_V2',version:2,transport_version:4,pairing_id:hex(crypto.getRandomValues(new Uint8Array(32))),generation:1,issued_at:now,expires_at:now+1800,previous_binding:null,intended_peer:target,contribution:hex(crypto.getRandomValues(new Uint8Array(32))),account_keys:{signing:hex(p.account.publicKey),box:hex(p.box.publicKey),kem_profile:'LEGACY_KYBER768_BUNDLE_V1',kem_public:Buffer.alloc(1184,p.n).toString('base64url')},inbound_certificate:certificate},p.account.secretKey,{now,localAccount:target??undefined}).serialized;}
const {NodeInboxV4}=require('../js/node_inbox_v4.js'),Local=require('../js/node_local_delivery_v4.js'),Ownership=require('../js/node_local_ownership_v4.js'),Runtime=require('../js/node_public_bootstrap_runtime_v4.js');require('../js/recipient_payload_v4.js');const privateCodec=require('../js/node_bootstrap_control_v4.js').createCodec({pairing,binding});
class Store{constructor(rows){this.rows=rows;}async open(){}async read(k){return structuredClone(this.rows.get(k)||null);}async all(){return structuredClone([...this.rows.values()].filter(r=>r.key!=='owner'&&!r.key.startsWith('binding:')));}async allBindings(){return [];}async cas(k,rev,row,{guard=()=>true}={}){guard();const old=this.rows.get(k);if((old?.revision??null)!==rev)return false;if(row===null)this.rows.delete(k);else this.rows.set(k,structuredClone({...row,key:k,revision:(rev??0)+1}));return true;}close(){}}
(async()=>{
 let dropNext=false;const routes=new Map(),deliveries=[],blobs=[],open=async(n,records=new Map())=>{
  const inbox=await NodeInboxV4.open(new Uint8Array(32).fill(n),'a'.repeat(64),{store:new Store(records)}),ownerInbox=await NodeInboxV4.open(new Uint8Array(32).fill(n+10),'b'.repeat(64),{store:new Store(new Map())}),local=new Local({},ownerInbox),ownership=new Ownership(local,ownerInbox),publicLocal={routes:new Map(),async discover(certificate){const target=routes.get(certificate.route_id);if(!target)throw Error('Fixture target missing');const handle=String(this.routes.size);this.routes.set(handle,{certificate,route:target});return {handle};}},runtime={bindLocal(cert,sign,box,handler){routes.set(cert.route_id,handler);},send(handler,payload){blobs.push(payload);if(dropNext){dropNext=false;return;}deliveries.push(handler(null,{payload}));}};
  const actor=new Runtime();Object.assign(actor,{runtime,ownership,local:publicLocal,inbox,codec,privateCodec,isCurrent:()=>true,closed:false});await actor.restore();return {actor,ownership,records,local,ownerInbox};
 },flush=async()=>{for(let empty=0;empty<3;){if(deliveries.length){empty=0;await Promise.all(deliveries.splice(0));}else empty++;await new Promise(r=>setTimeout(r,5));}};
 let left=await open(21),right=await open(22);const intake=await left.actor.register({kind:'PUBLIC_INTAKE',expiresAt:now+3600}),reply=await right.actor.register({kind:'PUBLIC_REPLY',expiresAt:now+3600}),requestData={requestId:'a'.repeat(64),displayName:'Neutral',introduction:'No Account needed',nonce:'b'.repeat(64)};
 await right.actor.request(reply.token,intake.certificate,requestData);await flush();let row=(await left.actor.list(intake.token))[0];assert.equal(row.state,'PENDING');assert.equal(row.claim,null);assert(!row.request.includes('account_keys'));
 const initialBlob=blobs[0];await right.actor.request(reply.token,intake.certificate,requestData);await flush();assert.equal(blobs[1],initialBlob,'exact persisted sealed request retry');assert.equal((await left.actor.list(intake.token)).length,1);
 await assert.rejects(right.actor.request(reply.token,intake.certificate,{...requestData,introduction:'changed'}));await assert.rejects(left.actor.list('forged-root-cap'));
 const localBundle=bundle(a),remoteBundle=bundle(b,hex(a.account.publicKey)),owner=async(side,p,offer)=>{const challenge=await side.ownership.challenge(hex(p.account.publicKey),JSON.parse(offer).inbound_certificate);return side.ownership.register(challenge.challenge,nacl.sign.detached(new TextEncoder().encode(challenge.transcript),p.account.secretKey));},leftOwner=await owner(left,a,localBundle),rightOwner=await owner(right,b,remoteBundle);
 const claim=await left.actor.claim(intake.token,leftOwner.token,row.requestId,row.requestDigest,localBundle);assert.equal((await left.actor.list(intake.token))[0].claim.bootstrapKey,undefined);await assert.rejects(left.actor.decline(intake.token,row.requestId,row.requestDigest));
 const requestHandle=await codec.inspectRequest(intake.certificate,row.request),acceptWire=await codec.accept(requestHandle,{bundle:localBundle,bootstrapBox:claim.bootstrapBox},a.account.secretKey);await left.actor.accept(intake.token,leftOwner.token,row.requestId,acceptWire);await flush();assert.equal((await right.actor.list(reply.token))[0].state,'CANDIDATE');
 const acceptHandle=await codec.inspectAccept(requestHandle,acceptWire),people=[a,b].sort((x,y)=>hex(x.account.publicKey).localeCompare(hex(y.account.publicKey))),candidate=await binding.prepare([localBundle,remoteBundle],{expectedParticipants:people.map(p=>hex(p.account.publicKey)),committed:null}),first=binding.signReceipt(candidate,'ACCEPT',people[0].account.secretKey),second=binding.signReceipt(candidate,'CONFIRM',people[1].account.secretKey,first),confirmWire=await codec.confirm(acceptHandle,{bundle:remoteBundle,acceptReceipt:people[0]===b?first:null},b.account.secretKey);
 await right.actor.confirm(reply.token,rightOwner.token,row.requestId,confirmWire);await flush();assert.equal((await left.actor.list(intake.token))[0].state,'CONFIRMED');
 dropNext=true;await left.actor.receipt(intake.token,leftOwner.token,row.requestId,people[0]===a?first:second);const lostAck=blobs.at(-1);await flush();await right.actor.confirm(reply.token,rightOwner.token,row.requestId,confirmWire);await flush();assert.equal(blobs.at(-1),lostAck,'duplicate CONFIRM resends exact durable ACK envelope');if(people[0]===a){await right.actor.receipt(reply.token,rightOwner.token,row.requestId,second);await flush();}
 for(const [side,cap] of [[left,intake],[right,reply]]){const record=(await side.actor.list(cap.token))[0];assert.equal(Object.keys(record.receipts).length,2);assert.equal(record.state,'CONFIRMED');assert(!JSON.stringify(record).includes('bootstrapKey'));assert.equal(side.local.bindings.size,0);}
 left.ownership.owners.delete(leftOwner.token);await assert.rejects(left.actor.accept(intake.token,leftOwner.token,row.requestId,acceptWire));
 const records=left.records;left.actor.close();left=await open(21,records);const reopened=await left.actor.register({id:intake.id});assert.equal((await left.actor.list(reopened.token))[0].state,'CONFIRMED');await assert.rejects(left.actor.list(intake.token));
 const denyData={...requestData,requestId:'d'.repeat(64)};await right.actor.request(reply.token,intake.certificate,denyData);await flush();const denied=(await left.actor.list(reopened.token)).find(v=>v.requestId===denyData.requestId);await left.actor.decline(reopened.token,denied.requestId,denied.requestDigest);await right.actor.request(reply.token,intake.certificate,denyData);await flush();assert.equal((await left.actor.list(reopened.token)).find(v=>v.requestId===denyData.requestId).state,'DENIED');
 for(let i=0;i<14;i++){await right.actor.request(reply.token,intake.certificate,{...requestData,requestId:(i+16).toString(16).padStart(64,'0')});await flush();}await assert.rejects(right.actor.request(reply.token,intake.certificate,{...requestData,requestId:'f'.repeat(64)}),/quota/);assert.equal((await left.actor.list(reopened.token)).length,16);
 for(const side of [left,right]){side.actor.close();side.ownership.close();side.local.close();side.ownerInbox.close();}
 console.log('PASS public encrypted journal: genuine owner claim, exact sealed retry, neutral intake, full receipts, revoked owner, encrypted reopen, no final activation; transport fixture is in-process only');
})().catch(e=>{console.error(e);process.exitCode=1;});
