'use strict';
const assert=require('node:assert/strict');global.nacl=require('../js/vendor/nacl-fast.min.js');require('../js/secure_session.js');const discovery=require('../js/route_discovery_v4.js'),pairing=require('../js/account_pairing_v2.js').createCodec({nacl,discovery});const now=Math.floor(Date.now()/1000),binding=require('../js/account_route_binding_v2.js').createBindingCodec({nacl,discovery,pairing,clock:()=>now}),codec=require('../js/node_bootstrap_control_v4.js').createCodec({pairing,binding,clock:()=>now});
const hex=b=>Buffer.from(b).toString('hex');
function person(n){const key=()=>nacl.sign.keyPair(),box=()=>nacl.box.keyPair();return {account:key(),box:box(),route:key(),sign:key(),discovery:box(),recipient:box(),n};}
const a=person(1),b=person(2);
function bundle(p,target=null){const certificate=discovery.issueCertificate(p.route,p.sign.publicKey,p.discovery.publicKey,p.recipient.publicKey,{generation:1,issuedAt:now,expiresAt:now+3600});return pairing.sign({type:'DMASH_PAIRING_V2',version:2,transport_version:4,pairing_id:hex(crypto.getRandomValues(new Uint8Array(32))),generation:1,issued_at:now,expires_at:now+1800,previous_binding:null,intended_peer:target,contribution:hex(crypto.getRandomValues(new Uint8Array(32))),account_keys:{signing:hex(p.account.publicKey),box:hex(p.box.publicKey),kem_profile:'LEGACY_KYBER768_BUNDLE_V1',kem_public:Buffer.alloc(1184,p.n).toString('base64url')},inbound_certificate:certificate},p.account.secretKey,{now,localAccount:target??undefined}).serialized;}
(async()=>{
 const ab=bundle(a),bb=bundle(b,hex(a.account.publicKey)),people=[a,b].sort((x,y)=>hex(x.account.publicKey).localeCompare(hex(y.account.publicKey))),candidate=await binding.prepare([ab,bb],{expectedParticipants:people.map(p=>hex(p.account.publicKey)),committed:null});
 const accept=binding.signReceipt(candidate,'ACCEPT',people[0].account.secretKey),confirm=binding.signReceipt(candidate,'CONFIRM',people[1].account.secretKey,accept);
 const wire=await codec.request(ab,bb,'a'.repeat(64),b.account.secretKey,{acceptReceipt:people[0]===b?accept:null}),verified=await codec.inspect(ab,wire);
 const reverseLocal=bundle(b),reverseSender=bundle(a,hex(b.account.publicKey)),reverseCandidate=await binding.prepare([reverseLocal,reverseSender],{expectedParticipants:people.map(p=>hex(p.account.publicKey)),committed:null}),reverseAccept=binding.signReceipt(reverseCandidate,'ACCEPT',people[0].account.secretKey);
 const reverseWire=await codec.request(reverseLocal,reverseSender,'e'.repeat(64),a.account.secretKey,{acceptReceipt:people[0]===a?reverseAccept:null});assert.equal((await codec.inspect(reverseLocal,reverseWire)).bindingDigest,reverseCandidate.digest);
 assert.equal(verified.identityStatus,'UNSELECTED_CANDIDATE');assert.equal(verified.bindingDigest,candidate.digest);assert.equal(codec.receipt(verified,accept).phase,'ACCEPT');assert.equal(codec.receipt(verified,confirm).phase,'CONFIRM');
 await assert.rejects(codec.inspect(bb,wire));await assert.rejects(codec.inspect(ab,' '+wire));await assert.rejects(codec.inspect(ab,JSON.stringify({...JSON.parse(wire),exchange_id:'b'.repeat(64)})));
 assert.throws(()=>codec.receipt({...verified},accept));assert.throws(()=>codec.receipt(verified,'user-message'));assert.throws(()=>codec.fits('"'.repeat(10000)));
 const {NodeInboxV4}=require('../js/node_inbox_v4.js'),Local=require('../js/node_local_delivery_v4.js'),Ownership=require('../js/node_local_ownership_v4.js'),Dispatcher=require('../js/node_bootstrap_dispatcher_v4.js');
 class Store{constructor(rows){this.rows=rows;}async open(){}async read(k){return structuredClone(this.rows.get(k)||null);}async all(){return structuredClone([...this.rows.values()].filter(r=>r.key!=='owner'&&!r.key.startsWith('binding:')));}async allBindings(){return structuredClone([...this.rows.values()].filter(r=>r.key==='owner'||r.key.startsWith('binding:')));}async cas(k,rev,row,{guard=()=>true}={}){guard();const old=this.rows.get(k);if((old?.revision??null)!==rev)return false;if(row===null)this.rows.delete(k);else this.rows.set(k,structuredClone({...row,key:k,revision:(rev??0)+1}));return true;}close(){}}
 const authorityInbox=await NodeInboxV4.open(new Uint8Array(32).fill(31),'a'.repeat(64),{store:new Store(new Map())}),local=new Local({},authorityInbox),ownership=new Ownership(local,authorityInbox),challenge=await ownership.challenge(hex(a.account.publicKey),JSON.parse(ab).inbound_certificate),owner=await ownership.register(challenge.challenge,nacl.sign.detached(new TextEncoder().encode(challenge.transcript),a.account.secretKey));
 const records=new Map(),open=()=>NodeInboxV4.open(new Uint8Array(32).fill(32),'a'.repeat(64),{store:new Store(records)});
 let inbox=await open(),dispatcher=new Dispatcher({ownership,inbox,codec,clock:()=>now});await dispatcher.register(owner.token,ab);
 const pending=await dispatcher.request(owner.token,wire);assert.equal(pending.state,'PENDING');assert.equal((await dispatcher.request(owner.token,wire)).duplicate,true);
 await assert.rejects(dispatcher.receipt(owner.token,'a'.repeat(64),accept),/selection/);
 await dispatcher.select(owner.token,'a'.repeat(64),pending.requestDigest);await dispatcher.receipt(owner.token,'a'.repeat(64),accept);await dispatcher.receipt(owner.token,'a'.repeat(64),confirm);
 assert.equal((await dispatcher.receipt(owner.token,'a'.repeat(64),confirm)).duplicate,true);assert.equal(local.bindings.size,0,'controls never activate final mapping');
 dispatcher.close();inbox=await open();dispatcher=new Dispatcher({ownership,inbox,codec,clock:()=>now});assert.equal((await dispatcher.list(owner.token))[0].state,'SELECTED');assert.equal((await dispatcher.request(owner.token,wire)).duplicate,true);
 const deniedWire=await codec.request(ab,bb,'d'.repeat(64),b.account.secretKey,{acceptReceipt:people[0]===b?accept:null}),denied=await dispatcher.request(owner.token,deniedWire);await dispatcher.select(owner.token,'d'.repeat(64),denied.requestDigest,{deny:true});assert.equal((await dispatcher.request(owner.token,deniedWire)).state,'DENIED');await assert.rejects(dispatcher.select(owner.token,'d'.repeat(64),denied.requestDigest));
 await assert.rejects(dispatcher.request('unregistered-owner',wire));assert(!JSON.stringify([...records.values()]).includes(bb));
 const expired=new Dispatcher({ownership,inbox:await open(),codec,clock:()=>now+2000});assert.equal((await expired.list(owner.token))[0].state,'EXPIRED_SELECTED');expired.close();
 dispatcher.close();ownership.close();local.close();authorityInbox.close();
 console.log('PASS bootstrap REQUEST authenticates second bundle before receipts, target/signer/canonical binding, no implicit selection, bounded recipient-envelope expansion');
})().catch(e=>{console.error(e);process.exitCode=1;});
