'use strict';
const assert=require('node:assert/strict');
const Coordinator=require('../js/node_runtime_coordinator_v4.js');
const deferred=()=>{let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no;});return {promise,resolve,reject};};
function root(){const listeners=new Set();return {state:null,onLock(fn){listeners.add(fn);return()=>listeners.delete(fn);},unlock(){this.state={root:new Uint8Array(32).fill(7)};},lock(){this.state=null;for(const fn of [...listeners])fn();},listeners};}
function host(){return {closed:false,calls:[],connect(value){this.calls.push(value);return Promise.resolve({connected:true});},close(){this.closed=true;}};}
const pin={version:4,nodeId:'a'.repeat(64),url:'wss://node.example/mesh/v4'};
(async()=>{
 const r=root(),pending=deferred();let calls=0,signal;const c=new Coordinator(r,{trustedDescriptors:[pin],hostFactory:{startForDevice(_,{signal:s}){calls++;signal=s;return pending.promise;}}});
 await assert.rejects(c.start(),{code:'NODE_ROOT_LOCKED'});assert.equal(calls,0);r.unlock();const first=c.start(),second=c.start();assert.equal(first,second);await Promise.resolve();assert.equal(calls,1);assert.equal(c.status().state,'STARTING');r.lock();await assert.rejects(first,{code:'NODE_SESSION_CHANGED'});assert(signal.aborted);const stale=host();pending.resolve(stale);await new Promise(resolve=>setImmediate(resolve));assert(stale.closed);assert.equal(c.status().state,'STOPPED');assert.throws(()=>c.capture(),{code:'NODE_RUNTIME_UNAVAILABLE'});c.close();assert.equal(r.listeners.size,0);
 const r2=root();r2.unlock();const starts=[];const c2=new Coordinator(r2,{trustedDescriptors:[pin],hostFactory:{startForDevice(){const value=host();starts.push(value);return Promise.resolve(value);}}});const h=await c2.start(),capture=c2.capture();assert(capture.current());assert(c2.isCurrentToken(capture.token));assert(!c2.isCurrentToken({...capture.token}));assert.equal(await c2.start(),h);assert.equal(starts.length,1);
 const [peer]=c2.peers();await assert.rejects(c2.connect(pin),{code:'NODE_DESCRIPTOR_UNTRUSTED'});await assert.rejects(c2.connect({trusted:true}),{code:'NODE_DESCRIPTOR_UNTRUSTED'});await c2.connect(peer.token);assert.deepEqual(h.calls[0],{url:pin.url,nodeId:pin.nodeId,password:undefined});pin.nodeId='b'.repeat(64);assert.equal(peer.descriptor.nodeId,'a'.repeat(64),'catalog is copied, never socket-learned/mutable caller authority');
 // Changing unrelated Account state cannot stop this Account-independent owner.
 global.Core={activeIdentity:'A',keys:{}};global.Core={activeIdentity:null,keys:null};assert(capture.current());assert(!h.closed);delete global.Core;
 const connection=deferred();h.connect=()=>connection.promise;const inFlight=c2.connect(peer.token);await Promise.resolve();await Promise.resolve();c2.stop();connection.resolve({connected:true});await assert.rejects(inFlight,{code:'NODE_SESSION_CHANGED'});assert(!capture.current());assert(!c2.isCurrentToken(capture.token));assert(h.closed);await c2.start();assert.equal(starts.length,2);r2.lock();assert(starts[1].closed);assert.equal(c2.status().state,'STOPPED');c2.close();await assert.rejects(c2.start(),{code:'NODE_COORDINATOR_CLOSED'});
 // An old failed startup must not tear down a newer root's runtime.
 const r3=root();r3.unlock();const old=deferred(),fresh=host();let n=0;const c3=new Coordinator(r3,{hostFactory:{startForDevice:()=>++n===1?old.promise:Promise.resolve(fresh)}});const oldStart=c3.start();await Promise.resolve();r3.lock();await assert.rejects(oldStart,{code:'NODE_SESSION_CHANGED'});r3.unlock();await c3.start();old.reject(Error('stale failure'));await new Promise(resolve=>setImmediate(resolve));assert(!fresh.closed);assert(c3.capture().current());c3.close();
 for(const value of [{version:3,nodeId:'a'.repeat(64),url:'wss://node.example/mesh/v4'},{version:4,nodeId:'a'.repeat(64),url:'ws://node.example/mesh/v4'},{version:4,nodeId:'a'.repeat(64),url:'wss://user:password@node.example/mesh/v4'},{version:4,nodeId:'a'.repeat(64),url:'wss://node.example/dmp-c/v3'},{version:4,nodeId:'a'.repeat(64),url:'wss://node.example/mesh/v4#secret'},{version:4,nodeId:null,url:'wss://node.example/mesh/v4'}])assert.throws(()=>new Coordinator(root(),{trustedDescriptors:[value],hostFactory:{startForDevice(){}}}),{code:'NODE_DESCRIPTOR_INVALID'});
 console.log('PASS inactive Node coordinator: coalesced root ownership, lock/cancel/stale-start isolation, Account independence, opaque session/canonical pinned-peer capabilities and no v3 conversion');
})().catch(error=>{console.error(error);process.exitCode=1;});
