'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(require('node:path').join(__dirname,'../js/acceptance_v50.js'),'utf8');
const body=source.slice(source.indexOf('core.sendPublicContactRequest ='),source.indexOf('// Quick Names are a chooser'));
function fixture(recordHook=async()=>{},dispatchHook=async()=>true){let resolve;const gate=new Promise(r=>resolve=r),events=[],listeners={};let modal=false;const root={};const core={activeIdentity:'A',openModal(){modal=true;events.push('loading');},closeModal(){modal=false;},customAlert(a){modal=false;events.push(a);},getContactFlowV3(){return {async recordOutgoing(...args){events.push(['record',args[2]]);await recordHook();},async dispatchInitial(){events.push('dispatch');return dispatchHook();}}}};const global={DeviceRoot:{state:root,onLock(fn){listeners.lock=fn;return()=>{};}},ContactFlowV3:{},DeviceRoutes:{verifyCertificate:()=>true,currentActivePublicRoute:()=>null,issue:async()=>{await gate;return {certificate:{},routeId:'reply'};}},NodeManager:{transportMode:'v3',probeActivePublicDeviceRoutes:()=>{events.push('probe');return gate;}},ContactPayloads:{validateRequest:r=>r},ContactTransport:class{constructor(o){this.o=o;}async deliver(){return this.o.submit({routeLocator:'r',envelope:{}});}}};vm.runInNewContext(body,{core,global,document:{querySelector(sel){return modal?{addEventListener(_,fn){listeners.cancel=fn;}}:null;}},plainCertificate:c=>c,b64url:()=> 'request',crypto:{getRandomValues:x=>x},Uint8Array,sealForCertificate:()=>{},setInterval:fn=>(listeners.watch=fn),clearInterval(){},setTimeout:fn=>(listeners.timeout=fn),clearTimeout(){}});return {core,global,events,listeners,resolve};}
(async()=>{
for(const mode of ['cancel','timeout','account','root','relogin','transition','keys','salt']){const f=fixture(),job=f.core.sendPublicContactRequest({r:'r',c:{routeId:'r'}},'n','i');assert.deepEqual(f.events,['loading']);if(mode==='cancel')f.listeners.cancel();if(mode==='timeout')f.listeners.timeout();if(mode==='account')f.core.activeIdentity='B';if(mode==='root')f.global.DeviceRoot.state={};if(mode==='relogin')f.core._accountBootAttempt=1;if(mode==='transition')f.core._accountTransitioning=true;if(mode==='keys')f.core.keys={};if(mode==='salt')f.core.blindSalt='new';f.resolve();await job;assert(!f.events.some(e=>Array.isArray(e)||e==='dispatch'),mode+' cannot persist or dispatch stale request');assert(!f.events.includes('ОТПРАВЛЕНО'));}
const f=fixture(),job=f.core.sendPublicContactRequest({r:'r',c:{routeId:'r'}},'n','i');f.resolve();await job;assert.deepEqual(f.events,['loading',['record','A'],'dispatch','ЗАПРОС СОХРАНЁН']);assert.equal(f.core._publicRequestPreparation,null);
const retry=fixture(),old=retry.core.sendPublicContactRequest({r:'r',c:{routeId:'r'}},'n','i');retry.listeners.cancel();assert.equal(retry.core._publicRequestPreparation,null);const current=retry.core.sendPublicContactRequest({r:'r',c:{routeId:'r'}},'n2','i');retry.resolve();await Promise.all([old,current]);assert.equal(retry.events.filter(e=>Array.isArray(e)).length,1,'cancelled job cannot affect retry');
const slow=fixture(undefined,()=>new Promise(()=>{}));const saved=slow.core.sendPublicContactRequest({r:'r',c:{routeId:'r'}},'n','i');slow.resolve();await saved;assert(slow.events.includes('ЗАПРОС СОХРАНЁН'),'slow proof/dispatch cannot block durable waiting result');assert(!slow.events.includes('probe'),'durable dispatcher owns route activation');assert(!slow.events.includes('ОТПРАВЛЕНО'));
let recordStarted,finishRecord;const started=new Promise(r=>recordStarted=r),recordGate=new Promise(r=>finishRecord=r);const locked=fixture(async()=>{recordStarted();await recordGate;});const durable=locked.core.sendPublicContactRequest({r:'r',c:{routeId:'r'}},'n','i');locked.resolve();await started;locked.listeners.lock();assert.equal(locked.core._publicRequestPreparation,null,'lock releases durable operation UI ownership');finishRecord();await durable;assert(locked.events.some(e=>Array.isArray(e)),'durable record preserved');assert(!locked.events.includes('dispatch'));assert(!locked.events.includes('ОТПРАВЛЕНО'));
console.log('PASS public request preparation: cancel/timeout, Account/root/same-slot relogin/keys/salt/transition, durable lock, success, immediate retry');
})().catch(e=>{console.error(e);process.exitCode=1;});
