"use strict";

/*
 * Device-scoped Route foundation.
 *
 * Route private keys are generated by TweetNaCl's CSPRNG and are handed only to
 * DeviceRoot.deviceMaterial().  The DeviceRoot record therefore contains their
 * AES-GCM encrypted representation; this module's small local index contains
 * only public certificates and local routing policy.  Route certificates are
 * deliberately policy-free: `type` and `allowedAccounts` never leave this
 * device through a RouteCertificateV1.
 */
(function (global) {
    const VERSION = 1;
    const INDEX_KEY = "dmash/routes/v1/index";
    const MATERIAL_PREFIX = "dmash/routes/v1/material/";
    const CERT_LABEL = "dmash/route-certificate/v1";
    const MAX_REISSUE_HISTORY = 1; // current + one previous route, no more
    const text = (value) => new TextEncoder().encode(value);
    const b64url = (bytes) => {
        let binary = "";
        for (const byte of bytes) binary += String.fromCharCode(byte);
        return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, "");
    };
    const unb64url = (value) => {
        if (typeof value !== "string" || !/^[A-Za-z0-9_-]*$/.test(value)) throw new RouteError("INVALID_ENCODING", "Route key encoding is invalid.");
        const padded = value.replace(/-/g, "+").replace(/_/g, "/") + "=".repeat((4 - value.length % 4) % 4);
        return new Uint8Array(atob(padded).split("").map((c) => c.charCodeAt(0)));
    };
    const u32 = (value) => {
        const out = new Uint8Array(4); new DataView(out.buffer).setUint32(0, value, false); return out;
    };
    const u64 = (value) => {
        const out = new Uint8Array(8); const view = new DataView(out.buffer); const n = BigInt(value);
        view.setUint32(0, Number(n >> 32n), false); view.setUint32(4, Number(n & 0xffffffffn), false); return out;
    };
    const join = (...parts) => {
        const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0)); let at = 0;
        for (const part of parts) { out.set(part, at); at += part.length; } return out;
    };
    const field = (bytes) => join(u32(bytes.length), bytes);

    class RouteError extends Error {
        constructor(code, message) { super(message); this.name = "RouteError"; this.code = code; }
    }

    const Routes = {
        VERSION,
        MAX_REISSUE_HISTORY,
        _storage: null,
        setStorageForTests(storage) { this._storage = storage; },
        resetForTests() { this._storage = null; },
        _store() { return this._storage || global.localStorage; },
        _requirePrimitives() {
            if (!global.crypto?.getRandomValues || !global.nacl?.sign?.keyPair || !global.nacl?.box?.keyPair || !global.nacl?.sign?.detached) {
                throw new RouteError("CRYPTO_UNAVAILABLE", "Route cryptographic primitives are unavailable.");
            }
            if (!global.DeviceRoot?.deviceMaterial) throw new RouteError("DEVICE_ROOT_UNAVAILABLE", "DeviceRoot is required for route key storage.");
        },
        _policy(type, allowedAccounts) {
            if (typeof type !== "string" || !type || type.length > 128) throw new RouteError("INVALID_TYPE", "Route type must be a non-empty local string.");
            if (!Array.isArray(allowedAccounts) || allowedAccounts.some((account) => typeof account !== "string" || !account || account.length > 512)) {
                throw new RouteError("INVALID_ALLOWED_ACCOUNTS", "allowedAccounts must be local non-empty account identifiers.");
            }
            return { type, allowedAccounts: [...new Set(allowedAccounts)].sort() };
        },
        // Canonical byte transcript: label + version + fixed public keys + u64
        // issue time. It has no JSON serialization or optional fields.
        certificateTranscript(certificate) {
            if (!certificate || certificate.version !== VERSION || !Number.isSafeInteger(certificate.issuedAt) || certificate.issuedAt < 0) {
                throw new RouteError("INVALID_CERTIFICATE", "Route certificate fields are invalid.");
            }
            const routeId = unb64url(certificate.routeId);
            const signing = unb64url(certificate.signingPublicKey);
            const box = unb64url(certificate.boxPublicKey);
            if (routeId.length !== 32 || signing.length !== 32 || box.length !== 32 || certificate.routeId !== certificate.signingPublicKey) {
                throw new RouteError("INVALID_CERTIFICATE", "RouteID must equal the 32-byte signing public key.");
            }
            return join(field(text(CERT_LABEL)), u32(VERSION), field(signing), field(box), u64(certificate.issuedAt));
        },
        verifyCertificate(certificate) {
            try {
                const signature = unb64url(certificate.signature);
                return signature.length === 64 && global.nacl.sign.detached.verify(this.certificateTranscript(certificate), signature, unb64url(certificate.signingPublicKey));
            } catch (_) { return false; }
        },
        _loadIndex() {
            const raw = this._store()?.getItem(INDEX_KEY);
            if (!raw) return { version: VERSION, current: null, previous: null };
            try {
                const index = JSON.parse(raw);
                if (index.version !== VERSION || !Object.hasOwn(index, "current") || !Object.hasOwn(index, "previous")) throw new Error();
                return index;
            } catch (_) { throw new RouteError("INDEX_CORRUPT", "Local route index is corrupt and was not replaced."); }
        },
        _saveIndex(index) { this._store().setItem(INDEX_KEY, JSON.stringify(index)); },
        _emitLifecycle(event, route) {
            if (typeof global.dispatchEvent !== "function" || typeof global.CustomEvent !== "function") return;
            global.dispatchEvent(new global.CustomEvent("dmash-device-route", {
                detail: { event, route: route ? this.publicRoute(route) : null }
            }));
        },
        _newMaterialName() {
            const bytes = global.crypto.getRandomValues(new Uint8Array(16));
            return MATERIAL_PREFIX + b64url(bytes);
        },
        async _generate(materialName, policy, issuedAt) {
            const encoded = await global.DeviceRoot.deviceMaterial(materialName, () => {
                const signing = global.nacl.sign.keyPair();
                const box = global.nacl.box.keyPair();
                return text(JSON.stringify({ version: VERSION, signingSecretKey: b64url(signing.secretKey), boxSecretKey: b64url(box.secretKey) }));
            });
            let privateMaterial;
            try { privateMaterial = JSON.parse(new TextDecoder().decode(encoded)); }
            finally { encoded.fill(0); }
            if (privateMaterial.version !== VERSION) throw new RouteError("MATERIAL_CORRUPT", "Route private material is unsupported.");
            const signingSecretKey = unb64url(privateMaterial.signingSecretKey);
            const boxSecretKey = unb64url(privateMaterial.boxSecretKey);
            let signing, box;
            try {
                if (!global.nacl.sign.keyPair.fromSecretKey || !global.nacl.box.keyPair.fromSecretKey) throw new Error();
                signing = global.nacl.sign.keyPair.fromSecretKey(signingSecretKey);
                box = global.nacl.box.keyPair.fromSecretKey(boxSecretKey);
            } catch (_) { throw new RouteError("MATERIAL_CORRUPT", "Route private material cannot be read."); }
            const signingPublicKey = b64url(signing.publicKey);
            const certificate = { version: VERSION, routeId: signingPublicKey, signingPublicKey, boxPublicKey: b64url(box.publicKey), issuedAt };
            certificate.signature = b64url(global.nacl.sign.detached(this.certificateTranscript(certificate), signingSecretKey));
            signingSecretKey.fill(0); boxSecretKey.fill(0);
            return { materialName, certificate, type: policy.type, allowedAccounts: policy.allowedAccounts };
        },
        async issue({ type, allowedAccounts = [], issuedAt = Date.now() } = {}) {
            this._requirePrimitives();
            const policy = this._policy(type, allowedAccounts);
            if (!Number.isSafeInteger(issuedAt) || issuedAt < 0) throw new RouteError("INVALID_ISSUED_AT", "Route issue time is invalid.");
            const index = this._loadIndex();
            const current = await this._generate(this._newMaterialName(), policy, issuedAt);
            // Reissue fallback is strictly bounded: retain only the immediately
            // preceding route, replacing any older fallback in the public index.
            this._saveIndex({ version: VERSION, current, previous: index.current || null });
            this._emitLifecycle(index.current ? "ROUTE_REISSUED" : "ROUTE_ISSUED", current);
            return this.publicRoute(current);
        },
        publicRoute(route) {
            if (!route?.certificate || !this.verifyCertificate(route.certificate)) throw new RouteError("INVALID_CERTIFICATE", "Route certificate self-signature is invalid.");
            return Object.freeze({ routeId: route.certificate.routeId, certificate: Object.freeze({ ...route.certificate }) });
        },
        current() {
            const route = this._loadIndex().current;
            return route ? this.publicRoute(route) : null;
        },
        // Resolution is local-only and considers current then exactly one prior
        // reissue. It returns policy but never a private key.
        resolve(routeId) {
            if (typeof routeId !== "string") return null;
            const { current, previous } = this._loadIndex();
            for (const route of [current, previous]) {
                if (route?.certificate?.routeId === routeId && this.verifyCertificate(route.certificate)) {
                    return Object.freeze({ ...this.publicRoute(route), type: route.type, allowedAccounts: Object.freeze([...route.allowedAccounts]) });
                }
            }
            return null;
        }
    };

    global.DeviceRoutes = Routes;
    global.RouteError = RouteError;
    if (typeof module !== "undefined") module.exports = { DeviceRoutes: Routes, RouteError };
})(typeof window !== "undefined" ? window : globalThis);
