"use strict";

/*
 * Device-scoped Route foundation.
 *
 * Route private keys are generated by TweetNaCl's CSPRNG and are handed only to
 * DeviceRoot.deviceMaterial().  The DeviceRoot record therefore contains their
 * AES-GCM encrypted representation; this module's small local index contains
 * only public certificates and local routing policy.  Route certificates are
 * deliberately policy-free: `type` and `allowedAccounts` never leave this
 * device through a RouteCertificateV1.
 */
(function (global) {
    const VERSION = 1;
    const INDEX_KEY = "dmash/routes/v1/index";
    const MATERIAL_PREFIX = "dmash/routes/v1/material/";
    const CERT_LABEL = "dmash/route-certificate/v1";
    const ENTRY_GRANT_VERSION = "EntryGrantV1";
    const ENTRY_GRANT_LABEL = "D-MASH|ENTRY_GRANT|V1\0";
    const MAX_REISSUE_HISTORY = 1; // current + one previous route, no more
    const text = (value) => new TextEncoder().encode(value);
    const b64url = (bytes) => {
        let binary = "";
        for (const byte of bytes) binary += String.fromCharCode(byte);
        return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, "");
    };
    const unb64url = (value) => {
        if (typeof value !== "string" || !/^[A-Za-z0-9_-]*$/.test(value)) throw new RouteError("INVALID_ENCODING", "Route key encoding is invalid.");
        const padded = value.replace(/-/g, "+").replace(/_/g, "/") + "=".repeat((4 - value.length % 4) % 4);
        const bytes = new Uint8Array(atob(padded).split("").map((c) => c.charCodeAt(0)));
        if (b64url(bytes) !== value) throw new RouteError("INVALID_ENCODING", "Route key encoding is not canonical.");
        return bytes;
    };
    const hexBytes = (value) => {
        if (typeof value !== "string" || !/^[0-9a-f]{64}$/.test(value)) throw new RouteError("INVALID_NODE_ID", "NodeID must be a lowercase 32-byte Ed25519 key in hex.");
        return new Uint8Array(value.match(/../g).map((pair) => Number.parseInt(pair, 16)));
    };
    const u32 = (value) => {
        const out = new Uint8Array(4); new DataView(out.buffer).setUint32(0, value, false); return out;
    };
    const u64 = (value) => {
        if (!Number.isSafeInteger(value) || value < 0) throw new RouteError("INVALID_INTEGER", "EntryGrant integer is invalid.");
        const out = new Uint8Array(8); const view = new DataView(out.buffer); const n = BigInt(value);
        view.setUint32(0, Number(n >> 32n), false); view.setUint32(4, Number(n & 0xffffffffn), false); return out;
    };
    const join = (...parts) => {
        const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0)); let at = 0;
        for (const part of parts) { out.set(part, at); at += part.length; } return out;
    };
    const field = (bytes) => join(u32(bytes.length), bytes);

    class RouteError extends Error {
        constructor(code, message) { super(message); this.name = "RouteError"; this.code = code; }
    }

    const Routes = {
        VERSION,
        MAX_REISSUE_HISTORY,
        _storage: null,
        setStorageForTests(storage) { this._storage = storage; },
        resetForTests() { this._storage = null; },
        _store() { return this._storage || global.localStorage; },
        _requirePrimitives() {
            if (!global.crypto?.getRandomValues || !global.nacl?.sign?.keyPair || !global.nacl?.box?.keyPair || !global.nacl?.sign?.detached) {
                throw new RouteError("CRYPTO_UNAVAILABLE", "Route cryptographic primitives are unavailable.");
            }
            if (!global.DeviceRoot?.deviceMaterial) throw new RouteError("DEVICE_ROOT_UNAVAILABLE", "DeviceRoot is required for route key storage.");
        },
        _policy(type, allowedAccounts) {
            if (typeof type !== "string" || !type || type.length > 128) throw new RouteError("INVALID_TYPE", "Route type must be a non-empty local string.");
            if (!Array.isArray(allowedAccounts) || allowedAccounts.some((account) => typeof account !== "string" || !account || account.length > 512)) {
                throw new RouteError("INVALID_ALLOWED_ACCOUNTS", "allowedAccounts must be local non-empty account identifiers.");
            }
            return { type, allowedAccounts: [...new Set(allowedAccounts)].sort() };
        },
        // Canonical byte transcript: label + version + fixed public keys + u64
        // issue time. It has no JSON serialization or optional fields.
        certificateTranscript(certificate) {
            if (!certificate || certificate.version !== VERSION || !Number.isSafeInteger(certificate.issuedAt) || certificate.issuedAt < 0) {
                throw new RouteError("INVALID_CERTIFICATE", "Route certificate fields are invalid.");
            }
            const routeId = unb64url(certificate.routeId);
            const signing = unb64url(certificate.signingPublicKey);
            const box = unb64url(certificate.boxPublicKey);
            if (routeId.length !== 32 || signing.length !== 32 || box.length !== 32 || certificate.routeId !== certificate.signingPublicKey) {
                throw new RouteError("INVALID_CERTIFICATE", "RouteID must equal the 32-byte signing public key.");
            }
            return join(field(text(CERT_LABEL)), u32(VERSION), field(signing), field(box), u64(certificate.issuedAt));
        },
        verifyCertificate(certificate) {
            try {
                const signature = unb64url(certificate.signature);
                return signature.length === 64 && global.nacl.sign.detached.verify(this.certificateTranscript(certificate), signature, unb64url(certificate.signingPublicKey));
            } catch (_) { return false; }
        },
        // EntryGrantV1 has the same canonical binary transcript as the Python
        // Node verifier.  Ownership is proven by RouteSignPrivate: RouteID is
        // itself the Ed25519 verification key.  NodeID is only a signed binding.
        entryGrantTranscript(grant) {
            if (!grant || grant.v !== ENTRY_GRANT_VERSION) throw new RouteError("INVALID_ENTRY_GRANT", "EntryGrant version is invalid.");
            const routeId = unb64url(grant.route_id);
            const compatibilityKey = unb64url(grant.route_public_key);
            const nodeId = hexBytes(grant.node_id);
            if (routeId.length !== 32 || compatibilityKey.length !== 32) throw new RouteError("INVALID_ENTRY_GRANT", "EntryGrant route key is invalid.");
            if (!Number.isSafeInteger(grant.generation) || grant.generation < 1) throw new RouteError("INVALID_ENTRY_GRANT", "EntryGrant generation is invalid.");
            if (!Number.isSafeInteger(grant.created_at) || grant.created_at < 0 || !Number.isSafeInteger(grant.expires_at) || grant.expires_at <= grant.created_at) {
                throw new RouteError("INVALID_ENTRY_GRANT", "EntryGrant lifetime is invalid.");
            }
            return join(
                text(ENTRY_GRANT_LABEL),
                field(routeId),
                field(nodeId),
                field(compatibilityKey),
                u64(grant.generation),
                u64(grant.created_at),
                u64(grant.expires_at)
            );
        },
        verifyEntryGrant(grant, expectedNodeId = null, now = Math.floor(Date.now() / 1000)) {
            try {
                if (expectedNodeId !== null && grant.node_id !== expectedNodeId) return false;
                if (!Number.isSafeInteger(now) || grant.expires_at <= now) return false;
                const signature = unb64url(grant.signature);
                const routeKey = unb64url(grant.route_id);
                return signature.length === 64 && routeKey.length === 32 &&
                    global.nacl.sign.detached.verify(this.entryGrantTranscript(grant), signature, routeKey);
            } catch (_) { return false; }
        },
        _loadIndex() {
            const raw = this._store()?.getItem(INDEX_KEY);
            if (!raw) return { version: VERSION, current: null, previous: null };
            try {
                const index = JSON.parse(raw);
                if (index.version !== VERSION || !Object.hasOwn(index, "current") || !Object.hasOwn(index, "previous")) throw new Error();
                return index;
            } catch (_) { throw new RouteError("INDEX_CORRUPT", "Local route index is corrupt and was not replaced."); }
        },
        _saveIndex(index) { this._store().setItem(INDEX_KEY, JSON.stringify(index)); },
        _emitLifecycle(event, route) {
            if (typeof global.dispatchEvent !== "function" || typeof global.CustomEvent !== "function") return;
            global.dispatchEvent(new global.CustomEvent("dmash-device-route", {
                detail: { event, route: route ? this.publicRoute(route) : null }
            }));
        },
        _newMaterialName() {
            const bytes = global.crypto.getRandomValues(new Uint8Array(16));
            return MATERIAL_PREFIX + b64url(bytes);
        },
        async _generate(materialName, policy, issuedAt) {
            const encoded = await global.DeviceRoot.deviceMaterial(materialName, () => {
                const signing = global.nacl.sign.keyPair();
                const box = global.nacl.box.keyPair();
                return text(JSON.stringify({ version: VERSION, signingSecretKey: b64url(signing.secretKey), boxSecretKey: b64url(box.secretKey) }));
            });
            let privateMaterial;
            try { privateMaterial = JSON.parse(new TextDecoder().decode(encoded)); }
            finally { encoded.fill(0); }
            if (privateMaterial.version !== VERSION) throw new RouteError("MATERIAL_CORRUPT", "Route private material is unsupported.");
            const signingSecretKey = unb64url(privateMaterial.signingSecretKey);
            const boxSecretKey = unb64url(privateMaterial.boxSecretKey);
            let signing, box;
            try {
                if (!global.nacl.sign.keyPair.fromSecretKey || !global.nacl.box.keyPair.fromSecretKey) throw new Error();
                signing = global.nacl.sign.keyPair.fromSecretKey(signingSecretKey);
                box = global.nacl.box.keyPair.fromSecretKey(boxSecretKey);
            } catch (_) { throw new RouteError("MATERIAL_CORRUPT", "Route private material cannot be read."); }
            const signingPublicKey = b64url(signing.publicKey);
            const certificate = { version: VERSION, routeId: signingPublicKey, signingPublicKey, boxPublicKey: b64url(box.publicKey), issuedAt };
            certificate.signature = b64url(global.nacl.sign.detached(this.certificateTranscript(certificate), signingSecretKey));
            signingSecretKey.fill(0); boxSecretKey.fill(0);
            return { materialName, certificate, type: policy.type, allowedAccounts: policy.allowedAccounts };
        },
        async issue({ type, allowedAccounts = [], issuedAt = Date.now() } = {}) {
            this._requirePrimitives();
            const policy = this._policy(type, allowedAccounts);
            if (!Number.isSafeInteger(issuedAt) || issuedAt < 0) throw new RouteError("INVALID_ISSUED_AT", "Route issue time is invalid.");
            const index = this._loadIndex();
            const current = await this._generate(this._newMaterialName(), policy, issuedAt);
            // Activation is local device policy.  It is intentionally absent
            // from the certificate, just like account allow-lists.
            current.active = true;
            // Reissue fallback is strictly bounded: retain only the immediately
            // preceding route, replacing any older fallback in the public index.
            this._saveIndex({ version: VERSION, current, previous: index.current || null });
            this._emitLifecycle(index.current ? "ROUTE_REISSUED" : "ROUTE_ISSUED", current);
            return this.publicRoute(current);
        },
        // End-user alias: reissuing always creates fresh route key material.
        // Unless explicitly supplied, it retains the current route's local
        // policy; an account session is never consulted.
        async reissue({ type, allowedAccounts, issuedAt = Date.now() } = {}) {
            const current = this._loadIndex().current;
            if (!current && type === undefined) throw new RouteError("NO_CURRENT_ROUTE", "Create a public route before reissuing it.");
            return this.issue({
                type: type === undefined ? current.type : type,
                allowedAccounts: allowedAccounts === undefined ? current.allowedAccounts : allowedAccounts,
                issuedAt
            });
        },
        // Create a Node-bound authorization using the Route private signing key.
        // No Node private key participates in this operation.
        async issueEntryGrant(routeId, entryNodeId, {
            generation = 1,
            createdAt = Math.floor(Date.now() / 1000),
            expiresAt = createdAt + 24 * 60 * 60
        } = {}) {
            this._requirePrimitives();
            const index = this._loadIndex();
            const route = [index.current, index.previous].find((candidate) => candidate?.certificate?.routeId === routeId);
            if (!route) throw new RouteError("NOT_FOUND", "Route was not found for EntryGrant issuance.");
            hexBytes(entryNodeId);
            if (!Number.isSafeInteger(generation) || generation < 1 || !Number.isSafeInteger(createdAt) || createdAt < 0 || !Number.isSafeInteger(expiresAt) || expiresAt <= createdAt) {
                throw new RouteError("INVALID_ENTRY_GRANT", "EntryGrant lifetime or generation is invalid.");
            }

            const encoded = await global.DeviceRoot.deviceMaterial(route.materialName, () => {
                throw new RouteError("MATERIAL_MISSING", "Route private material is unavailable.");
            });
            let privateMaterial;
            try { privateMaterial = JSON.parse(new TextDecoder().decode(encoded)); }
            finally { encoded.fill(0); }
            if (privateMaterial.version !== VERSION) throw new RouteError("MATERIAL_CORRUPT", "Route private material is unsupported.");
            const signingSecretKey = unb64url(privateMaterial.signingSecretKey);
            try {
                if (!global.nacl.sign.keyPair.fromSecretKey) throw new RouteError("CRYPTO_UNAVAILABLE", "Route signing primitive is unavailable.");
                const signing = global.nacl.sign.keyPair.fromSecretKey(signingSecretKey);
                if (b64url(signing.publicKey) !== routeId) throw new RouteError("MATERIAL_CORRUPT", "Route private key does not match RouteID.");
                const grant = {
                    v: ENTRY_GRANT_VERSION,
                    node_id: entryNodeId,
                    route_id: routeId,
                    // Compatibility field is signed but not authoritative.
                    // New grants bind it to RouteSignPublic exactly.
                    route_public_key: routeId,
                    generation,
                    created_at: createdAt,
                    expires_at: expiresAt
                };
                grant.signature = b64url(global.nacl.sign.detached(this.entryGrantTranscript(grant), signingSecretKey));
                if (!this.verifyEntryGrant(grant, entryNodeId, createdAt)) throw new RouteError("ENTRY_GRANT_SELF_VERIFY_FAILED", "EntryGrant self-verification failed.");
                return Object.freeze({ ...grant });
            } finally {
                signingSecretKey.fill(0);
            }
        },
        publicRoute(route) {
            if (!route?.certificate || !this.verifyCertificate(route.certificate)) throw new RouteError("INVALID_CERTIFICATE", "Route certificate self-signature is invalid.");
            return Object.freeze({ routeId: route.certificate.routeId, certificate: Object.freeze({ ...route.certificate }) });
        },
        current() {
            const route = this._loadIndex().current;
            return route ? this.publicRoute(route) : null;
        },
        // Device-local management view.  `active` and `type` are local policy
        // data and must not be used as a shareable route descriptor.
        list() {
            const { current, previous } = this._loadIndex();
            return [current, previous].filter(Boolean).map((route, index) => Object.freeze({
                ...this.publicRoute(route),
                active: route.active !== false,
                current: index === 0,
                type: route.type
            }));
        },
        activePublicRoutes() {
            return this.list().filter(route => route.active);
        },
        activate(routeId, active = true) {
            if (typeof routeId !== "string" || !routeId) throw new RouteError("INVALID_ROUTE_ID", "Route ID is invalid.");
            if (typeof active !== "boolean") throw new RouteError("INVALID_ACTIVE_STATE", "Route activation state is invalid.");
            const index = this._loadIndex();
            let changed = null;
            for (const route of [index.current, index.previous]) {
                if (route?.certificate?.routeId === routeId) { route.active = active; changed = route; break; }
            }
            if (!changed) throw new RouteError("NOT_FOUND", "Public route was not found.");
            this._saveIndex(index);
            this._emitLifecycle(active ? "ROUTE_ACTIVATED" : "ROUTE_DEACTIVATED", changed);
            return Object.freeze({ ...this.publicRoute(changed), active, current: index.current === changed, type: changed.type });
        },
        // Resolution is local-only and considers current then exactly one prior
        // reissue. It returns policy but never a private key.
        resolve(routeId) {
            if (typeof routeId !== "string") return null;
            const { current, previous } = this._loadIndex();
            for (const route of [current, previous]) {
                if (route?.certificate?.routeId === routeId && this.verifyCertificate(route.certificate)) {
                    return Object.freeze({ ...this.publicRoute(route), type: route.type, allowedAccounts: Object.freeze([...route.allowedAccounts]) });
                }
            }
            return null;
        }
    };

    global.DeviceRoutes = Routes;
    global.RouteError = RouteError;
    if (typeof module !== "undefined") module.exports = { DeviceRoutes: Routes, RouteError };
})(typeof window !== "undefined" ? window : globalThis);
