'use strict';
(function(g){
 const PROFILE='STORE_FORWARD_V1',DOMAIN='D-MASH|NODE-STORE|V4|STORE_FORWARD_V1|';
 const schemas={GRANT:'version issuer recipient grant_id generation direction issued_at expires_at policy max_records max_bytes',BIND:'version issuer recipient grant_hash direction transcript_hash challenge expires_at',ROUTE_GRANT:'version issuer holder binding_id binding_generation route_authority_commitment store_grant_hash expires_at',ROUTE_REBIND:'version issuer holder route_grant_hash store_grant_hash transcript_hash challenge expires_at',MIGRATION:'version issuer recipient migration_id source_grant_hash target_grant_hash transcript_hash challenge expires_at'};
 const ints=new Set('version generation binding_generation issued_at expires_at max_records max_bytes'.split(' ')),hex=x=>typeof x==='string'&&/^[0-9a-f]{64}$/.test(x),bytes=x=>Uint8Array.from(x.match(/../g),v=>parseInt(v,16)),tohex=x=>Array.from(x,v=>v.toString(16).padStart(2,'0')).join('');
 const canonical=x=>g.DmashSecureSession.canonical(x),exact=(x,keys)=>x&&Object.getPrototypeOf(x)===Object.prototype&&Object.keys(x).sort().join(' ')===[...keys].sort().join(' ');
 function negotiate(p){if(!exact(p,['profiles','required_profiles']))throw Error('PROFILE_UPGRADE_REQUIRED');for(const v of Object.values(p))if(!Array.isArray(v)||v.length<1||v.length>8||v.some(x=>typeof x!=='string'||! /^[\x00-\x7f]{1,64}$/.test(x))||JSON.stringify([...new Set(v)].sort())!==JSON.stringify(v))throw Error('Invalid profile list');if(!p.profiles.includes(PROFILE)||!p.required_profiles.includes(PROFILE)||p.required_profiles.some(v=>v!==PROFILE))throw Error('PROFILE_UPGRADE_REQUIRED');return PROFILE;}
 function bodyBytes(kind,b){if(!Object.hasOwn(schemas,kind)||!exact(b,schemas[kind].split(' ')))throw Error('Invalid profile schema');for(const [k,v]of Object.entries(b)){if(ints.has(k)){if(!Number.isSafeInteger(v)||v<0||Object.is(v,-0))throw Error('Invalid integer');}else if(k==='policy'){if(v!=='store-forward-v4')throw Error('Invalid policy');}else if(!hex(v))throw Error('Invalid hex');}if(b.version!==1)throw Error('PROFILE_UPGRADE_REQUIRED');const peer=b.recipient??b.holder;if(b.issuer===peer)throw Error('Self grant');g.DmashRouteDiscoveryV4.validateEd25519PublicEncoding(b.issuer);g.DmashRouteDiscoveryV4.validateEd25519PublicEncoding(peer);if(kind==='GRANT'&&(!(b.max_records>=1&&b.max_records<=128&&b.max_bytes>=1&&b.max_bytes<=524288)||b.issued_at>=b.expires_at))throw Error('Invalid grant bounds');return new TextEncoder().encode(DOMAIN+kind+'\0'+canonical(b));}
 const signer=(k,b)=>['GRANT','ROUTE_GRANT'].includes(k)?b.issuer:(b.recipient??b.holder);
 function sign(kind,body,key){if(tohex(g.nacl.sign.keyPair.fromSecretKey(key).publicKey)!==signer(kind,body))throw Error('Signer mismatch');const signature=g.nacl.sign.detached(bodyBytes(kind,body),key);return {kind,body:{...body},signature:g.DmashSecureSession.b64(signature)};}
 function verify(e,{now,expected}){if(!exact(e,['kind','body','signature'])||canonical(e).length>4096)throw Error('Invalid envelope');const b=e.body,k=e.kind,raw=bodyBytes(k,b);if(!Number.isSafeInteger(now)||now<0||b.expires_at<=now||(b.issued_at??now)>now)throw Error('Expired');if(!expected||Object.getPrototypeOf(expected)!==Object.prototype||!Object.keys(expected).length||Object.entries(expected).some(([k,v])=>b[k]!==v))throw Error('Context mismatch');if(!['issuer',Object.hasOwn(b,'recipient')?'recipient':'holder'].every(k=>Object.hasOwn(expected,k)))throw Error('Expected authenticated peer identities required');if(['BIND','ROUTE_REBIND','MIGRATION'].includes(k)&&(!Object.keys(b).filter(k=>!['version','expires_at'].includes(k)).every(k=>Object.hasOwn(expected,k))||b.expires_at>now+90))throw Error('Fresh binding context required');const sig=g.DmashSecureSession.unb64(e.signature,64);g.DmashRouteDiscoveryV4.validateEd25519SignatureEncoding(tohex(sig));if(!g.nacl.sign.detached.verify(raw,sig,bytes(signer(k,b))))throw Error('Invalid signature');return Object.freeze({...b});}
 function parse(s,options){if(typeof s!=='string'||s.length>4096)throw Error('Invalid envelope size');const e=JSON.parse(s);if(canonical(e)!==s)throw Error('Noncanonical envelope');return verify(e,options);}
 const api=Object.freeze({PROFILE,negotiate,bodyBytes,sign,verify,parse});g.DmashNodeStoreProfileV4=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
