"use strict";

window.DMASH_LOCALES = window.DMASH_LOCALES || {};
window.DMASH_LOCALES.en = {
    nav: { primary: "Primary navigation", chats: "Chats", contacts: "Contacts", network: "Network", settings: "Settings" },
    common: { back: "Back", close: "Close", cancel: "Cancel", save: "Save", retry: "Retry", remove: "Remove", update: "Update", done: "Done", copy: "Copy", copied: "Copied" },
    release: { privateMessenger: "Private messenger", build: "Build {id}", updateReady: "Update ready", reload: "Reload now" },
    chats: { title: "Chats", messages: "Messages", selectConversation: "Choose a conversation", welcomeTitle: "Private conversations, simply", welcomeBody: "Add a contact to start an end-to-end encrypted conversation.", emptyTitle: "No conversations yet", emptyDescription: "Add a contact to start a private conversation.", newContact: "New contact", search: "Search chats", compose: "Write a message", send: "Send", attachment: "Add attachment", recordVoice: "Record voice message", recordVideo: "Record video", call: "Call" },
    contacts: { title: "Contacts", subtitle: "People you can reach securely.", emptyTitle: "No contacts", emptyBody: "Use a QR code or a verified ID to add someone.", add: "Add contact", scanQr: "Scan QR", showQr: "Show my QR", manualId: "Enter ID manually", search: "Search contacts", verified: "Verified", unverified: "Not verified" },
    network: { title: "Network", subtitle: "Choose how D-MASH reaches the network. Your messages stay encrypted.", currentNode: "Current node", knownNodes: "Known nodes", noNode: "No node selected", noNodeDescription: "Select a node from the list or add your own endpoint.", addNode: "Add node", refresh: "Refresh Origin list", connect: "Connect", disconnect: "Disconnect", primary: "Primary", select: "Select", remove: "Remove", nodeEndpoint: "Secure node endpoint", nodeName: "Node name", emptyTitle: "No known nodes", emptyBody: "Add a trusted node or refresh the list supplied by Origin.", selectHint: "Choose a node to connect.", unlockHint: "Unlock your identity before connecting to a node.", reconnectingHint: "Trying to reconnect securely.", errorHint: "Connection needs attention. Try again or choose another node.", readyHint: "Ready to connect.", latency: "{value} ms", connectionError: "Could not connect to this node.", status: { connected: "Connected", connecting: "Connecting", reconnecting: "Reconnecting", offline: "Offline", error: "Connection problem" } },
    settings: { title: "Settings", subtitle: "Your account, privacy and app preferences.", identity: "Identity", identityDescription: "Your public identity and verification tools.", displayName: "Display name", fingerprint: "Fingerprint", notAvailable: "Not available until unlocked", showQr: "Show my QR", preferences: "Preferences", preferencesDescription: "Language and appearance apply only on this device.", security: "Security", network: "Network", networkDescription: "Manage the secure node used by this device.", notifications: "Notifications", notificationsDescription: "Choose how D-MASH tells you about pending messages.", appearance: "Appearance", language: "Language", storage: "Storage", advanced: "Advanced", advancedDescription: "Technical details for support and troubleshooting.", diagnostics: "Diagnostics", about: "About", theme: { system: "Use system setting", dark: "Dark", light: "Light" } },
    notifications: { title: "Notifications", personalBot: "Personal Telegram bot", personalBotDescription: "Your token is sent only to the encrypted Origin vault and is never stored in this browser.", originUrl: "Origin notification address", botToken: "Bot token", token: "Bot token", notConfigured: "Not configured", waiting: "Waiting for Telegram", waitingForTelegram: "Open Telegram and press Start to finish linking.", openTelegram: "Open Telegram", connected: "Connected", disabled: "Disabled", test: "Send test notification", connect: "Connect bot", replace: "Replace bot", remove: "Remove bot" },
    security: { protected: "End-to-end encrypted", secure: "End-to-end encrypted", details: "Security details", fingerprint: "Fingerprint", notVerified: "Not verified" }
};
