"use strict";

window.DMASH_LOCALES = window.DMASH_LOCALES || {};
window.DMASH_LOCALES.ru = {
    nav: { primary: "Основная навигация", chats: "Чаты", contacts: "Контакты", network: "Сеть", settings: "Настройки" },
    common: { back: "Назад", close: "Закрыть", cancel: "Отмена", save: "Сохранить", retry: "Повторить", remove: "Удалить", update: "Обновить", done: "Готово", copy: "Копировать", copied: "Скопировано" },
    release: { privateMessenger: "Приватный мессенджер", build: "Сборка {id}", updateReady: "Обновление готово", reload: "Перезагрузить" },
    chats: { title: "Чаты", messages: "Сообщения", selectConversation: "Выберите диалог", welcomeTitle: "Приватное общение без лишнего", welcomeBody: "Добавьте контакт, чтобы начать диалог со сквозным шифрованием.", emptyTitle: "Пока нет диалогов", emptyDescription: "Добавьте контакт, чтобы начать приватный разговор.", newContact: "Новый контакт", search: "Поиск чатов", compose: "Напишите сообщение", send: "Отправить", attachment: "Добавить вложение", recordVoice: "Записать голосовое сообщение", recordVideo: "Записать видеосообщение", call: "Позвонить" },
    contacts: { title: "Контакты", subtitle: "Люди, с которыми можно общаться безопасно.", emptyTitle: "Нет контактов", emptyBody: "Добавьте человека по QR-коду или проверенному ID.", add: "Добавить контакт", scanQr: "Сканировать QR", showQr: "Показать мой QR", manualId: "Ввести ID вручную", search: "Поиск контактов", verified: "Проверен", unverified: "Не проверен" },
    network: { title: "Сеть", subtitle: "Выберите, через какой узел D-MASH выходит в сеть. Сообщения остаются зашифрованными.", currentNode: "Текущий узел", knownNodes: "Известные узлы", noNode: "Узел не выбран", noNodeDescription: "Выберите узел из списка или добавьте свой адрес.", addNode: "Добавить узел", refresh: "Обновить список Origin", connect: "Подключиться", disconnect: "Отключиться", primary: "Основной", select: "Выбрать", remove: "Удалить", nodeEndpoint: "Защищённый адрес узла", nodeName: "Название узла", emptyTitle: "Нет известных узлов", emptyBody: "Добавьте доверенный узел или обновите список от Origin.", selectHint: "Выберите узел для подключения.", unlockHint: "Сначала разблокируйте личность, чтобы подключиться к узлу.", reconnectingHint: "Безопасно пытаемся восстановить соединение.", errorHint: "Подключению требуется внимание. Повторите попытку или выберите другой узел.", readyHint: "Готово к подключению.", latency: "{value} мс", connectionError: "Не удалось подключиться к этому узлу.", status: { connected: "Подключено", connecting: "Подключаемся", reconnecting: "Переподключаемся", offline: "Нет соединения", error: "Ошибка соединения" } },
    settings: { title: "Настройки", subtitle: "Ваш аккаунт, конфиденциальность и параметры приложения.", identity: "Личность", identityDescription: "Публичная личность и инструменты проверки.", displayName: "Имя", fingerprint: "Отпечаток", notAvailable: "Станет доступно после разблокировки", showQr: "Показать мой QR", preferences: "Параметры", preferencesDescription: "Язык и оформление действуют только на этом устройстве.", security: "Безопасность", network: "Сеть", networkDescription: "Управляйте защищённым узлом этого устройства.", notifications: "Уведомления", notificationsDescription: "Выберите, как D-MASH сообщает об ожидающих сообщениях.", appearance: "Оформление", language: "Язык", storage: "Хранилище", advanced: "Дополнительно", advancedDescription: "Техническая информация для поддержки и диагностики.", diagnostics: "Диагностика", about: "О приложении", theme: { system: "Как в системе", dark: "Тёмное", light: "Светлое" } },
    notifications: { title: "Уведомления", personalBot: "Личный Telegram-бот", personalBotDescription: "Токен передаётся только в зашифрованное хранилище Origin и не сохраняется в этом браузере.", originUrl: "Адрес Origin для уведомлений", botToken: "Токен бота", token: "Токен бота", notConfigured: "Не настроен", waiting: "Ожидание Telegram", waitingForTelegram: "Откройте Telegram и нажмите «Старт», чтобы завершить привязку.", openTelegram: "Открыть Telegram", connected: "Подключено", disabled: "Отключено", test: "Отправить тестовое уведомление", connect: "Подключить бота", replace: "Заменить бота", remove: "Удалить бота" },
    security: { protected: "Сквозное шифрование", secure: "Сквозное шифрование", details: "Сведения о безопасности", fingerprint: "Отпечаток", notVerified: "Не проверен" }
};
