'use strict';
// NOT IMPLEMENTED N4 contract. Real NaCl, bundled Kyber WASM and bundled Argon2.
// In-memory storage/network fault injection only; never touches real Accounts.
const assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs');
const {createCore,nacl}=require('../D-MASH PWA/not_messenger/tests/fixtures/core_vm.cjs');
// Browser-style Module binding for this bundled Emscripten adapter in Node.
global.self={get Module(){return global.Module;},set Module(value){global.Module=value;}};
const argon=require('../D-MASH PWA/not_messenger/js/vendor/argon2-bundled.min.js');
const hex=b=>Buffer.from(b).toString('hex');
async function pair(){const [a,b]=await Promise.all([createCore({kyber:true}),createCore({kyber:true})]);for(const [local,peer]of [[a,b],[b,a]]){local.outgoing=[];local.ctx.argon2={hash:argon.hash,argon2id:argon.ArgonType.Argon2id};await local.storage.putBox('blind_peers',{alias:peer.core.keys.pub_hex,data:{id:peer.core.keys.pub_hex,curvePub:hex(peer.core.keys.box.publicKey),kyberPub:hex(peer.core.keys.kyber.publicKey)}});local.ctx.NodeManager={transportMode:'mesh',getMeshRoute:()=>({routeLocator:'synthetic-out',backRouteLocator:'synthetic-in'}),startProbe:async()=>({}),submitEnvelope:async(_,envelope)=>{local.outgoing.push(envelope);return{state:'NODE_ACCEPTED'};}};}return[a,b];}
async function deliver(to,from,ciphertext){const raw=Buffer.from(ciphertext,'hex'),proof=nacl.sign.detached(raw,from.core.keys.sign.secretKey);assert(nacl.sign.detached.verify(raw,proof,from.core.keys.sign.publicKey));return to.core.decrypt(ciphertext,from.core.keys.pub_hex,true);}
const state=(a,b)=>a.storage.getBox('blind_secrets',b.core.keys.pub_hex);
async function establish(a,b){await deliver(b,a,await a.core.encrypt('init',b.core.keys.pub_hex,true));const firstFinal=b.outgoing.shift().ciphertext;const processed=await deliver(a,b,firstFinal);assert(processed.confirmation);const confirmation=await a.core.encrypt(JSON.stringify({type:'dmash_message',id:crypto.randomUUID(),body:processed.confirmation}),b.core.keys.pub_hex);await deliver(b,a,confirmation);assert.equal((await state(b,a)).pendingKyberFinal,undefined,'precondition: responder fully confirmed, old final retired');assert.equal((await state(a,b)).staticShared,(await state(b,a)).staticShared);a.outgoing.length=0;b.outgoing.length=0;}
(async()=>{const report={kind:'UNIT N4 proposed contract; expected RED; no runtime activation',node:process.version,crypto:'Real NaCl + bundled Kyber WASM + bundled Argon2',coreSha256:crypto.createHash('sha256').update(fs.readFileSync(require.resolve('../D-MASH PWA/not_messenger/js/core_engine.js'))).digest('hex'),cases:[]};const run=async(id,fn)=>{try{await fn();report.cases.push({id,status:'PASS'});}catch(e){report.cases.push({id,status:'FAIL',reason:e.message.split('\n')[0]});}};
 await run('H2-ESTABLISHED-ONE-SIDED-LOSS',async()=>{const[a,b]=await pair();await establish(a,b);const old=(await state(b,a)).staticShared;a.rows.delete('blind_secrets'+b.core.keys.pub_hex);await deliver(b,a,await a.core.encrypt('recovery',b.core.keys.pub_hex,true));assert.equal((await state(b,a)).staticShared,old,'must not blindly replace established root');assert(b.outgoing.length>0,'Fully confirmed responder swallowed fresh authenticated init without a fresh recovery challenge/response');});
 await run('H2-PENDING-OLD-FINAL-NO-RECOVERY',async()=>{const[a,b]=await pair();await deliver(b,a,await a.core.encrypt('init',b.core.keys.pub_hex,true));await deliver(a,b,b.outgoing.shift().ciphertext);a.rows.delete('blind_secrets'+b.core.keys.pub_hex);await deliver(b,a,await a.core.encrypt('recovery',b.core.keys.pub_hex,true));assert(b.outgoing.length>0,'baseline H2 expects only a response');await deliver(a,b,b.outgoing.shift().ciphertext);assert((await state(a,b)).staticShared,'Returned old final cannot complete the new recovery attempt; response alone is not recovery');});
 await run('FINAL-EXACT-DURABLE-RETRY',async()=>{const[a,b]=await pair(),init=await a.core.encrypt('init',b.core.keys.pub_hex,true);await deliver(b,a,init);const first=b.outgoing.shift().ciphertext;await deliver(b,a,init);const retry=b.outgoing.shift().ciphertext;assert.equal(first.slice(2,2178),retry.slice(2,2178),'Kyber capsule remains stable');assert.equal(first,retry,'Final retransmission rebuilds ciphertext instead of replaying exact durable frame');});
 console.log(JSON.stringify(report,null,2));process.exitCode=report.cases.some(x=>x.status==='FAIL')?1:0;
})().catch(e=>{console.error(e.message);process.exitCode=1;});
