'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict');
const {chromium}=require(process.env.DMASH_PLAYWRIGHT_MODULE||'/tmp/dmash-browser-tools/node_modules/playwright');
(async()=>{const out=process.env.DMASH_QA_OUTPUT||'docs/evidence/2026-10-08/qa-account-media-lifecycle.json',report={time:new Date().toISOString(),steps:[],inventory:[],limits:['Fresh synthetic Accounts only','Physical WebAuthn NOT RUN','No Account credentials or root keys recorded']};const browser=await chromium.launch({headless:true,executablePath:process.env.DMASH_CHROME});const overlay=process.env.DMASH_TEST_PWA_ROOT;const context=await browser.newContext(overlay?{serviceWorkers:'block'}:{});if(overlay){const path=require('node:path'),crypto=require('node:crypto');report.source={kind:'uncommitted browser overlay',baseSHA:require('node:child_process').execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),files:{}};for(const name of ['core_engine.js','storage.js']){const file=path.resolve(overlay,'js',name);report.source.files[name]=crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');await context.route('**/js/'+name+'*',route=>route.fulfill({path:file,contentType:'application/javascript'}));}}const page=await context.newPage();page.setDefaultTimeout(15000);const click=s=>page.getByRole('button',{name:s,exact:true}).click();const save=()=>fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');const clean=s=>s.replace(/[a-f0-9]{16,}/gi,'[id]');const inventory=async state=>{report.inventory.push({state,text:clean(await page.locator('body').innerText()).slice(-5000),controls:await page.locator('button').evaluateAll(es=>es.filter(e=>e.getClientRects().length).map(e=>({id:e.id,label:e.textContent.trim(),onclick:e.getAttribute('onclick')})))});};const step=async(id,fn)=>{try{await fn();report.steps.push({id,status:'PASS'});}catch(e){report.steps.push({id,status:'FAIL',error:e.message.split('\n')[0]});await inventory('FAIL '+id);throw e;}finally{save();}};const digits=async s=>{for(const d of s)await click(d);await click('=');};const names=['qa-switch-a-'+Date.now(),'qa-switch-b-'+Date.now()],password='Synthetic-only-2026!';const enter=async(name,pwd=password)=>{await page.locator('#p1').fill(name);await page.locator('#p2').fill(pwd);await click('ВОЙТИ');};const saved=()=>page.locator('#contact-list').getByText('Избранное',{exact:true});const logout=()=>click('[ ВЫХОД ]');
try{
 await page.goto('https://messenger.d-mash.ru/not_messenger/');if(!overlay){await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>navigator.serviceWorker.controller);}report.page=await page.evaluate(()=>DMASH_RELEASE.id);report.sw=overlay?'BLOCKED: uncommitted source overlay':await context.serviceWorkers()[0].evaluate(()=>RELEASE_ID);report.browser=browser.version();await page.getByText('УСТАНОВКА MASTER-КОДА',{exact:true}).waitFor();await digits('3333');await page.getByText('УСТАНОВКА WIPE-КОДА',{exact:true}).waitFor();await digits('9876');await page.getByText('СИСТЕМА ГОТОВА',{exact:true}).waitFor();await page.waitForTimeout(1300);await digits('3333');await page.locator('#p1').waitFor();
 await step('UI02-empty-error',async()=>{await click('ВОЙТИ');await page.getByText('ОШИБКА ВХОДА: Проверьте идентификатор и ключ доступа.',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'ВОЙТИ',exact:true}).isEnabled(),true);});
 for(let i=0;i<2;i++)await step('UI02-create-'+i,async()=>{if(i){await logout();await click('+ НОВЫЙ ВХОД');}await page.locator('#save-in-registry').check();await enter(names[i]);await saved().waitFor({timeout:60000});await saved().click();await page.locator('#msgInput').fill('Synthetic private history '+i);await click('SEND');await page.locator('#log .m-txt').filter({hasText:'Synthetic private history '+i}).waitFor();});
 await step('UI02-switch-isolation',async()=>{await logout();await click(names[0]);await page.locator('#p2').fill(password);await click('ВОЙТИ');await saved().click({timeout:60000});await page.locator('#log .m-txt').filter({hasText:'Synthetic private history 0'}).waitFor();assert.equal(await page.locator('#log .m-txt').filter({hasText:'Synthetic private history 1'}).count(),0);});
 try {await step('UI02-wrong-nonempty',async()=>{await logout();await click(names[0]);await page.locator('#p2').fill('Wrong-Synthetic-key');await click('ВОЙТИ');await page.waitForFunction(()=>document.getElementById('gate-status-text')?.textContent.includes('ОШИБКА')||document.getElementById('contact-list')?.getClientRects().length,null,{timeout:60000});await inventory('wrong Account key');assert(await page.locator('#p2').isVisible(),'Saved Account wrong key silently entered workspace');});}catch(_){if(await saved().isVisible()){await logout();await click(names[0]);}}
 await step('UI02-wrong-retry-correct',async()=>{await page.locator('#p2').fill(password);await click('ВОЙТИ');await saved().click({timeout:60000});await page.locator('#log .m-txt').filter({hasText:'Synthetic private history 0'}).waitFor();});
 if(process.env.DMASH_QA_SKIP_DELETE!=='1'){
 await step('UI02-registry-open',async()=>{await logout();await page.locator('#global-settings-button').click();await page.locator('button[onclick="Core.openAccountManager()"]').click();await inventory('Account registry');});
 const remove=()=>page.locator(`button[onclick*="removeAccountFlow"][onclick*="${names[1]}"]`);
 await step('UI02-remove-cancel',async()=>{await remove().click();await click('ОТМЕНА');await page.locator('#global-settings-button').count();});
 // Cancel closes the modal; global settings behind it remains available.
 await step('UI02-remove-confirm',async()=>{await page.locator('button[onclick="Core.openAccountManager()"]').click();await remove().click();await page.locator('#p-in').fill('УДАЛИТЬ');await page.locator('#p-ok').click();await page.waitForTimeout(1000);await inventory('Account removal result');assert.equal(await page.locator('button[onclick*="removeAccountFlow"]').count(),1);await click('НАЗАД');await click('НАЗАД К АККАУНТАМ');assert.equal(await page.getByRole('button',{name:names[1],exact:true}).count(),0);});
 await step('UI02-removal-history-erased',async()=>{await click('+ НОВЫЙ ВХОД');await enter(names[1]);await saved().click({timeout:60000});await page.locator('#msgInput').waitFor({state:'visible'});assert.equal(await page.locator('#log .m-txt').filter({hasText:'Synthetic private history 1'}).count(),0);});
 }else report.limits.push('Account deletion tracked separately as ACCOUNT-DELETE-01; not exercised in this run');
}catch(e){report.fatal=e.message.split('\n')[0];}finally{save();await browser.close();}process.exitCode=report.fatal||report.steps.some(s=>s.status==='FAIL')?1:0;console.log(JSON.stringify({steps:report.steps,fatal:report.fatal}));})();
