'use strict';
// Fresh-profile real UI contacts audit. No Core/storage/network mutation from console.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process'),{chromium}=require(process.env.DMASH_PLAYWRIGHT_MODULE||'playwright');
const overlay=process.env.DMASH_TEST_PWA_ROOT?path.resolve(process.env.DMASH_TEST_PWA_ROOT):null;
const out=process.env.DMASH_QA_OUTPUT||'docs/evidence/2026-10-08/qa-contacts-public-fresh.json',report={target:'https://messenger.d-mash.ru/not_messenger/',scope:'FRESH PUBLIC-ONLY actual two-profile UI; no preexisting peers, private fallback or console setup; v3 migration path, not N3 cutover',mode:overlay?'IMMUTABLE LOCAL SOURCE / SW BLOCKED / REAL TRANSPORT':'DEPLOYED / REAL SW / REAL TRANSPORT',snapshot:overlay,steps:[],states:[],transportObservations:[],errors:[],console:[],loadedSources:[]};
const clean=s=>String(s).replace(/[a-f0-9]{24,}/gi,'[id]').replace(/[A-Za-z0-9_-]{40,}/g,v=>v.startsWith('transport-v3-')?v:'[token]');
const save=()=>fs.writeFileSync(out,JSON.stringify(report,(k,v)=>typeof v==='string'&&!['actualSha256','expectedSha256','expectedSource'].includes(k)?clean(v):v,2)+'\n');
(async()=>{let browser;const pages=[],sourceTasks=[],observers=[];const cdpPort=Number(process.env.DMASH_QA_CDP_PORT||0);if(cdpPort&&(!Number.isInteger(cdpPort)||cdpPort<1024||cdpPort>65535))throw Error('Invalid diagnostic CDP port');try{
 browser=await chromium.launch({headless:true,executablePath:process.env.DMASH_CHROME,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream','--autoplay-policy=no-user-gesture-required',...(cdpPort?['--remote-debugging-port='+cdpPort,'--remote-debugging-address=127.0.0.1']:[])]});report.browser=browser.version();
 const click=(p,s)=>p.getByRole('button',{name:s,exact:true}).click();
 const prompt=async(p,s)=>{await p.locator('#p-in').fill(s);await p.locator('#p-ok').click();};
 const snap=async(p,state)=>{report.states.push({state,text:clean(await p.locator('body').innerText()).slice(-6000),controls:await p.locator('button,input,textarea').evaluateAll(es=>es.filter(e=>e.getClientRects().length).map(e=>({id:e.id,label:(e.textContent||e.placeholder||'').trim().slice(0,100),disabled:!!e.disabled})))});save();};
 const step=async(id,p,fn)=>{try{await fn();report.steps.push({id,status:'PASS'});console.log('PASS',id);}catch(e){report.steps.push({id,status:'FAIL',error:clean(e.message).slice(0,500)});await snap(p,'FAIL '+id);throw e;}save();};
 const accounts=[];
 for(let i=0;i<2;i++){
  const ctx=await browser.newContext({serviceWorkers:overlay?'block':'allow',permissions:['clipboard-read','clipboard-write','microphone','camera']});if(overlay)await ctx.route('**/not_messenger/**',async route=>{const rel=decodeURIComponent(new URL(route.request().url()).pathname.split('/not_messenger/')[1]||'index.html'),file=path.resolve(overlay,rel);if(!file.startsWith(overlay+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile())return route.continue();await route.fulfill({body:fs.readFileSync(file),contentType:{'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.wasm':'application/wasm'}[path.extname(file)]||'application/octet-stream'});});const p=await ctx.newPage();pages.push(p);p.setDefaultTimeout(15000);p.on('pageerror',e=>report.errors.push({profile:i,error:clean(e.message)}));p.on('console',m=>{if(['warning','error'].includes(m.type()))report.console.push({profile:i,type:m.type(),text:clean(m.text()).slice(0,500)});});p.on('response',response=>{const u=new URL(response.url());if(u.origin!==new URL(report.target).origin||!u.pathname.startsWith('/not_messenger/'))return;const rel=decodeURIComponent(u.pathname.slice('/not_messenger/'.length))||'index.html';if(!(rel==='index.html'||rel==='nodes.json'||rel.endsWith('.js')))return;sourceTasks.push((async()=>{try{const actual=await response.body(),sha=process.env.DMASH_EXPECT_SHA;if(sha&&!/^[0-9a-f]{40}$/.test(sha))throw Error('Expected full commit SHA');const expected=sha?execFileSync('git',['show',sha+':D-MASH PWA/not_messenger/'+rel]):fs.readFileSync(path.join(overlay||'D-MASH PWA/not_messenger',rel));const hash=x=>crypto.createHash('sha256').update(x).digest('hex');report.loadedSources.push({profile:i,path:rel,actualSha256:hash(actual),expectedSha256:hash(expected),match:hash(actual)===hash(expected),fromServiceWorker:response.fromServiceWorker()});}catch(error){report.loadedSources.push({profile:i,path:rel,error:error.message.split('\n')[0]});}})());});if(process.env.DMASH_QA_READINESS==='1'){report.readinessStages||=[];report.instrumentation='CDP observational logpoints; may affect timing';observers.push(await require('./qa_public_readiness.cjs').attach({page:p,context:ctx,sourceRoot:overlay||path.resolve('D-MASH PWA/not_messenger'),profile:i,emit:row=>{report.readinessStages.push(row);save();}}));}await p.goto(report.target);await p.waitForFunction(()=>window.DMASH_RELEASE);if(!overlay){await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);}report['page'+i]=await p.evaluate(()=>DMASH_RELEASE.id);report['sw'+i]=overlay?'BLOCKED':await ctx.serviceWorkers()[0].evaluate(()=>RELEASE_ID);if((!overlay&&report['page'+i]!==report['sw'+i])||(process.env.DMASH_EXPECT_RELEASE&&report['page'+i]!==process.env.DMASH_EXPECT_RELEASE))throw Error('Page/SW release mismatch');
  const digits=async s=>{for(const d of s)await click(p,d);await click(p,'=');};
  await step('profile-'+i,p,async()=>{await p.getByText('УСТАНОВКА MASTER-КОДА',{exact:true}).waitFor();await digits('3333');await p.getByText('УСТАНОВКА WIPE-КОДА',{exact:true}).waitFor();await digits('9876');await p.getByText('СИСТЕМА ГОТОВА',{exact:true}).waitFor();await p.waitForTimeout(1300);await digits('3333');accounts[i]='qa-contacts-'+i+'-'+Date.now();await p.locator('#p1').fill(accounts[i]);await p.locator('#p2').fill('Synthetic-only-2026!');await p.locator('#save-in-registry').check();await click(p,'ВОЙТИ');await p.getByText('Избранное',{exact:true}).waitFor({timeout:90000});});
  await step('request-node-'+i,p,async()=>{await click(p,'Настройки');await click(p,'УЗЛЫ И ПОДКЛЮЧЕНИЕ');await click(p,'ЗАПРОСИТЬ УЗЕЛ');await p.getByRole('button',{name:'OFF',exact:true}).waitFor({timeout:90000});await snap(p,'connected-node-'+i);await click(p,'НАЗАД');await click(p,'ЗАКРЫТЬ');});
 }
 const [a,b]=pages;let link;
 await step('public-route-copy',b,async()=>{await click(b,'Настройки');await click(b,'PUBLIC / PRIVATE QR');await click(b,'PUBLIC');await click(b,'СОЗДАТЬ PUBLIC ROUTE');await b.getByRole('button',{name:'СОЗДАТЬ PUBLIC ROUTE',exact:true}).waitFor({state:'visible'});await snap(b,'visible-account-public-route-panel');await click(b,'СОЗДАТЬ PUBLIC ROUTE');await b.getByRole('button',{name:'CONTACT LINK',exact:true}).waitFor({timeout:90000});await click(b,'CONTACT LINK');link=await b.evaluate(()=>navigator.clipboard.readText());if(!link.includes('d-mash'))throw Error('Contact link copy failed');await click(b,'OK');});
 await step('public-request',a,async()=>{await click(a,'[ + ]');await prompt(a,link);await click(a,'ВВЕСТИ ДРУГОЕ ИМЯ');await prompt(a,'QA Alice');await prompt(a,'Synthetic browser contact audit');await a.getByRole('button',{name:'OK',exact:true}).waitFor({timeout:90000});await snap(a,'request-result');await click(a,'OK');await a.locator('.contact-progress-item').waitFor();});
 await step('public-accept-account',b,async()=>{
  if(await b.getByRole('button',{name:'OK',exact:true}).isVisible())await click(b,'OK');
  const openPending=async()=>{if(!await b.getByRole('button',{name:'ЗАПРОСЫ В КОНТАКТЫ',exact:true}).isVisible())await click(b,'Настройки');await click(b,'ЗАПРОСЫ В КОНТАКТЫ');};await openPending();
  let lastObservation=0;const deadline=Date.now()+180000;while(!await b.getByRole('button',{name:/QA Alice/}).count()){
   if(Date.now()>deadline)throw Error('Public request never became visible');
   if(Date.now()-lastObservation>10000){lastObservation=Date.now();for(const [profile,page]of pages.entries())report.transportObservations.push({profile,at:new Date().toISOString(),workers:page.workers().length,nodes:await page.evaluate(()=>[...NodeManager.connections.values()].map(c=>({state:c.state,dnss:c.dnssReadyState,difficulty:c.client?.resourcePowDifficulty,pending:c.client?.pending?.size,error:c.dnssError?.message||null})))});save();}
   if(await b.getByRole('button',{name:'OK',exact:true}).isVisible())await click(b,'OK');
   if(await b.locator('[data-dmash-pending-close]').isVisible())await b.locator('[data-dmash-pending-close]').click();
   await openPending();await b.waitForTimeout(1000);
  }
  await b.getByRole('button',{name:/QA Alice/}).click();await snap(b,'incoming-request');await click(b,'ПРИНЯТЬ');await prompt(b,'QA Bob');await b.locator('button[onclick*="Core.acceptPendingContactRequest"]').click();await b.getByRole('button',{name:'OK',exact:true}).waitFor({timeout:90000});await snap(b,'accepted');if((await b.locator('body').innerText()).includes('Откройте выбранный Account'))throw Error('Active Account acceptance rejected');await click(b,'OK');
 });
 await step('public-confirm',a,async()=>{await Promise.all(pages.map(p=>p.locator('.contact-progress-item').waitFor({state:'hidden',timeout:180000})));await snap(a,'confirmed');});
 for(const [i,p]of pages.entries())await step('chat-open-'+i,p,async()=>{await p.locator('#contact-list .peer-item').filter({hasNotText:'Избранное'}).first().waitFor({timeout:180000});await p.locator('#contact-list .peer-item').filter({hasNotText:'Избранное'}).first().click();});
 await step('key-exchange',a,async()=>{await click(a,'ОБМЕНЯТЬСЯ КЛЮЧАМИ');await a.locator('#msgInput').waitFor({state:'visible',timeout:180000});});
 for(const [i,p]of pages.entries())await step('send-receive-'+i,p,async()=>{const msg='UI contact message '+i;await p.locator('#msgInput').fill(msg);await click(p,'SEND');await pages[1-i].locator('#log .m-txt').filter({hasText:msg}).waitFor({timeout:180000});});
await Promise.all(sourceTasks);report.expectedSource=process.env.DMASH_EXPECT_SHA||(overlay?'LOCAL SNAPSHOT (not exact commit)':'WORKTREE');if(report.loadedSources.some(row=>row.error||!row.match))throw Error('Loaded source bytes differ from expected revision');for(let i=0;i<2;i++)for(const required of ['index.html','js/core_engine.js','js/acceptance_v50.js','nodes.json'])if(!report.loadedSources.some(row=>row.profile===i&&row.path===required&&row.match))throw Error('Missing loaded-source evidence '+required);
if(report.errors.length)throw Error('Unhandled browser errors');
if(process.env.DMASH_QA_SENDER_VOICE==='1')await require('./qa_sender_voice.cjs')({pages,report,step,click,snap});
if(process.env.DMASH_QA_MEDIA==='1')await require('./qa_remote_media.cjs')({pages,report,step,click,snap});
}catch(e){report.fatal=clean(e.message).slice(0,600);console.log('FAIL',report.fatal);process.exitCode=1;}finally{await Promise.allSettled(sourceTasks);for(const p of pages){try{report.states.push({state:'final',text:clean(await p.locator('body').innerText()).slice(-3000)});}catch(_){}}save();if(process.env.DMASH_QA_KEEP_ALIVE==='1'&&browser){report.retained={at:new Date().toISOString(),cdp:cdpPort?'http://127.0.0.1:'+cdpPort:null,note:'Original acceptance result preserved; same synthetic profiles alive for diagnosis. SIGUSR2 releases handle.'};save();console.log('RETAINED browser for same-profile diagnosis',report.retained.cdp||'(no external CDP port)');await new Promise(resolve=>process.once('SIGUSR2',resolve));}for(const observer of observers)await observer.close().catch(()=>{});await browser?.close();}})();
