'use strict';
// Supplemental browser fault-injection fixture: real UI Accounts/actions and real signed/encrypted flow state.
// Synthetic incoming metadata and transport send failures are injected; no remote delivery claim.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {chromium}=require(process.env.DMASH_PLAYWRIGHT_MODULE||'/tmp/dmash-browser-tools/node_modules/playwright');
(async()=>{
 const root=path.resolve(process.env.DMASH_TEST_PWA_ROOT||'D-MASH PWA/not_messenger'),out=process.env.DMASH_QA_OUTPUT||'docs/evidence/2026-10-08/qa-contact-owner.json';
 const report={mode:'BROWSER supplemental fault injection; full local source overlay; SW BLOCKED',limits:['Fresh synthetic A/B only; actual UI login/logout/menu/accept/retry','Incoming request metadata injected; real NaCl signatures and DeviceRoot encrypted storage','Send failure and captured successful queue injected; real remote delivery NOT RUN','Expiry uses genuinely signed short lifetime; no signed state rewrite'],steps:[],sources:{},errors:[]};
 const browser=await chromium.launch({headless:true,executablePath:process.env.DMASH_CHROME||'/home/jcode/.cache/ms-playwright/chromium-1248/chrome-linux64/chrome'});report.browser=browser.version();const ctx=await browser.newContext({serviceWorkers:'block'});
 await ctx.route('**/not_messenger/**',async route=>{const rel=decodeURIComponent(new URL(route.request().url()).pathname.split('/not_messenger/')[1]||'index.html'),file=path.resolve(root,rel);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile())return route.continue();const body=fs.readFileSync(file);report.sources[rel]=crypto.createHash('sha256').update(body).digest('hex');await route.fulfill({body,contentType:{'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.wasm':'application/wasm'}[path.extname(file)]||'application/octet-stream'});});
 const p=await ctx.newPage();p.setDefaultTimeout(20000);p.on('pageerror',e=>report.errors.push(e.message));const click=s=>p.getByRole('button',{name:s,exact:true}).click(),save=()=>fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');
 const step=async(id,fn)=>{try{await fn();report.steps.push({id,status:'PASS'});console.log('PASS',id);}catch(e){report.steps.push({id,status:'FAIL',error:e.message.split('\n')[0]});report.visibleFailure=(await p.locator('body').innerText()).replace(/[a-f0-9]{32,}/gi,'[id]').slice(-5000);throw e;}finally{save();}};
 const names=['owner-a-'+Date.now(),'owner-b-'+Date.now()],password='Synthetic-owner-test-2026!';const digits=async s=>{for(const d of s)await click(d);await click('=');};const enter=async(name,fresh=false)=>{if(fresh){await p.locator('#p1').fill(name);await p.locator('#save-in-registry').check();}else await click(name);await p.locator('#p2').fill(password);await click('ВОЙТИ');await p.locator('#contact-list').getByText('Избранное',{exact:true}).waitFor({timeout:90000});};
 const pending=async label=>{await click('Настройки');await click('ЗАПРОСЫ В КОНТАКТЫ');await p.getByRole('button',{name:label,exact:true}).click();};
 try{
 await p.goto('https://messenger.d-mash.ru/not_messenger/');report.page=await p.evaluate(()=>DMASH_RELEASE.id);report.sw='BLOCKED';await p.getByText('УСТАНОВКА MASTER-КОДА',{exact:true}).waitFor();await digits('3333');await p.getByText('УСТАНОВКА WIPE-КОДА',{exact:true}).waitFor();await digits('9876');await p.getByText('СИСТЕМА ГОТОВА',{exact:true}).waitFor();await p.waitForTimeout(1300);await digits('3333');
 await step('actual-ui-create-A-and-history',async()=>{await enter(names[0],true);await p.getByText('Избранное',{exact:true}).click();await p.locator('#msgInput').fill('Owner fixture retained history');await click('SEND');await p.locator('#log .m-txt').filter({hasText:'Owner fixture retained history'}).waitFor();});
 await p.evaluate(async()=>{
  const route=await DeviceRoutes.issue({type:'public'}),b64=x=>DmashSecureSession.b64(x).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
  const signing=nacl.sign.keyPair(),box=nacl.box.keyPair(),certificate={version:1,routeId:b64(signing.publicKey),signingPublicKey:b64(signing.publicKey),boxPublicKey:b64(box.publicKey),issuedAt:Date.now()};certificate.signature=b64(nacl.sign.detached(DeviceRoutes.certificateTranscript(certificate),signing.secretKey));
  const flow=Core.getContactFlowV3(),originalMake=flow.makeBootstrap;window.ownerFixture={flow,route,certificate,send:false,sent:[],originals:{},requests:{},short:false};
  flow.send=async(cert,wire)=>{if(!ownerFixture.send)throw Error('Synthetic transport failure after durable signing');ownerFixture.sent.push(JSON.stringify(wire));return true;};
  flow.makeBootstrap=async options=>{const signed=await originalMake(options);if(!ownerFixture.short)return signed;return DeviceRoutes.withRouteKeys(options.localCertificate.routeId,({signing})=>ContactBootstrapV3.create({...signed.body,expires_at:Math.floor(Date.now()/1000)+2},Core.keys.sign,signing));};
  ownerFixture.add=async(label,caller=false)=>{const request={type:'CONTACT_REQUEST_V1',version:1,request_id:b64(nacl.randomBytes(32)),reply_route_certificate:certificate,sender_display_name:label,intro_message:'',bootstrap_encryption_public:certificate.boxPublicKey,protocol_capabilities:['CONTACT_BOOTSTRAP_V3','DMP_C_V3']};const row=await Core.getPendingContactRequestStore().addContactRequest({requestId:request.request_id,displayName:label,replyRoute:certificate.routeId,receivedRoute:route.routeId,bootstrap:{contactRequest:request}});ownerFixture.requests[label]=request;if(caller){await flow.recordOutgoing(request,route.certificate,Core.activeIdentity);}return row.id;};
  await ownerFixture.add('Synthetic retry');
 });
 await step('actual-ui-A-sign-then-send-fails',async()=>{await pending('Synthetic retry');await click('ПРИНЯТЬ');await p.locator('#p-in').fill('Original signed name');await p.locator('#p-ok').click();await p.getByRole('button',{name:new RegExp(names[0])}).click();await p.getByText('Synthetic transport failure after durable signing',{exact:true}).waitFor();await click('OK');await p.evaluate(async()=>{const q=ownerFixture.requests['Synthetic retry'];ownerFixture.originals.retry=JSON.stringify((await ownerFixture.flow.read(q.request_id)).accept);});});
 await step('actual-ui-create-B-and-owner-guidance',async()=>{await click('[ ВЫХОД ]');await click('+ НОВЫЙ ВХОД');await enter(names[1],true);await pending('Synthetic retry');await p.getByText(new RegExp('Принятие уже сохранено для аккаунта')).waitFor();assert.equal(await p.getByRole('button',{name:'ПРИНЯТЬ',exact:true}).count(),0);assert(await p.getByRole('button',{name:'ВЫЙТИ И ВЫБРАТЬ АККАУНТ',exact:true}).isVisible());assert(await p.evaluate(async()=>JSON.stringify((await ownerFixture.flow.read(ownerFixture.requests['Synthetic retry'].request_id)).accept)===ownerFixture.originals.retry));});
 await step('actual-ui-owner-switch-and-exact-retry',async()=>{await click('ВЫЙТИ И ВЫБРАТЬ АККАУНТ');await enter(names[0]);await p.evaluate(()=>ownerFixture.send=true);await pending('Synthetic retry');await click('ПОВТОРИТЬ ПРИНЯТИЕ');await p.getByText('ПРИНЯТИЕ ОТПРАВЛЕНО',{exact:true}).waitFor();assert(await p.evaluate(()=>ownerFixture.sent.at(-1)===ownerFixture.originals.retry));await click('OK');});
 await step('actual-ui-expired-signed-accept-refused',async()=>{await p.evaluate(async()=>{ownerFixture.send=false;ownerFixture.short=true;await ownerFixture.add('Synthetic expired');});await pending('Synthetic expired');await click('ПРИНЯТЬ');await p.locator('#p-in').fill('Expiring signed name');await p.locator('#p-ok').click();await p.getByRole('button',{name:new RegExp(names[0])}).click();await p.getByText('Synthetic transport failure after durable signing',{exact:true}).waitFor();await click('OK');await p.evaluate(async()=>{ownerFixture.originals.expired=JSON.stringify((await ownerFixture.flow.read(ownerFixture.requests['Synthetic expired'].request_id)).accept);});await p.waitForTimeout(2200);await pending('Synthetic expired');await p.getByText(/Срок подписанного принятия истёк/).waitFor();assert.equal(await p.getByRole('button',{name:'ПОВТОРИТЬ ПРИНЯТИЕ',exact:true}).count(),0);assert.equal(await p.getByRole('button',{name:'ПРИНЯТЬ',exact:true}).count(),0);assert(await p.evaluate(async()=>JSON.stringify((await ownerFixture.flow.read(ownerFixture.requests['Synthetic expired'].request_id)).accept)===ownerFixture.originals.expired));await click('ЗАКРЫТЬ');await click('НАЗАД');await click('ЗАКРЫТЬ');});
 await step('actual-ui-caller-self-not-accepted',async()=>{await p.evaluate(()=>ownerFixture.add('Synthetic outgoing',true));await pending('Synthetic outgoing');await p.getByText(/уже есть исходящий запрос/).waitFor();assert.equal(await p.getByRole('button',{name:'ПРИНЯТЬ',exact:true}).count(),0);await click('ЗАКРЫТЬ');await click('НАЗАД');await click('ЗАКРЫТЬ');});
 await step('actual-ui-history-retained',async()=>{await p.getByText('Избранное',{exact:true}).click();await p.locator('#log .m-txt').filter({hasText:'Owner fixture retained history'}).waitFor();});
 }catch(e){report.fatal=e.message.split('\n')[0];}finally{save();await browser.close();}if(report.fatal)process.exitCode=1;console.log(JSON.stringify({steps:report.steps,fatal:report.fatal}));
})().catch(e=>{console.error(e);process.exitCode=1;});
