'use strict';
const assert=require('node:assert/strict');
// Only call for a synthetic peer created by this audit. IDB corruption is test setup;
// deletion and confirmation remain actual UI actions. No existing row is overwritten.
module.exports=async({pages,report,step,click,snap})=>{
 const [a]=pages,r=report.deletionGuard={scope:'Synthetic contact only; known-corrupt and unknown-opaque test fixtures; actual UI deletion'};
 const identity=await a.evaluate(()=>Core.keys.server_id);
 const fixture=await a.evaluate(async()=>{const peer=Core.activePeerId,known=await Storage.getAlias('node-peer-v4:'+peer,'L2'),unknown=Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('');await new Promise((resolve,reject)=>{const tx=Storage.db.transaction('pairing_material','readwrite'),store=tx.objectStore('pairing_material'),q=store.get(known);q.onsuccess=()=>{if(q.result){tx.abort();return;}store.put({alias:known,blob:'synthetic corrupt owner fixture'});store.put({alias:unknown,blob:'synthetic unknown opaque fixture'});};tx.oncomplete=resolve;tx.onabort=()=>reject(Error('Existing known owner row; refuse fixture overwrite'));});return {peer,known,unknown};});
 const state=()=>a.evaluate(async f=>{const has=async(table,key)=>!!await new Promise((resolve,reject)=>{const q=Storage.db.transaction(table).objectStore(table).get(key);q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);}),count=async table=>new Promise(resolve=>{const q=Storage.db.transaction(table).objectStore(table).count();q.onsuccess=()=>resolve(q.result);}),rt=Core.recordedNoteTurn;return {peer:await has('blind_peers',await Storage.getAlias(f.peer,'L1')),history:await count('blind_messages'),known:await has('pairing_material',f.known),unknown:await has('pairing_material',f.unknown),notes:rt?(await rt.rows(rt.capture())).length:0,peerRevoked:!!rt?.peerEpochs?.get(Core.keys)?.get(f.peer)?.blocked,routePresent:!!NodeManager.getRouteConfig()[f.peer]};},fixture);
 const remove=async()=>{await a.locator('#contact-list .chat-del-btn').first().click();await click(a,'ДА');};r.before=await state();
 await step('delete-contact-cancel',a,async()=>{await a.locator('#contact-list .chat-del-btn').first().click();await click(a,'НЕТ');assert.deepEqual(await state(),r.before);});
 await step('delete-corrupt-owner-visible-refusal',a,async()=>{await remove();await a.getByText('УДАЛЕНИЕ НЕ ВЫПОЛНЕНО',{exact:true}).waitFor();r.refused=await state();assert.deepEqual(r.refused,r.before);assert.equal(await a.evaluate(()=>Core.keys.server_id),identity);await snap(a,'delete-corrupt-owner-refusal');await click(a,'OK');});
 // Remove only our injected corrupt row, preserving all original records.
 await a.evaluate(async f=>new Promise((resolve,reject)=>{const tx=Storage.db.transaction('pairing_material','readwrite');tx.objectStore('pairing_material').delete(f.known);tx.oncomplete=resolve;tx.onabort=()=>reject(tx.error);}),fixture);
 await step('delete-valid-contact-preserves-unknown',a,async()=>{await remove();await a.locator('#contact-list .chat-del-btn').waitFor({state:'hidden',timeout:30000});await a.getByRole('button',{name:'OK',exact:true}).waitFor();r.deleted=await state();assert(!r.deleted.peer);assert.equal(r.deleted.history,0);assert(r.deleted.unknown);assert.equal(await a.evaluate(()=>Core.keys.server_id),identity);r.identityPreserved=true;await snap(a,'delete-valid-contact');await click(a,'OK');});
};
