const crypto=require('node:crypto'),{execFileSync}=require('node:child_process');const fs=require('node:fs'),{chromium}=require('/tmp/dmash-browser-tools/node_modules/playwright');const out='/tmp/dmash-qa-sender-voice/docs/evidence/2026-10-08/qa-deployed5a-resumed.json',base=JSON.parse(fs.readFileSync('/tmp/dmash-qa-sender-voice/docs/evidence/2026-10-08/qa-deployed5a-media-delete.json'));const clean=s=>String(s).replace(/[a-f0-9]{20,}/gi,'[id]').replace(/[A-Za-z0-9_-]{40,}/g,v=>v.startsWith('transport-v3-')?v:'[token]');const report={scope:'Same syntheticprofiles resumed via actual UI after incoming notification intercepted settings. Original harness failure retained. No storage reset/new miners.',expectedSHA:'5a2439834a2fc22db8f6ecd0b9674d533397ea8a',errors:[],steps:[],states:[],loadedSources:base.loadedSources,page0:base.page0,page1:base.page1,sw0:base.sw0,sw1:base.sw1};const save=()=>fs.writeFileSync(out,JSON.stringify(report,(k,v)=>typeof v==='string'&&!['actualSha256','expectedSha256','expectedSHA'].includes(k)?clean(v):v,2)+'\n');
const jobs=[];let finish;
(async()=>{let browser;try{browser=await chromium.connectOverCDP('http://127.0.0.1:9490');const all=browser.contexts().flatMap(c=>c.pages());let a,b;for(const p of all){if(await p.locator('.contact-progress-item').count())a=p;else b=p;}if(!a||!b)throw Error('Pair role detection failed');const pages=[a,b];for(const [profile,p]of pages.entries()){p.on('pageerror',e=>report.errors.push({profile,error:clean(e.message)}));p.on('response',r=>{const u=new URL(r.url());if(!u.pathname.startsWith('/not_messenger/'))return;const rel=u.pathname.slice('/not_messenger/'.length)||'index.html';if(!(rel.endsWith('.js')||rel==='index.html'||rel==='nodes.json'))return;jobs.push((async()=>{try{const actual=await r.body(),expected=execFileSync('git',['show',report.expectedSHA+':D-MASH PWA/not_messenger/'+rel]),hash=x=>crypto.createHash('sha256').update(x).digest('hex');report.loadedSources.push({profile,path:rel,actualSha256:hash(actual),expectedSha256:hash(expected),match:actual.equals(expected),fromServiceWorker:r.fromServiceWorker()});}catch(e){report.loadedSources.push({profile,path:rel,error:e.message.split('\n')[0]});}})());});}
for(const p of pages)p.setDefaultTimeout(15000);const click=(p,n)=>p.getByRole('button',{name:n,exact:true}).click();const prompt=async(p,v)=>{await p.locator('#p-in').fill(v);await p.locator('#p-ok').click();};const snap=async(p,state)=>{report.states.push({state,text:clean(await p.locator('body').innerText())});save();};const step=async(id,p,fn)=>{try{await fn();report.steps.push({id,status:'PASS'});console.log('PASS',id);}catch(e){report.steps.push({id,status:'FAIL',error:clean(e.message)});await snap(p,'FAIL '+id);throw e;}save();};
await step('resume-pending-notification',b,async()=>{if(await b.getByRole('button',{name:'OK',exact:true}).isVisible())await click(b,'OK');await click(b,'Настройки');await click(b,'ЗАПРОСЫ В КОНТАКТЫ');await b.getByRole('button',{name:/QA Alice/}).click();await click(b,'ПРИНЯТЬ');await prompt(b,'QA Bob');await b.locator('button[onclick*="Core.acceptPendingContactRequest"]').click();await b.getByRole('button',{name:'OK',exact:true}).waitFor({timeout:90000});await snap(b,'accepted');await click(b,'OK');});
await step('confirm-existing-request',a,async()=>{await Promise.all(pages.map(p=>p.locator('.contact-progress-item').waitFor({state:'hidden',timeout:180000})));});
for(const p of pages)await p.locator('#contact-list .peer-item').filter({hasNotText:'Избранное'}).first().click();
await step('key-exchange',a,async()=>{await click(a,'ОБМЕНЯТЬСЯ КЛЮЧАМИ');await a.locator('#msgInput').waitFor({state:'visible',timeout:180000});});
for(const [i,p]of pages.entries())await step('deployed-text-direction-'+i,p,async()=>{const message='Deployed synthetic message '+i;await p.locator('#msgInput').fill(message);await click(p,'SEND');await pages[1-i].locator('#log .m-txt').filter({hasText:message}).waitFor({timeout:180000});});
const root='/tmp/dmash-qa-sender-voice';finish=await require(root+'/tools/qa_note_observer.cjs')({pages,report,sourceRoot:''});
await require(root+'/tools/qa_sender_voice_turn.cjs')({pages,report,step,click,snap,observeRelay:finish});
await require(root+'/tools/qa_note_lifecycle_ui.cjs')({pages,report,step,click,snap});
await require(root+'/tools/qa_delete_peer_guard.cjs')({pages,report,step,click,snap});
await Promise.allSettled(jobs);if(!report.loadedSources.every(x=>x.match)||report.errors.length)throw Error('Exact source/browser errors gate failed');
report.finalPageSW=[];for(const p of pages)report.finalPageSW.push({page:await p.evaluate(()=>DMASH_RELEASE.id),controller:await p.evaluate(()=>!!navigator.serviceWorker.controller),sw:await p.context().serviceWorkers()[0].evaluate(()=>RELEASE_ID)});report.status='PASS_RESUMED_DEPLOYED_CONTROLS';

}catch(e){report.fatal=clean(e.message);console.log('FATAL',report.fatal);}finally{if(finish)await finish();await Promise.allSettled(jobs);save();await browser?.close();}})();
