'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),{chromium}=require(process.env.DMASH_PLAYWRIGHT_MODULE||'playwright');
const out=process.env.DMASH_QA_OUTPUT||'docs/evidence/2026-10-08/qa-delete-owner-ui.json',report={scope:'Actual deletion UI on retained synthetic PUBLIC pair; corruption injected only as test precondition, never user data; SW blocked contexts',steps:[],states:[],sources:[],errors:[]},jobs=[];let phase={name:'existing6e9',sha:'6e9e867addc5fe9d95dfb581b2ffbf3d1540cf1b'};
const clean=s=>String(s).replace(/(ID:\s*)[a-f0-9]{6,}/gi,'$1[synthetic-id]').replace(/[a-f0-9]{24,}/gi,'[id]').replace(/[A-Za-z0-9_-]{40,}/g,'[token]');const save=()=>fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');
(async()=>{const browser=await chromium.connectOverCDP('http://127.0.0.1:9480');try{
 const all=browser.contexts().flatMap(c=>c.pages());let a,b;for(const p of all){if(await p.evaluate(async()=>Core.recordedNoteTurn&&(await Core.recordedNoteTurn.rows(Core.recordedNoteTurn.capture())).length>0))a=p;else b=p;}assert(a&&b);const pages=[a,b],names=await Promise.all(pages.map(p=>p.evaluate(()=>Core.activeIdentity))),identities=await Promise.all(pages.map(p=>p.evaluate(()=>Core.keys.server_id)));
 const click=(p,s)=>p.getByRole('button',{name:s,exact:true}).click(),snap=async(label)=>report.states.push({phase:phase.name,label,text:clean(await a.locator('body').innerText()).slice(-3500)});
 const step=async(id,fn,soft=false)=>{try{await fn();report.steps.push({id,phase:phase.name,status:'PASS'});console.log('PASS',id);}catch(e){report.steps.push({id,phase:phase.name,status:'FAIL',error:clean(e.message).slice(0,600)});await snap(id);console.log('FAIL',id,clean(e.message));if(!soft)throw e;}finally{save();}};
 for(const [profile,p]of pages.entries()){
  p.on('pageerror',e=>report.errors.push({phase:phase.name,profile,error:clean(e.message)}));
  p.on('response',r=>{const u=new URL(r.url());if(!u.pathname.startsWith('/not_messenger/'))return;const rel=u.pathname.slice('/not_messenger/'.length)||'index.html';if(!(rel.endsWith('.js')||rel==='index.html'||rel==='nodes.json'))return;const captured={...phase};jobs.push((async()=>{try{const actual=await r.body(),expected=execFileSync('git',['show',captured.sha+':D-MASH PWA/not_messenger/'+rel]),hash=x=>crypto.createHash('sha256').update(x).digest('hex');report.sources.push({phase:captured.name,profile,path:rel,actual:hash(actual),expected:hash(expected),match:actual.equals(expected)});}catch(e){report.sources.push({phase:captured.name,profile,path:rel,error:e.message.split('\n')[0]});}})());});
  await p.context().unroute('**/not_messenger/**');await p.context().route('**/not_messenger/**',async route=>{if(!phase.root)return route.continue();const rel=new URL(route.request().url()).pathname.split('/not_messenger/')[1]||'index.html',file=path.resolve(phase.root,rel);if(!file.startsWith(path.resolve(phase.root)+path.sep)||!fs.existsSync(file))return route.continue();await route.fulfill({body:fs.readFileSync(file),contentType:{'.js':'application/javascript','.html':'text/html; charset=utf-8','.json':'application/json','.css':'text/css','.wasm':'application/wasm'}[path.extname(file)]||'application/octet-stream'});});
 }
 await step('integrated6e9-circle-actual-playback',async()=>{const video=b.locator('#log video').last();await video.waitFor();const box=await video.boundingBox();await b.mouse.click(box.x+box.width/2,box.y+box.height/2);await b.waitForFunction(()=>[...document.querySelectorAll('#log video')].at(-1)?.currentTime>0);});
 const reload=async next=>{phase=next;for(const [i,p]of pages.entries()){await p.reload();for(const d of '3333')await click(p,d);await click(p,'=');await p.getByRole('button',{name:names[i],exact:true}).waitFor({timeout:60000});await click(p,names[i]);await p.locator('#p2').fill('Synthetic-only-2026!');await click(p,'ВОЙТИ');await p.getByText('Избранное',{exact:true}).waitFor({timeout:90000});await p.locator('#contact-list .peer-item').filter({hasNotText:'Избранное'}).first().click();assert.equal(await p.evaluate(()=>Core.keys.server_id),identities[i]);assert.equal(await p.evaluate(()=>DMASH_RELEASE.id),'transport-v3-node-preparation-20261008.29');}report[phase.name+'IdentityPreserved']=true;await Promise.allSettled(jobs);};
 await step('reload-red3e-exact',()=>reload({name:'red3e',sha:'3e70587cc9aad76ba3549650506914f4a5e500ea',root:'/tmp/dmash-delete-red3e/D-MASH PWA/not_messenger'}));
 await step('red3e-voice-sanity',async()=>{await a.locator('#voice-btn').click();await a.locator('#recording-timer').waitFor({state:'visible'});await a.waitForTimeout(2300);await a.locator('#input-area .send-btn').click();await a.locator('#recording-timer').waitFor({state:'hidden'});await a.locator('.note-transfer-state').last().filter({hasText:'Доставлено'}).waitFor({timeout:60000});});
 const fixture=await a.evaluate(async()=>{const peer=Core.activePeerId,known=await Storage.getAlias('node-peer-v4:'+peer,'L2'),unknown=Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('');await new Promise((resolve,reject)=>{const tx=Storage.db.transaction('pairing_material','readwrite'),store=tx.objectStore('pairing_material'),q=store.get(known);q.onsuccess=()=>{if(q.result){tx.abort();return;}store.put({alias:known,blob:'synthetic corrupt owner fixture'});store.put({alias:unknown,blob:'synthetic opaque versioned fixture'});};tx.oncomplete=resolve;tx.onabort=()=>reject(Error('Pre-existing known owner record: refusing overwrite'));});return {peer,known,unknown};});
 const state=()=>a.evaluate(async f=>{const has=async(table,key)=>!!await new Promise((resolve,reject)=>{const q=Storage.db.transaction(table).objectStore(table).get(key);q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});const count=async table=>new Promise(resolve=>{const q=Storage.db.transaction(table).objectStore(table).count();q.onsuccess=()=>resolve(q.result);});const rt=Core.recordedNoteTurn;return {peer:await has('blind_peers',await Storage.getAlias(f.peer,'L1')),history:await count('blind_messages'),known:await has('pairing_material',f.known),unknown:await has('pairing_material',f.unknown),notes:rt?(await rt.rows(rt.capture())).length:0,peerRevoked:!!rt?.peerEpochs?.get(Core.keys)?.get(f.peer)?.blocked,routePresent:!!NodeManager.getRouteConfig()[f.peer]};},fixture);
 const deleteClick=async()=>{await a.locator('#contact-list .chat-del-btn').first().click();await click(a,'ДА');};
 report.redBefore=await state();const redErrors=report.errors.length;
 await deleteClick();for(let n=0;n<100;n++){if(report.errors.length>redErrors||await a.getByRole('button',{name:'OK',exact:true}).isVisible())break;await a.waitForTimeout(100);}report.redAfter=await state();
 await step('red3e-refusal-visible-no-side-effects',async()=>{assert(await a.getByText('УДАЛЕНИЕ НЕ ВЫПОЛНЕНО',{exact:true}).isVisible(),'Corrupt owner requires a visible refusal');assert.deepEqual(report.redAfter,report.redBefore);},true);
 await step('red3e-storage-preserved',async()=>{assert(report.redAfter.peer&&report.redAfter.known&&report.redAfter.unknown);assert.equal(report.redAfter.history,report.redBefore.history);});
 await step('reload-green668-exact',()=>reload({name:'green668',sha:'668be72ff419fb122fe00171b8a6f2f32c33fffb',root:'/tmp/dmash-delete-green668/D-MASH PWA/not_messenger'}));
 report.greenBefore=await state();
 await step('green-delete-cancel',async()=>{await a.locator('#contact-list .chat-del-btn').first().click();await click(a,'НЕТ');assert.deepEqual(await state(),report.greenBefore);});
 await step('green-corrupt-owner-visible-refusal',async()=>{await deleteClick();await a.getByText('УДАЛЕНИЕ НЕ ВЫПОЛНЕНО',{exact:true}).waitFor();report.greenAfter=await state();assert.deepEqual(report.greenAfter,report.greenBefore);await snap('green-visible-refusal');await click(a,'OK');});
 // Restore only the injected corrupt fixture; do not reset or rewrite real Account records.
 await a.evaluate(async f=>new Promise((resolve,reject)=>{const tx=Storage.db.transaction('pairing_material','readwrite');tx.objectStore('pairing_material').delete(f.known);tx.oncomplete=resolve;tx.onabort=()=>reject(tx.error);}),fixture);
 await step('green-valid-delete-preserves-unknown',async()=>{await deleteClick();await a.locator('#contact-list .chat-del-btn').waitFor({state:'hidden',timeout:30000});await a.getByRole('button',{name:'OK',exact:true}).waitFor();report.validAfter=await state();assert(!report.validAfter.peer);assert.equal(report.validAfter.history,0);assert(report.validAfter.unknown);await snap('green-delete-done');await click(a,'OK');});
 await Promise.allSettled(jobs);assert(report.sources.every(x=>x.match),'Loaded bytes exact per phase');assert(!report.errors.some(x=>x.phase==='green668'),'No green UI pageerror');report.status='EXPECTED_RED_THEN_GREEN_PASS';
}catch(e){report.fatal=clean(e.message);report.status='FAIL';console.log('FATAL',report.fatal);}finally{await Promise.allSettled(jobs);save();await browser.close();}})();
