'use strict';
// Retained synthetic .26 profile ONLY; no downgrade/reset. Run after active capture timing tests.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const {chromium}=require(process.env.DMASH_PLAYWRIGHT_MODULE||'playwright');
const candidate=process.env.DMASH_TEST_PWA_ROOT,sha=process.env.DMASH_EXPECT_SHA,out=process.env.DMASH_QA_OUTPUT;
if(!candidate||!sha||!out)throw Error('Explicit immutable candidate/SHA/output required');
const report={scope:'Retained synthetic old-PWA pending note upgrade without data reset; not user profile',candidateSHA:sha,steps:[],states:[],sources:[],errors:[]},jobs=[];
const save=()=>fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');
const clean=s=>String(s).replace(/(?<=ID:\s*)[a-f0-9]{6,}/gi,'[synthetic-id]').replace(/[a-f0-9]{24,}/gi,'[id]').replace(/[A-Za-z0-9_-]{40,}/g,'[token]');
(async()=>{const browser=await chromium.connectOverCDP('http://127.0.0.1:9452');try{
 const pages=browser.contexts().flatMap(c=>c.pages());assert.equal(pages.length,2);let sender,recipient;
 for(const p of pages){assert.equal(await p.evaluate(()=>DMASH_RELEASE.id),'transport-v3-node-preparation-20261008.26','Old browser must still run original .26');if(await p.evaluate(async()=> (await Storage.getAllBoxes('blind_messages')).some(m=>m.text?.type==='voice'&&!m.inbound)))sender=p;else recipient=p;}
 assert(sender&&recipient,'Unique old sender/recipient');
 const a=sender,b=recipient,click=(p,s)=>p.getByRole('button',{name:s,exact:true}).click();
 const snap=async label=>report.states.push({label,text:clean(await a.locator('body').innerText()).slice(-3000)});
 const step=async(id,fn)=>{try{await fn();report.steps.push({id,status:'PASS',at:new Date().toISOString()});console.log('PASS',id);}catch(e){report.steps.push({id,status:'FAIL',error:clean(e.message).slice(0,600)});await snap(id);throw e;}finally{save();}};
 const oldState=()=>a.evaluate(async()=>({rows:(await Storage.getAllBoxes('blind_outbox')).filter(x=>x.record==='media_outbound').map(x=>({status:x.status,acked:x.acked?.length||0,count:x.meta?.count||0})),history:(await Storage.getAllBoxes('blind_messages')).length}));
 const identity=await a.evaluate(()=>Core.keys.server_id),name=await a.evaluate(()=>Core.activeIdentity),before=await oldState();assert.equal(before.rows.length,0,'Existing old outbound must be drained before fixture');
 await step('legacy-recipient-node-off',async()=>{await click(b,'Настройки');await click(b,'УЗЛЫ И ПОДКЛЮЧЕНИЕ');await click(b,'OFF');await b.getByRole('button',{name:'ON',exact:true}).waitFor();await click(b,'НАЗАД');await click(b,'ЗАКРЫТЬ');});
 await step('legacy-actual-record-pending',async()=>{await a.locator('#voice-btn').click();await a.locator('#recording-timer').waitFor({state:'visible'});await a.waitForTimeout(2300);await a.locator('#input-area .send-btn').click();await a.locator('#recording-timer').waitFor({state:'hidden'});const deadline=Date.now()+10000;while(!(await oldState()).rows.length){if(Date.now()>deadline)throw Error('Legacy intent not durably queued');await a.waitForTimeout(100);}report.pendingBeforeUpgrade=await oldState();assert.equal(report.pendingBeforeUpgrade.rows.length,1);assert.equal(report.pendingBeforeUpgrade.history,before.history+1);});
 await step('legacy-upgrade-same-profile',async()=>{
  a.on('pageerror',e=>report.errors.push(clean(e.message)));
  a.on('response',r=>{const u=new URL(r.url());if(!u.pathname.startsWith('/not_messenger/'))return;const rel=u.pathname.slice('/not_messenger/'.length)||'index.html';if(!(rel.endsWith('.js')||rel==='index.html'||rel==='nodes.json'))return;jobs.push((async()=>{const actual=await r.body(),expected=execFileSync('git',['show',sha+':D-MASH PWA/not_messenger/'+rel]),hash=b=>crypto.createHash('sha256').update(b).digest('hex');report.sources.push({path:rel,actual:hash(actual),expected:hash(expected),match:actual.equals(expected)});})());});
  const cdp=await a.context().newCDPSession(a);await cdp.send('Network.setBypassServiceWorker',{bypass:true});
  await a.context().route('**/not_messenger/**',async route=>{const rel=new URL(route.request().url()).pathname.split('/not_messenger/')[1]||'index.html',file=path.resolve(candidate,rel);if(!file.startsWith(path.resolve(candidate)+path.sep)||!fs.existsSync(file))return route.continue();await route.fulfill({body:fs.readFileSync(file),contentType:{'.js':'application/javascript','.html':'text/html; charset=utf-8','.json':'application/json','.css':'text/css','.wasm':'application/wasm'}[path.extname(file)]||'application/octet-stream'});});
  await a.reload();for(const d of '3333')await click(a,d);await click(a,'=');await a.getByRole('button',{name,exact:true}).waitFor({timeout:60000});await click(a,name);await a.locator('#p2').fill('Synthetic-only-2026!');await click(a,'ВОЙТИ');await a.getByText('Избранное',{exact:true}).waitFor({timeout:90000});await a.locator('#contact-list .peer-item').filter({hasNotText:'Избранное'}).first().click();assert.equal(await a.evaluate(()=>Core.keys.server_id),identity);const restored=await oldState();assert.equal(restored.history,before.history+1);assert.equal(restored.rows.length,1);report.afterUpgrade=restored;report.page=await a.evaluate(()=>DMASH_RELEASE.id);report.sw='Network bypass in existing synthetic context (not a real SW upgrade)';
 });
 await step('legacy-reconnect-drains-original',async()=>{await click(b,'Настройки');await click(b,'УЗЛЫ И ПОДКЛЮЧЕНИЕ');await click(b,'ON');await b.getByRole('button',{name:'OFF',exact:true}).waitFor({timeout:60000});await click(b,'НАЗАД');await click(b,'ЗАКРЫТЬ');const deadline=Date.now()+120000;while((await oldState()).rows.length){if(Date.now()>deadline)throw Error('Old pending not drained in120s after actual reconnect');await a.waitForTimeout(500);}assert.equal((await oldState()).history,before.history+1);assert.equal(await a.evaluate(()=>Core.keys.server_id),identity);await snap('legacy-delivered');});
 await Promise.all(jobs);assert(report.sources.length&&report.sources.every(x=>x.match));assert.equal(report.errors.length,0);report.status='PASS_LEGACY_UPGRADE_SLICE';
}catch(e){report.fatal=clean(e.message);report.status='FAIL_OR_NOT_RUN';console.log(report.status,report.fatal);}finally{await Promise.allSettled(jobs);save();await browser.close();}})().catch(e=>{report.status="NOT_RUN";report.fatal=clean(e.message).slice(0,500);save();console.log(report.status,report.fatal);process.exitCode=1;});
