'use strict';
const assert=require('node:assert/strict');
module.exports=async({pages,report,step,click,snap})=>{
 const [a,b]=pages,name=await a.evaluate(()=>Core.activeIdentity);
 const rows=()=>a.evaluate(async()=>{const rt=Core.recordedNoteTurn;return rt?(await rt.rows(rt.capture())).sort((x,y)=>x.createdAt-y.createdAt).map(x=>({status:x.status,retained:!!x.content})):[];});
 const before=await rows();report.switchCircle={before,notRun:['Cancel/retry blocked by missing post-reload controls in original candidate']};
 const enter=async who=>{const saved=a.getByRole('button',{name:who,exact:true});if(await saved.isVisible())await saved.click();else{if(await a.getByRole('button',{name:'+ НОВЫЙ ВХОД',exact:true}).isVisible())await click(a,'+ НОВЫЙ ВХОД');await a.locator('#p1').fill(who);}await a.locator('#p2').fill('Synthetic-only-2026!');await click(a,'ВОЙТИ');await a.getByText('Избранное',{exact:true}).waitFor({timeout:90000});};
 await step('note-account-switch-isolation',a,async()=>{await click(a,'[ ВЫХОД ]');await enter('qa-media-isolation-'+Date.now());assert.equal(await a.locator('#contact-list .peer-item').count(),1);assert.equal((await rows()).length,0);await snap(a,'other-account-empty');await click(a,'[ ВЫХОД ]');await enter(name);await a.locator('#contact-list .peer-item').filter({hasNotText:'Избранное'}).first().click();assert.equal((await rows()).length,before.length);assert((await rows()).at(-1).retained);});
 await step('note-peer-reconnect-recovery',b,async()=>{await click(b,'Настройки');await click(b,'УЗЛЫ И ПОДКЛЮЧЕНИЕ');await click(b,'ON');await b.getByRole('button',{name:'OFF',exact:true}).waitFor({timeout:60000});await click(b,'НАЗАД');await click(b,'ЗАКРЫТЬ');const deadline=Date.now()+90000;while((await rows()).at(-1).status!=='delivered'){if(Date.now()>deadline)throw Error('Retained pending note not delivered after UI reconnect');await a.waitForTimeout(500);}await snap(a,'reconnected-delivery');});
 await step('circle-cancel',a,async()=>{await a.locator('#circle-btn').click();await a.locator('#recording-timer').waitFor({state:'visible'});await a.locator('#circle-btn').click();await a.locator('#recording-timer').waitFor({state:'hidden'});assert.equal((await rows()).length,before.length);});
 await step('circle-send',a,async()=>{await a.locator('#circle-btn').click();await a.locator('#recording-timer').waitFor({state:'visible'});await a.waitForTimeout(2300);await a.locator('#input-area .send-btn').click();await a.locator('#recording-timer').waitFor({state:'hidden'});await a.locator('.note-transfer-state').last().filter({hasText:'Доставлено'}).waitFor({timeout:60000});assert.equal((await rows()).length,before.length+1);});
 await step('circle-decode-ready-no-autoplay',b,async()=>{await b.getByRole('button',{name:'РАСШИФРОВАТЬ КРУЖОК',exact:true}).last().click();await b.locator('#log video').last().waitFor();await b.waitForFunction(()=>[...document.querySelectorAll('#log video')].at(-1)?.readyState>=2);report.switchCircle.video=await b.locator('#log video').last().evaluate(v=>({duration:v.duration,paused:v.paused,autoplay:v.autoplay,readyState:v.readyState}));assert(report.switchCircle.video.paused&&!report.switchCircle.video.autoplay);});
};
