'use strict';
const assert=require('node:assert/strict');
module.exports=async({pages,report,step,click,snap,resumeAfterReload=false})=>{
 const [a,b]=pages, names=[resumeAfterReload?await a.getByRole('button',{name:/^qa-contacts-0-/}).first().innerText():await a.evaluate(()=>Core.activeIdentity)];
 const r=report.noteLifecycle={scope:'Same synthetic pair; actual offline Node controls, reload/login, Account switch, durable cancel/retry and circle',states:[]};
 const rows=()=>a.evaluate(async()=>{const rt=Core.recordedNoteTurn;return rt?(await rt.rows(rt.capture())).sort((x,y)=>x.createdAt-y.createdAt).map(x=>({status:x.status,size:x.size,retained:!!x.content})):[];});
 const noteState=async(label)=>r.states.push({label,at:new Date().toISOString(),notes:await rows()});
 const node=async(p,on)=>{await click(p,'Настройки');await click(p,'УЗЛЫ И ПОДКЛЮЧЕНИЕ');await click(p,on?'ON':'OFF');await p.getByRole('button',{name:on?'OFF':'ON',exact:true}).waitFor({timeout:60000});await click(p,'НАЗАД');await click(p,'ЗАКРЫТЬ');};
 const openPeer=async(p)=>p.locator('#contact-list .peer-item').filter({hasNotText:'Избранное'}).first().click();
 const login=async(p,name)=>{if(await p.getByRole('button',{name,exact:true}).isVisible())await click(p,name);else{if(await p.getByRole('button',{name:'+ НОВЫЙ ВХОД',exact:true}).isVisible())await click(p,'+ НОВЫЙ ВХОД');await p.locator('#p1').fill(name);}await p.locator('#p2').fill('Synthetic-only-2026!');await click(p,'ВОЙТИ');await p.getByText('Избранное',{exact:true}).waitFor({timeout:90000});};
 const record=async(p,kind='voice')=>{await p.locator(kind==='voice'?'#voice-btn':'#circle-btn').click();await p.locator('#recording-timer').waitFor({state:'visible'});await p.waitForTimeout(2300);await click(p,'SEND');await p.locator('#recording-timer').waitFor({state:'hidden'});};
 if(resumeAfterReload){await login(a,names[0]);await openPeer(a);}
 if(!resumeAfterReload)await step('note-offline-peer',b,async()=>{await node(b,false);});
 const count=(await rows()).length-(resumeAfterReload?1:0);
 if(!resumeAfterReload)await step('note-offline-durable',a,async()=>{await record(a);await a.getByRole('button',{name:'Отменить отправку',exact:true}).last().waitFor();const x=await rows();assert.equal(x.length,count+1);assert(x.at(-1).retained);await noteState('offline-saved');await snap(a,'offline-waiting');});
 if(!resumeAfterReload)await step('note-reload-preserves',a,async()=>{await a.reload();for(const d of '3333')await click(a,d);await click(a,'=');await a.getByRole('button',{name:names[0],exact:true}).waitFor({timeout:60000});await login(a,names[0]);await openPeer(a);await a.getByRole('button',{name:'Отменить отправку',exact:true}).last().waitFor();assert.equal((await rows()).length,count+1);await noteState('after-reload');});
 if(resumeAfterReload)await step('note-reload-restored-via-saved-account',a,async()=>{assert.equal((await rows()).length,count+1);assert((await rows()).at(-1).retained);await noteState('after-reload-saved-account');});
 await step('note-cancel-retained',a,async()=>{await a.getByRole('button',{name:'Отменить отправку',exact:true}).last().click();await a.getByRole('button',{name:'Повторить',exact:true}).last().waitFor();const x=(await rows()).at(-1);assert.equal(x.status,'cancelled');assert(x.retained);await snap(a,'cancel-retained');});
 await step('note-retry-retained',a,async()=>{await a.getByRole('button',{name:'Повторить',exact:true}).last().click();await a.getByRole('button',{name:'Отменить отправку',exact:true}).last().waitFor();assert.equal((await rows()).length,count+1);});
 await step('note-account-switch-isolation',a,async()=>{await click(a,'[ ВЫХОД ]');await login(a,'qa-media-other-'+Date.now());assert.equal(await a.locator('#contact-list .peer-item').count(),1);assert.equal((await rows()).length,0);await click(a,'[ ВЫХОД ]');await login(a,names[0]);await openPeer(a);await a.getByRole('button',{name:'Отменить отправку',exact:true}).last().waitFor();assert.equal((await rows()).length,count+1);await noteState('original-account-restored');});
 await step('note-reconnect-delivery',b,async()=>{await node(b,true);await a.locator('.note-transfer-state').last().filter({hasText:'Доставлено'}).waitFor({timeout:90000});assert.equal((await rows()).at(-1).status,'delivered');await noteState('reconnected-delivered');});
 await step('circle-capture-cancel',a,async()=>{await a.locator('#circle-btn').click();await a.locator('#recording-timer').waitFor({state:'visible'});await a.locator('#circle-btn').click();await a.locator('#recording-timer').waitFor({state:'hidden'});assert.equal((await rows()).length,count+1);});
 await step('circle-record-deliver',a,async()=>{await record(a,'circle');await a.locator('.note-transfer-state').last().filter({hasText:'Доставлено'}).waitFor({timeout:60000});assert.equal((await rows()).length,count+2);});
 await step('circle-decrypt-no-autoplay',b,async()=>{await b.getByRole('button',{name:'РАСШИФРОВАТЬ КРУЖОК',exact:true}).last().click();await b.locator('#log video').last().waitFor();await b.waitForFunction(()=>[...document.querySelectorAll('#log video')].at(-1)?.readyState>=2);r.circle=await b.locator('#log video').last().evaluate(v=>({duration:v.duration,readyState:v.readyState,paused:v.paused,autoplay:v.autoplay}));assert(r.circle.paused&&!r.circle.autoplay);});
};
