'use strict';
// Called after actual UI pairing and verified bidirectional messages.
// All control mutations are user actions; evaluate only observes state/stats.
const assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs');
module.exports=async({pages,report,step,click,snap,resumeAt})=>{
 if(resumeAt){const run=step;let reached=false;step=async(id,...args)=>{if(id===resumeAt)reached=true;if(reached)return run(id,...args);};}
 const [a,b]=pages;
 const idle=p=>p.waitForFunction(()=>Core.callState==='idle',null,{timeout:30000});
 const relay=async(p)=>{await p.waitForFunction(async()=>{if(!Core.peerConnection)return false;const stats=await Core.peerConnection.getStats();let pair,received=false;for(const row of stats.values()){if(row.type==='transport'&&row.selectedCandidatePairId)pair=stats.get(row.selectedCandidatePairId);if(row.type==='inbound-rtp'&&(row.kind==='audio'||row.mediaType==='audio')&&row.bytesReceived>0)received=true;}return received&&pair&&stats.get(pair.localCandidateId)?.candidateType==='relay'&&stats.get(pair.remoteCandidateId)?.candidateType==='relay';},null,{timeout:60000});};
 await step('UI11-call-decline',a,async()=>{await a.locator('#voip-btn').click();await b.locator('#decline-call').waitFor({state:'visible',timeout:90000});await snap(b,'incoming-call');await b.locator('#decline-call').click();await Promise.all(pages.map(idle));});
 await step('UI11-call-accept-relay',a,async()=>{await a.locator('#voip-btn').click();await b.locator('#accept-call').waitFor({state:'visible',timeout:90000});await b.locator('#accept-call').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>Core.callState==='connected'&&Core.peerConnection?.connectionState==='connected',null,{timeout:60000})));await Promise.all(pages.map(relay));await snap(a,'connected-call-relay');});
 await step('UI11-mute-unmute',a,async()=>{await a.locator('#btn-mic-toggle').click();await a.waitForFunction(()=>Core.localStream.getAudioTracks().every(t=>!t.enabled));await a.locator('#btn-mic-toggle').click();await a.waitForFunction(()=>Core.localStream.getAudioTracks().every(t=>t.enabled));});
 await step('UI11-speaker-toggle',a,async()=>{const before=await a.evaluate(()=>Boolean(Core.isSpeakerOn));await a.locator('#btn-speaker-toggle').click();assert.equal(await a.evaluate(()=>Boolean(Core.isSpeakerOn)),!before);assert.equal(await a.locator('#btn-speaker-toggle').evaluate(e=>e.classList.contains('off')),before);await a.locator('#btn-speaker-toggle').click();});
 try {await step('UI11-video-toggle',a,async()=>{await a.locator('#btn-vid-toggle').click();await a.waitForFunction(()=>Core.localStream?.getVideoTracks().some(t=>t.enabled),null,{timeout:5000});await a.locator('#btn-vid-toggle').click();await a.waitForFunction(()=>!Core.localStream?.getVideoTracks().some(t=>t.enabled));});} catch (_) { /* Keep the failed video control recorded, continue with call cleanup and files. */ }
 await step('UI11-hangup',a,async()=>{await a.locator('#call-overlay button[onclick="Core.endCall()"]').click();await Promise.all(pages.map(idle));await a.locator('#call-overlay').waitFor({state:'hidden'});});
 report.mediaLimits=['Synthetic camera/microphone, real WSS signaling and TURN','Screen-share OS chooser and physical audio output NOT RUN'];
 const choose=async(p,bytes)=>{const pending=p.waitForEvent('filechooser');await p.locator('button[onclick="Core.uiAttach()"]').click();await(await pending).setFiles({name:'synthetic-qa.bin',mimeType:'application/octet-stream',buffer:bytes});};
 const incomingFile=()=>Promise.race([b.locator('.dmash-file-transfer').getByRole('button',{name:'Принять',exact:true}).waitFor({timeout:90000}),a.waitForFunction(()=>Core._fileTransfer?.failed,null,{timeout:90000}).then(async()=>{throw Error(await a.locator('.dmash-file-transfer').innerText());})]);
 await step('UI12-empty-file-bound',a,async()=>{await choose(a,Buffer.alloc(0));await a.getByText('Поддерживаются файлы от 1 байта до 64 МиБ',{exact:true}).waitFor();await click(a,'OK');});
 await step('UI12-file-reject',a,async()=>{await choose(a,Buffer.from('Synthetic file decline'));await incomingFile();await snap(b,'incoming-file-consent');await b.locator('.dmash-file-transfer').getByRole('button',{name:'Отмена',exact:true}).click();await b.locator('.dmash-file-transfer').waitFor({state:'hidden'});await a.locator('.dmash-file-transfer').getByRole('button',{name:'Закрыть',exact:true}).waitFor({timeout:30000});await a.locator('.dmash-file-transfer').getByRole('button',{name:'Закрыть',exact:true}).click();});
 const bytes=Buffer.alloc(1024*1024+13);for(let i=0;i<bytes.length;i++)bytes[i]=i%251;
 await step('UI12-file-accept-download-integrity',a,async()=>{await choose(a,bytes);await incomingFile();await b.locator('.dmash-file-transfer').getByRole('button',{name:'Принять',exact:true}).click();await Promise.all(pages.map(p=>p.getByText('Передано и проверено',{exact:true}).waitFor({timeout:120000})));await snap(b,'file-complete');const waiting=b.waitForEvent('download');await b.getByRole('link',{name:'Сохранить файл',exact:true}).click();const download=await waiting;const received=fs.readFileSync(await download.path());assert.equal(received.length,bytes.length);assert.equal(crypto.createHash('sha256').update(received).digest('hex'),crypto.createHash('sha256').update(bytes).digest('hex'));report.file={bytes:bytes.length,downloadHashVerified:true};await Promise.all(pages.map(p=>p.locator('.dmash-file-transfer').getByRole('button',{name:'Закрыть',exact:true}).click()));});
};
