'use strict';
const assert=require('node:assert/strict');
module.exports=async({pages,report,step,click,snap})=>{
 const [a,b]=pages;report.senderVoice={scope:'Synthetic fake microphone, actual record/SEND/decrypt, real peer transport; no user profile',timeline:[]};
 const observe=async label=>{const state=await a.evaluate(async()=>{const media=Core.recordedMedia;const operations=media?await media.storage.getAllBoxes('blind_outbox'):[];const history=media?await media.storage.getAllBoxes('blind_messages'):[];return {recording:!!Core.isRecording,timerVisible:!document.querySelector('#recording-timer')?.hidden,outbox:operations.filter(o=>o.record==='media_outbound').map(o=>({status:o.status,acked:o.acked?.length||0,fragments:o.meta?.count||0,historyCommitted:!!o.historyCommitted})),voiceHistory:history.filter(m=>m.text?.type==='voice'&&!m.inbound).map(m=>({state:m.transportState})),dom:[...document.querySelectorAll('#log .msg.out')].map(e=>({text:e.innerText,states:[...e.querySelectorAll('.m-state')].map(s=>({text:s.textContent,title:s.title}))}))};});report.senderVoice.timeline.push({label,at:new Date().toISOString(),...state});return state;};
 await step('voice-start-recording',a,async()=>{await a.locator('#voice-btn').click();await a.locator('#recording-timer').waitFor({state:'visible'});await observe('recording');});
 await a.waitForTimeout(2300);
 await step('voice-send-stops-recording',a,async()=>{await click(a,'SEND');await a.locator('#recording-timer').waitFor({state:'hidden'});await a.getByRole('button',{name:'РАСШИФРОВАТЬ',exact:true}).waitFor({timeout:30000});await observe('queued');await snap(a,'voice-sender-after-SEND');});
 await step('voice-peer-receive-decrypt',b,async()=>{await b.getByRole('button',{name:'РАСШИФРОВАТЬ',exact:true}).waitFor({timeout:120000});await click(b,'РАСШИФРОВАТЬ');await b.locator('#log audio').waitFor();await b.waitForFunction(()=>document.querySelector('#log audio')?.readyState>=2,null,{timeout:15000});report.senderVoice.receiver=await b.locator('#log audio').evaluate(e=>({readyState:e.readyState,duration:e.duration}));await snap(b,'voice-peer-audio-ready');});
 await step('voice-final-receipt-retired',a,async()=>{const deadline=Date.now()+60000;while(true){const s=await observe('receipt-wait');if(!s.outbox.length&&s.voiceHistory.some(m=>m.state==='DELIVERED'||m.state==='READ'))break;if(Date.now()>deadline)throw Error('Media receipt not retired within60s after receive');await a.waitForTimeout(1000);}await snap(a,'voice-sender-after-receipt');});
 await a.waitForTimeout(3000);
 try{await step('voice-sender-visible-final-status',a,async()=>{const s=await observe('visible-status-check');const last=s.dom.at(-1);assert(last?.states.some(x=>x.title==='Delivered to device'||x.title==='Read by account'),'Sender must stop queued indicator after authenticated final receipt');});}catch(_){report.senderVoice.issue='Sender DOM status remains queued after persisted DELIVERED and outbox removal';}
 await step('voice-sender-decrypt-local-copy',a,async()=>{await click(a,'РАСШИФРОВАТЬ');await a.locator('#log audio').waitFor();await a.waitForFunction(()=>document.querySelector('#log audio')?.readyState>=2);await observe('sender-decrypted');});
 await step('voice-reopen-reflects-receipt',a,async()=>{await a.locator('#contact-list .peer-item').filter({hasNotText:'Избранное'}).first().click();await a.getByRole('button',{name:'РАСШИФРОВАТЬ',exact:true}).waitFor();const s=await observe('reopened');assert(s.dom.at(-1)?.states.some(x=>x.title==='Delivered to device'||x.title==='Read by account'));await snap(a,'voice-sender-reopened');});
};
