'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require(process.env.DMASH_PLAYWRIGHT_MODULE||'playwright');
const root=process.env.DMASH_TEST_PWA_ROOT&&path.resolve(process.env.DMASH_TEST_PWA_ROOT),base='https://messenger.d-mash.ru/not_messenger/';
const report={base,mode:root?'LOCAL MODIFIED SOURCE / real WSS / SW blocked':'DEPLOYED',baseSHA:require('node:child_process').execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),startedAt:new Date().toISOString(),files:{},servedFiles:{},checks:[],errors:[]};
for(const f of ['js/node_manager.js','js/acceptance_fixes.js','js/acceptance_v50.js','nodes.json'])report.files[f]=crypto.createHash('sha256').update(fs.readFileSync(path.join(root||'D-MASH PWA/not_messenger',f))).digest('hex');
const output=process.env.DMASH_QA_OUTPUT||'docs/evidence/2026-10-08/qa-controls-blockers-local.json';
(async()=>{let browser;try{
 browser=await chromium.launch({executablePath:process.env.DMASH_CHROME,headless:true,args:['--no-sandbox','--use-fake-device-for-media-stream']});
 const context=await browser.newContext({serviceWorkers:root?'block':'allow',permissions:['clipboard-read','clipboard-write']});
 if(root)await context.route('**/not_messenger/**',async route=>{const rel=decodeURIComponent(new URL(route.request().url()).pathname.split('/not_messenger/')[1]||'index.html'),f=path.resolve(root,rel);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)||!fs.statSync(f).isFile())return route.continue();const bytes=fs.readFileSync(f),hash=crypto.createHash('sha256').update(bytes).digest('hex');report.servedFiles[rel]||=[];if(!report.servedFiles[rel].includes(hash))report.servedFiles[rel].push(hash);await route.fulfill({body:bytes,contentType:{'.html':'text/html','.js':'application/javascript','.css':'text/css','.wasm':'application/wasm','.json':'application/json'}[path.extname(f)]||'application/octet-stream'});});
 const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>report.errors.push(e.message));page.on('dialog',d=>d.dismiss());
 await page.goto(base);await page.waitForFunction(()=>window.DMASH_RELEASE);report.page=await page.evaluate(()=>DMASH_RELEASE.id);report.sw=root?'BLOCKED':await (async()=>{await page.evaluate(()=>navigator.serviceWorker.ready);return context.serviceWorkers()[0].evaluate(()=>RELEASE_ID);})();
 const button=name=>page.getByRole('button',{name,exact:true});const click=async name=>button(name).click();const digits=async value=>{for(const d of value)await click(d);await click('=');};
 await page.getByText('УСТАНОВКА MASTER-КОДА',{exact:true}).waitFor();await digits('3333');await page.getByText('УСТАНОВКА WIPE-КОДА',{exact:true}).waitFor();await digits('9876');await page.getByText('СИСТЕМА ГОТОВА',{exact:true}).waitFor();await page.waitForTimeout(1300);await digits('3333');
 await page.locator('#p1').fill('qa-blockers-'+Date.now());await page.locator('#p2').fill('Synthetic-blockers-2026!');await click('ВОЙТИ');await page.getByText('Избранное',{exact:true}).waitFor({timeout:60000});
 await click('Настройки');await click('УЗЛЫ И ПОДКЛЮЧЕНИЕ');await click('ЗАПРОСИТЬ УЗЕЛ');await page.getByText('Подключено',{exact:true}).waitFor({timeout:60000});report.checks.push({id:'real-wss',status:'PASS',actual:'Requested real Node visibly connected; no DNSS readiness claim'});await click('QR');await page.locator('#node-qr-target canvas:visible, #node-qr-target img:visible').first().waitFor();await click('КОПИРОВАТЬ ССЫЛКУ');assert(await page.evaluate(()=>navigator.clipboard.readText().then(value=>value.includes('#/node/'))));report.checks.push({id:'NODE-QR-01',status:'PASS',actual:'Requested directory node renders canonical QR and copies node link'});await click('НАЗАД');await click('НАЗАД');await click('ЗАКРЫТЬ');
 await click('Настройки');await click('PUBLIC / PRIVATE QR');await click('PUBLIC');await click('СОЗДАТЬ PUBLIC ROUTE');await page.locator('#sys-modal').getByText('Public Routes ещё не созданы.',{exact:true}).waitFor();assert(await page.locator('#workspace').isVisible());await click('СОЗДАТЬ PUBLIC ROUTE');await page.locator('#sys-modal').getByText('CURRENT · ACTIVE',{exact:true}).waitFor();await click('НАЗАД');await page.locator('#sys-modal').getByText('PUBLIC / PRIVATE',{exact:true}).waitFor();report.checks.push({id:'UI-SHARE-CREATE',status:'PASS',actual:'Device-owned route panel visible in modal; create current route; Back returns QR; Account workspace preserved'});await click('ЗАКРЫТЬ');
 await click('Настройки');await click('УЗЛЫ И ПОДКЛЮЧЕНИЕ');
 await click('ДОБАВИТЬ ПО QR');await page.waitForTimeout(450);await click('ОТМЕНА');await page.getByRole('heading',{name:'ПОДКЛЮЧЕНИЕ К УЗЛУ',exact:true}).waitFor();report.checks.push({id:'scanner-denied-cancel',status:'PASS'});
 // Actual rapid clicks, followed by reopening: stale cleanup must not remove new reader.
 await click('ДОБАВИТЬ ПО QR');await click('ОТМЕНА');await page.getByRole('heading',{name:'ПОДКЛЮЧЕНИЕ К УЗЛУ',exact:true}).waitFor();await context.grantPermissions(['camera'],{origin:new URL(base).origin});await click('ДОБАВИТЬ ПО QR');await page.locator('#sys-modal video').waitFor();await page.waitForFunction(()=>document.querySelector('#sys-modal video')?.readyState>=2);await click('ОТМЕНА');await page.getByRole('heading',{name:'ПОДКЛЮЧЕНИЕ К УЗЛУ',exact:true}).waitFor();report.checks.push({id:'scanner-rapid-reopen-and-running-cancel',status:'PASS',actual:'Synthetic camera real MediaStream/Html5Qrcode; visible video before cancel'});

 // Fault injection delays only the real browser camera API completion. No fake stream/scanner.
 await page.evaluate(()=>{const original=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);window.__qaOriginalGum=original;window.__qaDelayedTracks=[];navigator.mediaDevices.getUserMedia=async options=>{const stream=await original(options);window.__qaDelayedTracks.push(...stream.getTracks());await new Promise(resolve=>setTimeout(resolve,900));return stream;};});
 await click('ДОБАВИТЬ ПО QR');await page.waitForFunction(()=>window.__qaDelayedTracks.length>0);await click('ОТМЕНА');await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=window.__qaOriginalGum;});await click('ДОБАВИТЬ ПО QR');await page.locator('#sys-modal video').waitFor();await page.waitForFunction(()=>document.querySelector('#sys-modal video')?.readyState>=2);await page.waitForTimeout(1200);assert(await page.locator('#sys-modal video').isVisible());await page.waitForFunction(()=>window.__qaDelayedTracks.every(track=>track.readyState==='ended'));await click('ОТМЕНА');report.checks.push({id:'scanner-delayed-real-camera-cancel-reopen',status:'PASS',actual:'Delayed real getUserMedia completion; old tracks ended; replacement scanner video remains visible'});
 await click('НАЗАД');await click('ЗАКРЫТЬ');await click('Настройки');await click('ЗАПРОСЫ В КОНТАКТЫ');await page.getByText('ЗАПРОСОВ НЕТ',{exact:true}).waitFor();assert.equal(await page.locator('#sys-modal').getByRole('button',{name:'НАЗАД',exact:true}).count(),1);await click('НАЗАД');await page.getByText('НАСТРОЙКИ АККАУНТА',{exact:true}).waitFor();await click('ЗАКРЫТЬ');report.checks.push({id:'UI-PUBLIC-ACCEPT-NAV',status:'PASS',actual:'Logged-in Account settings exposes root-owned pending; single Back returns Account settings; two-party handshake separate'});await click('[ ВЫХОД ]');await page.locator('#global-settings-button').click();await page.locator('[onclick="Core.openPendingContacts()"]').click();await page.getByText('ЗАПРОСОВ НЕТ',{exact:true}).waitFor();assert.equal(await page.locator('#sys-modal').getByRole('button',{name:'НАЗАД',exact:true}).count(),1);await page.locator('#sys-modal').getByRole('button',{name:'НАЗАД',exact:true}).click();assert.equal(await page.locator('#sys-modal').isVisible(),false);await page.getByText('ОБЩИЕ НАСТРОЙКИ',{exact:true}).waitFor();report.checks.push({id:'PENDING-BACK-01',status:'PASS',actual:'One Back button; closes modal and returns to global settings'});
 await page.locator('[onclick="ui.renderGlobalNodes()"]').click();await click('ЗАПРОСИТЬ ПУБЛИЧНУЮ NODE');await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>NodeManager.endpoints.length),1);assert.equal(await page.evaluate(()=>NodeManager.active.nodeId),JSON.parse(fs.readFileSync(path.join(root||'D-MASH PWA/not_messenger','nodes.json'),'utf8')).nodes[0].nodeId);report.checks.push({id:'global-node-request-pin',status:'PASS',actual:'Global request preserves validated catalog pin and deduplicates existing endpoint'});
 assert.deepEqual(report.errors,[]);report.status='PASS';
 }catch(e){report.status='FAIL';report.failure=e.message;process.exitCode=1;}finally{report.notLoaded=Object.keys(report.files).filter(file=>!report.servedFiles[file]);report.sourceConsistency=!root?'DEPLOYED_NOT_SOURCE_VERIFIED':Object.entries(report.files).filter(([file])=>report.servedFiles[file]).every(([file,hash])=>report.servedFiles[file].length===1&&report.servedFiles[file][0]===hash)?'MATCHED_SERVED_HASHES':'MIXED';await browser?.close();fs.writeFileSync(output,JSON.stringify(report,null,2));console.log(JSON.stringify(report));}})();
