'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require(process.env.DMASH_PLAYWRIGHT_MODULE||'/tmp/dmash-browser-tools/node_modules/playwright');
(async()=>{const root=path.resolve('D-MASH PWA/not_messenger'),names=['js/vendor/nacl-fast.min.js','js/storage.js','js/file_channel.js','js/call_signaling.js','js/recorded_note_turn.js'];const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');if(req.url==='/')res.end(names.map(x=>'<script src="/'+x+'"></script>').join(''));else{if(!names.includes(req.url.slice(1))){res.statusCode=404;res.end();return;}res.setHeader('Content-Type','application/javascript; charset=utf-8');res.end(fs.readFileSync(path.join(root,req.url.slice(1))));}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.DMASH_CHROME||'/home/jcode/.cache/ms-playwright/chromium-1248/chrome-linux64/chrome'});const p=await browser.newPage();
 const setup=async()=>{const state={};window.DeviceRoot={state,onLock:fn=>window.lockHook=fn};window.Core={keys:{sign:nacl.sign.keyPair.fromSeed(new Uint8Array(32).fill(7))},blindSalt:new Uint8Array(32).fill(8),activeIdentity:'synthetic',fastHash:async bytes=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join(''),withContactAccountV3:async(slot,fn)=>fn(),loadChat:async()=>{},renderPeers:async()=>{},refreshRecordedNoteState:()=>{},sendMessage:async payload=>{window.sent.push(payload);return true;}};window.sent=[];window.NodeManager={selectCallService:async()=>{throw Error('S-TURN service offline');}};await DMashStorage.initGamma(new Uint8Array(32).fill(9));window.runtime=new DmashRecordedNoteTurn(Core,DMashStorage);};
 try{await p.goto('http://127.0.0.1:'+server.address().port);await p.evaluate(setup);const first=await p.evaluate(async()=>{const peer='a'.repeat(64);for(let i=0;i<3;i++)await runtime.queue(peer,{type:'voice',data:'data:audio/webm;base64,'+btoa('synthetic'+i)});await runtime.flush();const rows=await runtime.rows(runtime.capture());return {count:rows.length,status:rows.map(r=>r.status),ids:rows.map(r=>r.id),sent:sent.length};});assert.equal(first.count,3);assert.equal(first.sent,0);assert(first.status.every(x=>x==='waiting'));
 await p.reload();await p.evaluate(setup);const reopened=await p.evaluate(async()=>{const rows=await runtime.rows(runtime.capture());await runtime.cancel(rows[0].id);const row=await runtime.row(runtime.capture(),rows[0].id);return {count:rows.length,id:row.id,status:row.status,retained:!!row.content,history:await DMashStorage.hasMessageWireId(row.peerID,row.id)};});assert.equal(reopened.count,3);assert.equal(reopened.status,'cancelled');assert(reopened.retained&&reopened.history);
 const retried=await p.evaluate(async id=>{await runtime.retry(id);await runtime.flush();const row=await runtime.row(runtime.capture(),id);const encrypted=await new Promise(resolve=>{const q=DMashStorage.db.transaction('blind_outbox').objectStore('blind_outbox').getAll();q.onsuccess=()=>resolve(q.result);});
 const crypt=runtime.crypt.bind(runtime);let entered,release;const reached=new Promise(r=>entered=r),gate=new Promise(r=>release=r);runtime.crypt=async(s,row)=>{const value=await crypt(s,row);if(row.record==='turn_note_v1'){entered();await gate;}return value;};
 const pending=runtime.queue('b'.repeat(64),{type:'voice',data:'data:audio/webm;base64,Yg=='}).then(()=>false,()=>true);await reached;const oldKey=DMashStorage.masterKey;DMashStorage.masterKey=await crypto.subtle.importKey('raw',new Uint8Array(32).fill(99),'AES-GCM',false,['encrypt','decrypt']);release();const switchRefused=await pending;DMashStorage.masterKey=oldKey;runtime.crypt=crypt;
 const after=await new Promise(resolve=>{const q=DMashStorage.db.transaction('blind_outbox').objectStore('blind_outbox').getAll();q.onsuccess=()=>resolve(q.result);});if(!switchRefused||JSON.stringify(after)!==JSON.stringify(encrypted))throw Error('Pending old Account write crossed captured vault');
 NodeManager.selectCallService=async()=> 'wss://stage-api-ems.d-mash.ru/signal/v1';
 const manifest=await DmashFileChannel.describe(new File(['abc'],'voice_msg',{type:'audio/webm'}),'c'.repeat(64));let foreignRefused=false,foreignError='';
 try{await runtime.receive({type:'voip_note_request',version:1,note_id:'d'.repeat(64),media_type:'voice',manifest,invitation:{call_id:manifest.id,expires_at:Math.floor(Date.now()/1000)+60,signaling:{wss_endpoint:'wss://untrusted.example/signal',session_id:'a'.repeat(43),one_time_key:'b'.repeat(43)}}},'a'.repeat(64),()=>true);}catch(e){foreignError=e.message;foreignRefused=e.message.includes('не совпадает');}
 if(!foreignRefused||runtime.tasks.size)throw Error('Foreign relay endpoint result '+JSON.stringify({foreignRefused,foreignError,tasks:runtime.tasks.size}));
 const peerSession=runtime.capture('a'.repeat(64));runtime.forgetPeer('a'.repeat(64));runtime.allowPeer('a'.repeat(64));if(peerSession.current())throw Error('Deleted peer session revived after re-add');runtime.capture('a'.repeat(64)).check();
 DeviceRoot.state=null;lockHook();let denied=false;try{await runtime.queue('a'.repeat(64),{type:'voice',data:'data:audio/webm;base64,YQ=='});}catch(_){denied=true;}return {status:row.status,retained:!!row.content,sent:sent.length,encryptedOnly:encrypted.every(r=>typeof r.blob==='string'&&!JSON.stringify(r).includes('synthetic')),denied,tasks:runtime.tasks.size};},reopened.id);assert.equal(retried.status,'waiting');assert(retried.retained&&retried.encryptedOnly&&retried.denied);assert.equal(retried.sent,0);assert.equal(retried.tasks,0);console.log(JSON.stringify({scope:'BROWSER real AES/IndexedDB offline store; stubbed service unavailable; no real TURN or UI claim',browser:browser.version(),sourceHashes:Object.fromEntries(names.map(name=>[name,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,name))).digest('hex')])),checks:{threeDurable:true,reload:true,cancelRetains:true,retry:true,noMediaNetworkOffline:true,encryptedAtRest:true,rootLock:true,pendingAccountSwitchNoWrite:true,foreignRelayRefused:true,peerDeleteRevokesOldGeneration:true}}));
 }finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
