'use strict';
// Local crypto/real IndexedDB dispatcher fixture, not a Node network/UI cutover.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.DMASH_PLAYWRIGHT_MODULE||'playwright');
const names=['vendor/nacl-fast.min.js','secure_session.js','route_discovery_v4.js','recipient_payload_v4.js','account_pairing_v2.js','account_route_binding_v2.js','node_inbox_v4.js','node_local_delivery_v4.js','node_local_ownership_v4.js','node_bootstrap_control_v4.js','node_bootstrap_dispatcher_v4.js'];
const sources=new Map(names.map(name=>['/js/'+name,fs.readFileSync(path.join(__dirname,'../D-MASH PWA/not_messenger/js',name))]));
(async()=>{const server=http.createServer((req,res)=>{res.setHeader('Content-Type',req.url==='/'?'text/html':'application/javascript');if(req.url==='/')res.end(names.map(n=>'<script src="/js/'+n+'"></script>').join(''));else if(sources.has(req.url))res.end(sources.get(req.url));else{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({executablePath:process.env.DMASH_CHROME,headless:true});const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.address().port+'/');
const result=await page.evaluate(async()=>{
 const now=Math.floor(Date.now()/1000),hex=b=>Array.from(b,x=>x.toString(16).padStart(2,'0')).join(''),rejects=async fn=>{try{await fn();return false;}catch(_){return true;}},pairing=DmashAccountPairingV2.createCodec({nacl,discovery:DmashRouteDiscoveryV4}),binding=DmashAccountRouteBindingV2.createBindingCodec({nacl,discovery:DmashRouteDiscoveryV4,pairing,clock:()=>now}),codec=DmashNodeBootstrapControlV4.createCodec({pairing,binding,clock:()=>now});
 const person=n=>({n,account:nacl.sign.keyPair(),box:nacl.box.keyPair(),route:nacl.sign.keyPair(),sign:nacl.sign.keyPair(),discovery:nacl.box.keyPair(),recipient:nacl.box.keyPair()});const a=person(1),b=person(2);
 const bundle=(p,target=null)=>pairing.sign({type:'DMASH_PAIRING_V2',version:2,transport_version:4,pairing_id:hex(crypto.getRandomValues(new Uint8Array(32))),generation:1,issued_at:now,expires_at:now+1800,previous_binding:null,intended_peer:target,contribution:hex(crypto.getRandomValues(new Uint8Array(32))),account_keys:{signing:hex(p.account.publicKey),box:hex(p.box.publicKey),kem_profile:'LEGACY_KYBER768_BUNDLE_V1',kem_public:btoa(String.fromCharCode(...new Uint8Array(1184).fill(p.n))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')},inbound_certificate:DmashRouteDiscoveryV4.issueCertificate(p.route,p.sign.publicKey,p.discovery.publicKey,p.recipient.publicKey,{generation:1,issuedAt:now,expiresAt:now+3600})},p.account.secretKey,{now,localAccount:target??undefined}).serialized;
 const ab=bundle(a),bb=bundle(b,hex(a.account.publicKey)),people=[a,b].sort((x,y)=>hex(x.account.publicKey).localeCompare(hex(y.account.publicKey))),candidate=await binding.prepare([ab,bb],{expectedParticipants:people.map(p=>hex(p.account.publicKey)),committed:null}),accept=binding.signReceipt(candidate,'ACCEPT',people[0].account.secretKey),confirm=binding.signReceipt(candidate,'CONFIRM',people[1].account.secretKey,accept);
 const authorityInbox=await DmashNodeInboxV4.open(new Uint8Array(32).fill(31),'a'.repeat(64),{databaseName:'bootstrap-fixture-authority'}),local=new DmashNodeLocalDeliveryV4({},authorityInbox),ownership=new DmashNodeLocalOwnershipV4(local,authorityInbox),challenge=await ownership.challenge(hex(a.account.publicKey),JSON.parse(ab).inbound_certificate),owner=await ownership.register(challenge.challenge,nacl.sign.detached(new TextEncoder().encode(challenge.transcript),a.account.secretKey));
 const open=()=>DmashNodeInboxV4.open(new Uint8Array(32).fill(32),'a'.repeat(64),{databaseName:'bootstrap-fixture-controls',maxRecords:96,maxBytes:1024*1024});
 let inbox=await open(),dispatcher=new DmashNodeBootstrapDispatcherV4({ownership,inbox,codec,clock:()=>now});await dispatcher.register(owner.token,ab);
 const wire=await codec.request(ab,bb,'a'.repeat(64),b.account.secretKey,{acceptReceipt:people[0]===b?accept:null}),pending=await dispatcher.request(owner.token,wire),notSelected=await rejects(()=>dispatcher.receipt(owner.token,'a'.repeat(64),accept));
 await dispatcher.select(owner.token,'a'.repeat(64),pending.requestDigest);await dispatcher.receipt(owner.token,'a'.repeat(64),accept);await dispatcher.receipt(owner.token,'a'.repeat(64),confirm);
 const duplicate=(await dispatcher.receipt(owner.token,'a'.repeat(64),confirm)).duplicate,neverActivated=local.bindings.size===0;
 const stored=await inbox.store.all(),encrypted=stored.every(row=>!JSON.stringify(row).includes('NODE_BOOTSTRAP_REQUEST_V4'));
 dispatcher.close();inbox=await open();dispatcher=new DmashNodeBootstrapDispatcherV4({ownership,inbox,codec,clock:()=>now});const records=await dispatcher.list(owner.token),persisted=records.length===1&&records[0].state==='SELECTED'&&Object.keys(records[0].receipts).length===2;
 const replay=(await dispatcher.request(owner.token,wire)).duplicate,userPayloadDenied=await rejects(()=>dispatcher.receipt(owner.token,'a'.repeat(64),'hello user message'));
 const foreignDenied=await rejects(()=>dispatcher.list('other-account'));
 dispatcher.close();ownership.close();local.close();authorityInbox.close();return {notSelected,duplicate,neverActivated,encrypted,persisted,replay,userPayloadDenied,foreignDenied};
});for(const [key,value]of Object.entries(result))assert.equal(value,true,key);console.log('PASS real IndexedDB bootstrap control journal: signed second-bundle request, explicit selection, receipts only, exact retries, encrypted reopen, foreign owner denied; no Worker/network/UI activation');
}finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
