'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.DMASH_PLAYWRIGHT_MODULE||'playwright');
const names=['vendor/nacl-fast.min.js','vendor/kyber768.js','vendor/kyber768.wasm','account_static_kem_v1.js'];
const sources=new Map(names.map(n=>['/js/'+n,fs.readFileSync(path.join(__dirname,'../D-MASH PWA/not_messenger/js',n))]));
(async()=>{const server=http.createServer((req,res)=>{res.setHeader('Content-Type',req.url.endsWith('.wasm')?'application/wasm':'text/html');if(req.url==='/')res.end(names.filter(n=>n.endsWith('.js')).map(n=>`<script src="/js/${n}"></script>`).join(''));else if(sources.has(req.url)){res.setHeader('Content-Type',req.url.endsWith('.wasm')?'application/wasm':'application/javascript');res.end(sources.get(req.url));}else{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({executablePath:process.env.DMASH_CHROME,headless:true});const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.address().port+'/');await page.waitForFunction(()=>!!window.KyberModule?._wasm_keypair);
const result=await page.evaluate(async()=>{
 const Store=DmashAccountStaticKemV1,wasm=Store.wasmAdapter(KyberModule),equal=(a,b)=>a.length===b.length&&a.every((x,i)=>x===b[i]);
 const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('isolated-account-kem-fixture',1);r.onupgradeneeded=()=>r.result.createObjectStore('pairing_material',{keyPath:'alias'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
 const masterKey=await crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt']),rootState={},blindSalt=crypto.getRandomValues(new Uint8Array(32)),a=nacl.sign.keyPair(),b=nacl.sign.keyPair(),legacy=wasm.generateKeys(),legacyCopy=legacy.sk.slice();let active;
 function session(sign,generation){const controller=new AbortController(),value={keys:{sign},db,masterKey,blindSalt,rootState,generation,signal:controller.signal,assertCurrent(){if(active!==value||controller.signal.aborted)throw Error('STALE');}};active=value;return {value,controller};}
 const sa=session(a,1),ka=await Store.open({session:sa.value}),pair=await Promise.all([ka.createExplicit(),ka.createExplicit()]);if(!equal(pair[0].publicKey,pair[1].publicKey))throw Error('Concurrent create changed material');const publicA=pair[0].publicKey.slice();ka.release(pair[1]);
 for(let i=0;i<40;i++){const handle=await ka.load();if(!ka.release(handle)||handle.secretKey.some(x=>x))throw Error('Release failed');}
 const held=[];for(let i=0;i<31;i++)held.push(await ka.load());let quota=false;try{await ka.load();}catch(error){quota=error.code==='ACCOUNT_KEM_HANDLE_QUOTA';}if(!quota)throw Error('Handle quota bypass');for(const h of held)ka.release(h);
 sa.controller.abort();if(pair[0].secretKey.some(x=>x))throw Error('Abort retained secret');
 const sb=session(b,1),kb=await Store.open({session:sb.value}),mb=await kb.createExplicit();const publicB=mb.publicKey.slice();if(equal(publicA,publicB))throw Error('Shared Account KEM');sb.controller.abort();
 const reopened=session(a,2),again=await Store.open({session:reopened.value}),ma=await again.load();if(!equal(ma.publicKey,publicA)||ma.createdSessionGeneration!==1)throw Error('Reopen changed KEM');
 const encapsulated=wasm.encapsulate(ma.publicKey),decapsulated=wasm.decapsulate(encapsulated.ct,ma.secretKey);if(!equal(encapsulated.ss,decapsulated.ss))throw Error('Real KEM mismatch');encapsulated.ss.fill(0);decapsulated.ss.fill(0);again.close();
 // Stale async decrypt must zero the result even before assigning it to a handle.
 let exposedPlain;const guardedCrypto={subtle:{importKey:(...args)=>crypto.subtle.importKey(...args),sign:(...args)=>crypto.subtle.sign(...args),decrypt:async(...args)=>{exposedPlain=await crypto.subtle.decrypt(...args);reopened.controller.abort();return exposedPlain;}}};
 const late=await Store.open({session:reopened.value,crypto:guardedCrypto});let staleDenied=false;try{await late.load();}catch(_){staleDenied=true;}if(!staleDenied||new Uint8Array(exposedPlain).some(x=>x))throw Error('Stale decrypt retained plaintext');late.close();
 let generated;const sc=session(nacl.sign.keyPair(),1),failing=await Store.open({session:sc.value,kem:{...wasm,generateKeys(){generated=wasm.generateKeys();generated.success=false;return generated;}}});let failed=false;try{await failing.createExplicit();}catch(_){failed=true;}if(!failed||generated.sk.some(x=>x))throw Error('Failed generation retained key');failing.close();sc.controller.abort();
 const finalSession=session(a,3);
 // Corruption must fail closed; explicit creation may not overwrite existing row.
 const rows=await new Promise((resolve,reject)=>{const tx=db.transaction('pairing_material','readonly'),request=tx.objectStore('pairing_material').getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
 await new Promise((resolve,reject)=>{const tx=db.transaction('pairing_material','readwrite');for(const row of rows){const bytes=Uint8Array.from(atob(row.blob),c=>c.charCodeAt(0));bytes[bytes.length-1]^=1;tx.objectStore('pairing_material').put({...row,blob:btoa(String.fromCharCode(...bytes))});}tx.oncomplete=resolve;tx.onabort=()=>reject(tx.error);});
 const corrupted=await Store.open({session:finalSession.value});let denied=0;for(const action of ['load','createExplicit'])try{await corrupted[action]();}catch(error){if(error.code==='ACCOUNT_KEM_CORRUPT')denied++;else throw error;}if(denied!==2)throw Error('Corrupt material regenerated');corrupted.close();
 const legacyPreserved=equal(legacy.sk,legacyCopy);legacy.sk.fill(0);legacyCopy.fill(0);db.close();return {distinctSameRootAccounts:true,reopenSameMaterial:true,concurrentCreateSameMaterial:true,releaseAndAbortZeroed:true,staleDecryptAndFailedGenerationZeroed:true,realKyberRoundTrip:true,corruptFailClosed:true,legacyPreserved};
});for(const value of Object.values(result))assert.equal(value,true);console.log(JSON.stringify({result:'PASS',scope:'real WASM/IndexedDB with synthetic Account session guards; no ordinary UI or Node transport claim',checks:result}));
}finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(error=>{console.error(error.message);process.exitCode=1;});
