'use strict';
// Real Worker/Python public control transport; not ordinary UI/final Account cutover.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{spawn}=require('node:child_process'),assert=require('node:assert/strict');
const {chromium}=require(process.env.DMASH_PLAYWRIGHT_MODULE||'playwright');
const names=['vendor/nacl-fast.min.js','secure_session.js','route_discovery_v4.js','recipient_payload_v4.js','account_pairing_v2.js','account_route_binding_v2.js','node_inbox_v4.js','node_local_delivery_v4.js','node_local_ownership_v4.js','node_bootstrap_control_v4.js','node_bootstrap_dispatcher_v4.js','node_bootstrap_runtime_v4.js','vendor/blake3.min.js','vendor/argon2-bundled.min.js','device_root.js','node_identity.js','node_runtime_host_v4.js','node_public_bootstrap_control_v4.js','node_public_bootstrap_runtime_v4.js'];
const extra=['node_runtime_worker_v4.js','node_relationships_v4.js','node_admission_v4.js','node_registration_v4.js','resource_pow.js','node_socket_v4.js','node_channel_v4.js','probe_primitives_v4.js','node_routing_v4.js','vendor/argon2.wasm'];
const sources=new Map([...names,...extra].map(name=>['/js/'+name,fs.readFileSync(path.join(__dirname,'../D-MASH PWA/not_messenger/js',name))]));
async function poll(page,predicate,arg,{timeout=30000}={}){const until=Date.now()+timeout;for(;;){const result=await page.evaluate(predicate,arg);if(result)return result;if(Date.now()>=until)throw Error('Public fixture predicate timeout');await new Promise(resolve=>setTimeout(resolve,100));}}
(async()=>{
 const server=http.createServer((req,res)=>{res.setHeader('Content-Type',req.url==='/'?'text/html':req.url.endsWith('.wasm')?'application/wasm':'application/javascript');if(req.url==='/')res.end(names.map(n=>'<script src="/js/'+n+'"></script>').join(''));else if(sources.has(req.url))res.end(sources.get(req.url));else{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const helper=spawn(path.join(__dirname,'../.venv/bin/python'),[path.join(__dirname,'node_bootstrap_browser_server.py')]);let buffer='';const nodeReady=new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Native Node startup timeout')),240000);helper.stdout.on('data',chunk=>{buffer+=chunk;if(buffer.includes('\n')){clearTimeout(timer);resolve(JSON.parse(buffer.slice(0,buffer.indexOf('\n'))));}});helper.once('exit',code=>{if(!buffer){clearTimeout(timer);reject(Error('Native Node exited '+code));}});});helper.stderr.on('data',()=>{});let browser;
 try{
  const node=await nodeReady;console.log('stage native Node ready');browser=await chromium.launch({executablePath:process.env.DMASH_CHROME,headless:true});const pages=[];
  for(let i=0;i<2;i++){const context=await browser.newContext(),page=await context.newPage();pages.push(page);await page.goto('http://127.0.0.1:'+server.address().port+'/');await page.evaluate(async({node,index})=>{
   await DeviceRoot.unlock('PublicBootstrap-fixture-'+index);const host=await DmashNodeRuntimeHostV4.startForDevice(DeviceRoot,{localOwnership:'managed',bootstrapProfile:'public-v1'});await host.connect({url:'ws://127.0.0.1:'+node.port+'/mesh/v4',nodeId:node.nodeId});
   const registration=await host.registerPublicBootstrap({kind:index===0?'PUBLIC_INTAKE':'PUBLIC_REPLY',expiresAt:Math.floor(Date.now()/1000)+3600});window.fixture={host,registration,index,nodeId:host.identity.nodeId};
  },{node,index:i});}
  console.log('stage both browser roots connected');const [a,b]=pages,target=await a.evaluate(()=>fixture.registration.certificate);
  const submitted=await b.evaluate(async certificate=>fixture.host.sendPublicRequest(fixture.registration.capability,certificate,{requestId:'a'.repeat(64),displayName:'Neutral stranger',introduction:'Request without any Account',nonce:'b'.repeat(64)}),target);
  await poll(a,async()=>((await fixture.host.publicRequests(fixture.registration.capability)).length===1),null,{timeout:30000});
  const neutral=await a.evaluate(async()=>{const samples=[];for(let i=0;i<3;i++){const records=await fixture.host.publicRequests(fixture.registration.capability);samples.push({count:records.length,states:records.map(r=>r.state),neutral:records[0]?.state==='PENDING'&&records[0]?.claim===null&&!JSON.stringify(records).includes('account_keys')});}return samples;});console.log(JSON.stringify({stage:'neutral-intake-repeat',samples:neutral}));assert.ok(neutral.every(row=>row.neutral));
  for(const page of pages)await page.evaluate(()=>{
   const hex=b=>Array.from(b,x=>x.toString(16).padStart(2,'0')).join(''),now=Math.floor(Date.now()/1000),keys={account:nacl.sign.keyPair(),box:nacl.box.keyPair(),route:nacl.sign.keyPair(),sign:nacl.sign.keyPair(),discovery:nacl.box.keyPair(),recipient:nacl.box.keyPair()};
   const pairing=DmashAccountPairingV2.createCodec({nacl,discovery:DmashRouteDiscoveryV4}),binding=DmashAccountRouteBindingV2.createBindingCodec({nacl,discovery:DmashRouteDiscoveryV4,pairing}),codec=DmashNodePublicBootstrapControlV4.createCodec({pairing,binding});
   Object.assign(fixture,{hex,now,keys,pairing,binding,codec,controller:new AbortController()});
   fixture.makeBundle=target=>pairing.sign({type:'DMASH_PAIRING_V2',version:2,transport_version:4,pairing_id:hex(crypto.getRandomValues(new Uint8Array(32))),generation:1,issued_at:now,expires_at:now+1800,previous_binding:null,intended_peer:target,contribution:hex(crypto.getRandomValues(new Uint8Array(32))),account_keys:{signing:hex(keys.account.publicKey),box:hex(keys.box.publicKey),kem_profile:'LEGACY_KYBER768_BUNDLE_V1',kem_public:btoa(String.fromCharCode(...new Uint8Array(1184).fill(fixture.index+1))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')},inbound_certificate:DmashRouteDiscoveryV4.issueCertificate(keys.route,keys.sign.publicKey,keys.discovery.publicKey,keys.recipient.publicKey,{generation:1,issuedAt:now,expiresAt:now+3600})},keys.account.secretKey,{now,localAccount:target??undefined}).serialized;
   fixture.registerOwner=async bundle=>{const challenge=await fixture.host.challengeLocalOwner(hex(keys.account.publicKey),JSON.parse(bundle).inbound_certificate);fixture.owner=await fixture.host.registerLocalOwner(challenge.challenge,nacl.sign.detached(new TextEncoder().encode(challenge.transcript),keys.account.secretKey),{accountPublic:hex(keys.account.publicKey),isAccountCurrent:()=>true,signal:fixture.controller.signal});};
  });
  await a.evaluate(async()=>{
   const f=fixture,row=(await f.host.publicRequests(f.registration.capability))[0];f.bundle=f.makeBundle(null);await f.registerOwner(f.bundle);const claim=await f.host.claimPublicRequest(f.registration.capability,f.owner,row.requestId,row.requestDigest,f.bundle),request=await f.codec.inspectRequest(f.registration.certificate,row.request);f.accept=await f.codec.accept(request,{bundle:f.bundle,bootstrapBox:claim.bootstrapBox},f.keys.account.secretKey);await f.host.submitPublicControl(f.registration.capability,f.owner,row.requestId,'ACCEPT',f.accept);
  });
  await poll(b,async()=>(await fixture.host.publicRequests(fixture.registration.capability))[0].state==='CANDIDATE',null,{timeout:30000});
  await b.evaluate(async()=>{
   const f=fixture,row=(await f.host.publicRequests(f.registration.capability))[0],request=await f.codec.inspectRequest(row.targetCertificate,row.request),accepted=await f.codec.inspectAccept(request,row.accept);f.bundle=f.makeBundle(accepted.accountPublic);await f.registerOwner(f.bundle);f.candidate=await f.binding.prepare([JSON.parse(row.accept).bundle,f.bundle],{expectedParticipants:[accepted.accountPublic,f.hex(f.keys.account.publicKey)],committed:null});const lower=f.hex(f.keys.account.publicKey)<accepted.accountPublic;f.initial=lower?f.binding.signReceipt(f.candidate,'ACCEPT',f.keys.account.secretKey):null;f.confirm=await f.codec.confirm(accepted,{bundle:f.bundle,acceptReceipt:f.initial},f.keys.account.secretKey);await f.host.submitPublicControl(f.registration.capability,f.owner,row.requestId,'CONFIRM',f.confirm);
  });
  await poll(a,async()=>(await fixture.host.publicRequests(fixture.registration.capability))[0].state==='CONFIRMED',null,{timeout:30000});
  await a.evaluate(async()=>{
   const f=fixture,row=(await f.host.publicRequests(f.registration.capability))[0],remote=JSON.parse(JSON.parse(row.confirm).bundle).account_keys.signing;f.candidate=await f.binding.prepare([f.bundle,JSON.parse(row.confirm).bundle],{expectedParticipants:[f.hex(f.keys.account.publicKey),remote],committed:null});const phase=f.hex(f.keys.account.publicKey)<remote?'ACCEPT':'CONFIRM',receipt=f.binding.signReceipt(f.candidate,phase,f.keys.account.secretKey,row.receipts.ACCEPT);await f.host.submitPublicControl(f.registration.capability,f.owner,row.requestId,'RECEIPT',receipt);
  });
  await poll(b,async()=>Object.keys((await fixture.host.publicRequests(fixture.registration.capability))[0].receipts).length>=1,null,{timeout:30000});
  await b.evaluate(async()=>{const f=fixture;for(let n=0;n<100;n++){const row=(await f.host.publicRequests(f.registration.capability))[0];if(f.initial?row.receipts.CONFIRM:row.receipts.ACCEPT){if(!f.initial){const receipt=f.binding.signReceipt(f.candidate,'CONFIRM',f.keys.account.secretKey,row.receipts.ACCEPT);await f.host.submitPublicControl(f.registration.capability,f.owner,row.requestId,'RECEIPT',receipt);}return;}await new Promise(r=>setTimeout(r,50));}throw Error('Public remote receipt missing');});
  await poll(a,async()=>Object.keys((await fixture.host.publicRequests(fixture.registration.capability))[0].receipts).length===2,null,{timeout:30000});
  for(const page of pages){const checks=await page.evaluate(async()=>{const f=fixture,row=(await f.host.publicRequests(f.registration.capability))[0],stat=await f.host.stats(),noSecrets=!JSON.stringify(row).includes('bootstrapKey'),receipts=Object.keys(row.receipts).length===2,rootNeutral=row.kind==='public-request'&&row.state==='CONFIRMED';f.controller.abort();return {noSecrets,receipts,rootNeutral,owned:stat.owned};});assert.equal(checks.noSecrets,true);assert.equal(checks.receipts,true);assert.equal(checks.rootNeutral,true);assert.equal(checks.owned,1);}
  await a.evaluate(async()=>{const f=fixture;DeviceRoot.lock();const deadline=Date.now()+5000;while((await navigator.locks.query()).held.some(x=>x.name==='dmash-node-runtime-v4')){if(Date.now()>deadline)throw Error('Node lock retained');await new Promise(r=>setTimeout(r,25));}await DeviceRoot.unlock('PublicBootstrap-fixture-0');f.host=await DmashNodeRuntimeHostV4.startForDevice(DeviceRoot,{localOwnership:'managed',bootstrapProfile:'public-v1'});f.registration=await f.host.registerPublicBootstrap({id:f.registration.id});const row=(await f.host.publicRequests(f.registration.capability))[0];if(row.state!=='CONFIRMED'||Object.keys(row.receipts).length!==2||f.host.identity.nodeId!==f.nodeId)throw Error('Public root restore mismatch');});
  console.log('PASS real Worker↔Python Node↔Worker public neutral REQUEST without Account; genuine Account claim/ACCEPT/CONFIRM and bilateral receipts; root journal retained/reopened, no final ACTIVE/user inbox/ordinary UI claim');
 }finally{helper.stdin.write(JSON.stringify({type:'STOP'})+'\n');helper.stdin.end();await browser?.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
