'use strict';
// Real Chromium/IndexedDB/crypto mechanism fixture. NOT ordinary UI or Node transport.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require(process.env.DMASH_PLAYWRIGHT_MODULE||'playwright');
const scripts=['vendor/nacl-fast.min.js','route_discovery_v4.js','account_handshake_v4.js','account_session_v4.js','account_session_store_v4.js'];
const files=new Map(scripts.map(n=>['/js/'+n,fs.readFileSync(path.join(__dirname,'../D-MASH PWA/not_messenger/js',n))]));
(async()=>{const server=http.createServer((req,res)=>{if(req.url==='/'){res.setHeader('Content-Type','text/html');res.end(scripts.map(n=>'<script src="/js/'+n+'"></script>').join(''));}else if(files.has(req.url)){res.setHeader('Content-Type','application/javascript');res.end(files.get(req.url));}else{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({headless:true,executablePath:process.env.DMASH_CHROME});const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.address().port+'/');
const result=await page.evaluate(async()=>{
 const assert=(v,m)=>{if(!v)throw Error(m);},rejects=async(fn,code)=>{try{await fn();return false;}catch(e){if(code&&e.code!==code)throw e;return true;}};
 const db=await new Promise((resolve,reject)=>{const q=indexedDB.open('synthetic-account-session-fixture',1);q.onupgradeneeded=()=>{q.result.createObjectStore('pairing_material',{keyPath:'alias'});q.result.createObjectStore('blind_messages',{keyPath:'alias'});};q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});
 const make=async(n=1,customCrypto=crypto)=>{const signal=new AbortController(),context={local:n.toString(16).padStart(64,'0'),peer:'22'.repeat(32),bindingDigest:'33'.repeat(32),bindingGeneration:1,requiredSuite:DmashAccountHandshakeV4.SUITE},owner={context:()=>context,assertCurrent(){if(signal.signal.aborted)throw Error('STALE_OWNER');}},dataKey=await crypto.subtle.importKey('raw',new Uint8Array(32).fill(n),'AES-GCM',false,['encrypt','decrypt']),blindKey=await crypto.subtle.importKey('raw',new Uint8Array(32).fill(n+40),{name:'HMAC',hash:'SHA-256'},false,['sign']),options={db,dataKey,blindKey,owner,signal:signal.signal,crypto:customCrypto};return {store:await DmashAccountSessionStoreV4.open(options),options,signal};};
 const raw=()=>new Promise((resolve,reject)=>{const tx=db.transaction('pairing_material'),r=tx.objectStore('pairing_material').getAll();r.onsuccess=()=>resolve(r.result);tx.onabort=()=>reject(tx.error);});
 const change=(alias,row)=>new Promise((resolve,reject)=>{const tx=db.transaction('pairing_material','readwrite'),s=tx.objectStore('pairing_material');if(row)s.put(row);else s.delete(alias);tx.oncomplete=resolve;tx.onabort=()=>reject(tx.error);});
 const value={version:4,ledger:{session_id:'aa'.repeat(32),generation:1},confirmed:{session_id:'aa'.repeat(32),generation:1,root:'bb'.repeat(32)},pending:null,recovery:{role:'authority',consumed:true,ticket:'cc'.repeat(32)},retired:[],intents:[],superseded:[]};
 const a=await make();let snap=await a.store.load();assert(snap.value===null,'new nonempty');await a.store.commit(snap.revision,value,()=>{});a.store.close();a.store=await DmashAccountSessionStoreV4.open(a.options);assert((await a.store.load()).value.confirmed.root===value.confirmed.root,'reopen root');
 const baseline=JSON.stringify(await raw()),nativePut=IDBObjectStore.prototype.put;
 const faults=[];for(let at=1;at<=3;at++){let writes=0;IDBObjectStore.prototype.put=function(...args){const r=nativePut.apply(this,args);if(this.name==='pairing_material'&&++writes===at)this.transaction.abort();return r;};try{snap=await a.store.load();faults.push(await rejects(()=>a.store.commit(snap.revision,{...value,intents:[{raw:'synthetic'}]},()=>{})));}finally{IDBObjectStore.prototype.put=nativePut;}assert(JSON.stringify(await raw())===baseline,'torn transaction '+at);}
 const first=await a.store.load(),second=await a.store.load();await a.store.commit(first.revision,value,()=>{});const conflict=await rejects(()=>a.store.commit(second.revision,value,()=>{}),'SESSION_CONFLICT');
 const beforeLoss=await raw(),stateRow=beforeLoss.find(r=>r.alias===a.store.aliases.state);await change(stateRow.alias,null);const lost=await a.store.load();assert(lost.value.confirmed===null&&lost.value.ledger.session_id===value.ledger.session_id&&lost.value.recovery.consumed,'ledger/ticket lost with session');await change(stateRow.alias,stateRow);
 await change(stateRow.alias,{...stateRow,blob:'AAAA'});const corrupt=await rejects(()=>a.store.load(),'CORRUPT_SESSION');await change(stateRow.alias,stateRow);
 const b=await make(2),bs=await b.store.load();assert(bs.value===null,'other Account inherited');await b.store.commit(bs.revision,{...value,confirmed:{...value.confirmed,root:'dd'.repeat(32)}},()=>{});assert((await a.store.load()).value.confirmed.root===value.confirmed.root,'other Account overwrote');
 const rows=JSON.stringify(await raw());assert(!rows.includes(value.confirmed.root)&&!rows.includes(value.ledger.session_id),'plaintext leaked');
 const changedContext={...a.options.owner.context(),bindingDigest:'99'.repeat(32),bindingGeneration:2},changedOwner={...a.options.owner,context:()=>changedContext},changed=await DmashAccountSessionStoreV4.open({...a.options,owner:changedOwner});const migration=await rejects(()=>changed.load(),'BINDING_MIGRATION_REQUIRED');assert(changed.aliases.ledger!==a.store.aliases.ledger&&changed.aliases.state!==a.store.aliases.state,'binding missing from aliases');changed.close();assert((await a.store.load()).value.confirmed.root===value.confirmed.root,'migration reset old state');
 const beforeAbort=JSON.stringify(await raw());snap=await a.store.load();IDBObjectStore.prototype.put=function(...args){const r=nativePut.apply(this,args);if(this.name==='pairing_material')a.signal.abort();return r;};let aborted;try{aborted=await rejects(()=>a.store.commit(snap.revision,value,()=>{}));}finally{IDBObjectStore.prototype.put=nativePut;}assert(JSON.stringify(await raw())===beforeAbort,'abort wrote data');
 let entered,release;const gate=new Promise(r=>entered=r),wrapped={getRandomValues:crypto.getRandomValues.bind(crypto),subtle:{sign:crypto.subtle.sign.bind(crypto.subtle),decrypt:crypto.subtle.decrypt.bind(crypto.subtle),encrypt:async(...args)=>{entered();await new Promise(r=>release=r);return crypto.subtle.encrypt(...args);}}},c=await make(3,wrapped),cs=await c.store.load(),pending=c.store.commit(cs.revision,value,()=>{});await gate;c.signal.abort();release();const late=await rejects(()=>pending);assert(JSON.stringify(await raw())===beforeAbort,'late crypto wrote');
 b.store.close();c.store.close();db.close();return {reopen:true,faults,conflict,targetedLoss:true,corrupt,isolation:true,encrypted:true,migration,aborted,late};
});for(const [k,v]of Object.entries(result))assert(Array.isArray(v)?v.every(Boolean):v,k);console.log(JSON.stringify({kind:'BROWSER mechanism only; no ordinary UI/Node transport',browser:await browser.version(),result}));
}finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
