'use strict';
// Local crypto/real IndexedDB dispatcher fixture, not a Node network/UI cutover.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{spawn}=require('node:child_process'),assert=require('node:assert/strict');
const {chromium}=require(process.env.DMASH_PLAYWRIGHT_MODULE||'playwright');
const names=['vendor/nacl-fast.min.js','secure_session.js','route_discovery_v4.js','recipient_payload_v4.js','account_pairing_v2.js','account_route_binding_v2.js','node_inbox_v4.js','node_local_delivery_v4.js','node_local_ownership_v4.js','node_bootstrap_control_v4.js','node_bootstrap_dispatcher_v4.js','node_bootstrap_runtime_v4.js','vendor/blake3.min.js','vendor/argon2-bundled.min.js','device_root.js','node_identity.js','node_runtime_host_v4.js'];
const extra=['node_runtime_worker_v4.js','node_relationships_v4.js','node_admission_v4.js','node_registration_v4.js','resource_pow.js','node_socket_v4.js','node_channel_v4.js','probe_primitives_v4.js','node_routing_v4.js','vendor/argon2.wasm'];
const sources=new Map([...names,...extra].map(name=>['/js/'+name,fs.readFileSync(path.join(__dirname,'../D-MASH PWA/not_messenger/js',name))]));
(async()=>{const server=http.createServer((req,res)=>{res.setHeader('Content-Type',req.url==='/'?'text/html':req.url.endsWith('.wasm')?'application/wasm':'application/javascript');if(req.url==='/')res.end(names.map(n=>'<script src="/js/'+n+'"></script>').join(''));else if(sources.has(req.url))res.end(sources.get(req.url));else{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
const helper=spawn(path.join(__dirname,'../.venv/bin/python'),[path.join(__dirname,'node_bootstrap_browser_server.py')]);let buffer='',waiting=[],queued=[];helper.stderr.on('data',()=>{});helper.stdout.on('data',chunk=>{buffer+=chunk;while(buffer.includes('\n')){const i=buffer.indexOf('\n'),v=JSON.parse(buffer.slice(0,i));buffer=buffer.slice(i+1);if(waiting.length)waiting.shift()(v);else queued.push(v);}});const next=()=>queued.length?Promise.resolve(queued.shift()):new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Python fixture timeout')),240000);waiting.push(v=>{clearTimeout(timer);resolve(v);});});
try{const node=await next();browser=await chromium.launch({executablePath:process.env.DMASH_CHROME,headless:true});const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.address().port+'/');
await page.exposeFunction('sendNative',async(certificate,payload)=>{helper.stdin.write(JSON.stringify({type:'SEND',certificate,payload})+'\n');const result=await next();if(!result.queued)throw Error('Native send failed');});
const result=await page.evaluate(async node=>{
 const now=Math.floor(Date.now()/1000),hex=b=>Array.from(b,x=>x.toString(16).padStart(2,'0')).join(''),rejects=async fn=>{try{await fn();return false;}catch(_){return true;}},pairing=DmashAccountPairingV2.createCodec({nacl,discovery:DmashRouteDiscoveryV4}),binding=DmashAccountRouteBindingV2.createBindingCodec({nacl,discovery:DmashRouteDiscoveryV4,pairing,clock:()=>now}),codec=DmashNodeBootstrapControlV4.createCodec({pairing,binding,clock:()=>now});
 const person=n=>({n,account:nacl.sign.keyPair(),box:nacl.box.keyPair(),route:nacl.sign.keyPair(),sign:nacl.sign.keyPair(),discovery:nacl.box.keyPair(),recipient:nacl.box.keyPair()});const a=person(1),b=person(2);
 const bundle=(p,target=null)=>pairing.sign({type:'DMASH_PAIRING_V2',version:2,transport_version:4,pairing_id:hex(crypto.getRandomValues(new Uint8Array(32))),generation:1,issued_at:now,expires_at:now+1800,previous_binding:null,intended_peer:target,contribution:hex(crypto.getRandomValues(new Uint8Array(32))),account_keys:{signing:hex(p.account.publicKey),box:hex(p.box.publicKey),kem_profile:'LEGACY_KYBER768_BUNDLE_V1',kem_public:btoa(String.fromCharCode(...new Uint8Array(1184).fill(p.n))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')},inbound_certificate:DmashRouteDiscoveryV4.issueCertificate(p.route,p.sign.publicKey,p.discovery.publicKey,p.recipient.publicKey,{generation:1,issuedAt:now,expiresAt:now+3600})},p.account.secretKey,{now,localAccount:target??undefined}).serialized;
 const ab=bundle(a),bb=bundle(b,hex(a.account.publicKey)),people=[a,b].sort((x,y)=>hex(x.account.publicKey).localeCompare(hex(y.account.publicKey))),candidate=await binding.prepare([ab,bb],{expectedParticipants:people.map(p=>hex(p.account.publicKey)),committed:null}),accept=binding.signReceipt(candidate,'ACCEPT',people[0].account.secretKey),confirm=binding.signReceipt(candidate,'CONFIRM',people[1].account.secretKey,accept);
 await DeviceRoot.unlock('BootstrapWorker-fixture-only');let host=await DmashNodeRuntimeHostV4.startForDevice(DeviceRoot,{localOwnership:'managed',bootstrapProfile:'private-v1'});const identity=host.identity.nodeId;
 const certificate=JSON.parse(ab).inbound_certificate;let controller=new AbortController();
 async function register(){const challenge=await host.challengeLocalOwner(hex(a.account.publicKey),certificate);return host.registerLocalOwner(challenge.challenge,nacl.sign.detached(new TextEncoder().encode(challenge.transcript),a.account.secretKey),{accountPublic:hex(a.account.publicKey),isAccountCurrent:()=>true,signal:controller.signal});}
 let owner=await register();await host.provisionBootstrap(owner,{localBundle:ab,discoverySeed:a.sign.secretKey.slice(0,32),discoveryBox:a.discovery.secretKey.slice(),recipientKeys:[a.recipient.secretKey.slice()]});await host.connect({url:'ws://127.0.0.1:'+node.port+'/mesh/v4',nodeId:node.nodeId});
 const wire=await codec.request(ab,bb,'a'.repeat(64),b.account.secretKey,{acceptReceipt:people[0]===b?accept:null}),poll=async test=>{const end=Date.now()+20000;while(!await test()){if(Date.now()>end)throw Error('Bootstrap delivery timeout');await new Promise(r=>setTimeout(r,50));}};
 controller.abort();const revokedOwnerDenied=await rejects(()=>host.bootstrapList(owner));
 await sendNative(certificate,wire);await new Promise(r=>setTimeout(r,700));controller=new AbortController();owner=await register();await poll(async()=>(await host.bootstrapList(owner)).length===1);const pending=(await host.bootstrapList(owner))[0],notSelected=pending.state==='PENDING',noUserInbox=(await host.ownerInboxList(owner)).records.length===0;
 await host.selectBootstrap(owner,pending.exchangeId,pending.requestDigest);
 for(const receipt of [accept,confirm,confirm])await sendNative(certificate,DmashSecureSession.canonical({type:'NODE_BOOTSTRAP_RECEIPT_V4',exchange_id:pending.exchangeId,receipt}));
 await poll(async()=>Object.keys((await host.bootstrapList(owner))[0].receipts).length===2);const selected=(await host.bootstrapList(owner))[0].state==='SELECTED';
 for(let n=1;n<=7;n++){const request=await codec.request(ab,bb,n.toString(16).padStart(64,'0'),b.account.secretKey,{acceptReceipt:people[0]===b?accept:null});await sendNative(certificate,request);}
 await poll(async()=>(await host.bootstrapList(owner)).length===8);const overflow=await codec.request(ab,bb,'f'.repeat(64),b.account.secretKey,{acceptReceipt:people[0]===b?accept:null});await sendNative(certificate,overflow);
 await sendNative(certificate,'user payload forbidden');await new Promise(r=>setTimeout(r,700));const stillConnected=(await host.stats()).peers===1,onlyReceipts=(await host.ownerInboxList(owner)).records.length===0;
 DeviceRoot.lock();const end=Date.now()+5000;while((await navigator.locks.query()).held.some(v=>v.name==='dmash-node-runtime-v4')){if(Date.now()>end)throw Error('Root lock stuck');await new Promise(r=>setTimeout(r,25));}
 await DeviceRoot.unlock('BootstrapWorker-fixture-only');host=await DmashNodeRuntimeHostV4.startForDevice(DeviceRoot,{localOwnership:'managed',bootstrapProfile:'private-v1'});owner=await register();const restoredRows=await host.bootstrapList(owner),restored=restoredRows.find(v=>v.exchangeId==='a'.repeat(64)),quotaPersisted=restoredRows.length===8,persistent=restored.state==='SELECTED'&&Object.keys(restored.receipts).length===2&&host.identity.nodeId===identity,bootstrapRestored=(await host.stats()).owned===1;
 DeviceRoot.lock();return {revokedOwnerDenied,quotaPersisted,notSelected,noUserInbox,selected,stillConnected,onlyReceipts,persistent,bootstrapRestored};
},node);for(const [key,value]of Object.entries(result))assert.equal(value,true,key);console.log('PASS real Python Node→Worker bootstrap: signed REQUEST/ACCEPT/CONFIRM, explicit selection, receipt replay, no user Inbox, root restore and stable identity; ordinary UI/public-neutral bootstrap NOT tested');
}finally{helper.stdin.write(JSON.stringify({type:'STOP'})+'\n');helper.stdin.end();await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
