'use strict';
// Real EMS WSS/forced TURN runtime mechanism. Synthetic Accounts and injected
// metadata delivery callback; not ordinary UI or production capability acceptance.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require(process.env.DMASH_PLAYWRIGHT_MODULE||'/tmp/dmash-browser-tools/node_modules/playwright');
(async()=>{const root=path.resolve('D-MASH PWA/not_messenger'),names=['vendor/nacl-fast.min.js','storage.js','call_signaling.js','call_session.js','file_channel.js','file_session.js','recorded_note_turn.js'];const server=http.createServer((req,res)=>{if(req.url==='/'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(names.map(x=>'<script src="/js/'+x+'"></script>').join(''));}else if(names.includes(req.url.slice(4))){res.setHeader('Content-Type','application/javascript; charset=utf-8');res.end(fs.readFileSync(path.join(root,req.url.slice(1))));}else{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.DMASH_CHROME||'/home/jcode/.cache/ms-playwright/chromium-1248/chrome-linux64/chrome',args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});const contexts=[await browser.newContext({permissions:['microphone']}),await browser.newContext()],pages=await Promise.all(contexts.map(c=>c.newPage())),events=[];let mimeRetryRefused=false;
 try{for(let side=0;side<2;side++){await pages[side].exposeFunction('deliverMetadata',async wire=>{const message=JSON.parse(wire);assert(['voip_note_request','voip_note_complete'].includes(message.type));assert(!wire.includes('data:audio')&&!wire.includes('data:video')&&!wire.includes('dmash_media_fragment'));events.push({from:side,type:message.type,bytes:wire.length,at:Date.now()});
 if(process.env.DMASH_RETRY_MIME_ATTACK==='1'&&message.type==='voip_note_request'&&events.filter(e=>e.type==='voip_note_request').length>1&&!mimeRetryRefused){
  try{await pages[1-side].evaluate(({message,peer})=>runtime.receive({...message,manifest:{...message.manifest,mime:'audio/ogg'}},peer,()=>true),{message,peer:(side?'b':'a').repeat(64)});throw Error('MIME substitution accepted');}catch(error){assert(error.message.includes('Запись с таким номером уже существует'));mimeRetryRefused=true;}
 }
 return pages[1-side].evaluate(({message,peer})=>runtime.receive(message,peer,()=>true),{message,peer:(side?'b':'a').repeat(64)});});await pages[side].goto('http://127.0.0.1:'+server.address().port);await pages[side].evaluate(async side=>{window.peer=(side?'a':'b').repeat(64);window.DeviceRoot={state:{},onLock:()=>{}};window.observations=[];window.relay=[];window.Core={keys:{sign:nacl.sign.keyPair.fromSeed(new Uint8Array(32).fill(side+10))},blindSalt:new Uint8Array(32).fill(side+20),activeIdentity:'synthetic-'+side,activePeerId:peer,fastHash:async bytes=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join(''),withContactAccountV3:async(slot,fn)=>fn(),loadChat:async()=>{},renderPeers:async()=>{},refreshMessageTransportState:()=>{},refreshRecordedNoteState:(p,id,state,progress)=>observations.push({state,progress,at:performance.now()}),sendMessage:payload=>deliverMetadata(JSON.stringify(payload))};await DMashStorage.initGamma(new Uint8Array(32).fill(side+30));await DMashStorage.putBox('blind_peers',{alias:await DMashStorage.getAlias(peer,'L1'),data:{id:peer,name:'Synthetic peer'}});window.NodeManager={selectCallService:async()=> 'wss://stage-api-ems.d-mash.ru/signal/v1'};window.runtime=new DmashRecordedNoteTurn(Core,DMashStorage);window.timer=setInterval(()=>{void runtime.flush();for(const t of runtime.tasks.values())if(t.session?.pc){void t.session.pc.getStats().then(stats=>{for(const v of stats.values())if(v.type==='candidate-pair'&&v.state==='succeeded'&&v.nominated){const l=stats.get(v.localCandidateId),r=stats.get(v.remoteCandidateId);relay.push({local:l?.candidateType,remote:r?.candidateType});}}).catch(()=>{});}},200);},side);}
 if(process.env.DMASH_DROP_FINAL_ACK==='1')await pages[1].evaluate(()=>{const send=DmashFileChannel.FileChannel.prototype.send;window.droppedEndAck=0;DmashFileChannel.FileChannel.prototype.send=function(frame){if(!this.file&&new DataView(frame).getUint32(0)===this.count&&!droppedEndAck){droppedEndAck++;return;}return send.call(this,frame);};});
 const started=Date.now();await pages[0].evaluate(async()=>{const stream=await navigator.mediaDevices.getUserMedia({audio:true}),chunks=[],rec=new MediaRecorder(stream,{mimeType:'audio/webm;codecs=opus'}),stopped=new Promise(resolve=>rec.onstop=resolve);rec.ondataavailable=e=>chunks.push(e.data);rec.start();await new Promise(r=>setTimeout(r,2300));rec.stop();await stopped;stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:rec.mimeType});window.noteBytes=blob.size;const data=await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(blob);});window.sendStarted=performance.now();await runtime.queue(peer,{type:'voice',data});});
 const deadline=Date.now()+180000;while(!await pages[0].evaluate(async()=>{const rows=await runtime.rows(runtime.capture());return rows.length===1&&rows[0].status==='delivered';})){if(Date.now()>deadline)throw Error('TURN note delivery deadline');await new Promise(r=>setTimeout(r,250));}const sender=await pages[0].evaluate(async()=>({bytes:noteBytes,elapsedMs:performance.now()-sendStarted,states:observations,relay,rows:(await runtime.rows(runtime.capture())).map(r=>({sha256:r.sha256,status:r.status,contentRetired:r.content===null}))})),receiver=await pages[1].evaluate(async()=>{const msgs=await DMashStorage.getAllBoxes('blind_messages');return {count:msgs.filter(m=>m.inbound&&m.text.type==='voice').length,relay};});assert.equal(receiver.count,1);assert(sender.rows[0].contentRetired);assert([...sender.relay,...receiver.relay].some(x=>x.local==='relay'&&x.remote==='relay'));if(process.env.DMASH_DROP_FINAL_ACK==='1'){assert(events.filter(e=>e.type==='voip_note_request').length>=2);assert(events.some(e=>e.type==='voip_note_complete'));}
 if(process.env.DMASH_RETRY_MIME_ATTACK==='1')assert(mimeRetryRefused);
 const result={mimeRetryRefused,faultInjection:process.env.DMASH_DROP_FINAL_ACK==='1'?'one final encrypted ACK dropped after durable receiver commit':null,scope:'BROWSER actual EMS WSS+forcedTURN AES-GCM media; metadata IPC injected; no ordinary UI/deployedcapability claim',browser:browser.version(),sourceHashes:Object.fromEntries(names.map(name=>[name,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'js',name))).digest('hex')])),wallMs:Date.now()-started,sender,receiver,metadata:events};if(process.env.DMASH_QA_OUTPUT)fs.writeFileSync(process.env.DMASH_QA_OUTPUT,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
 }catch(e){for(let i=0;i<pages.length;i++){console.error('state',i,await pages[i].evaluate(async()=>({observations:window.observations,tasks:window.runtime&&[...runtime.tasks.values()].map(t=>({outbound:t.outbound,closed:t.closed,pc:t.session?.pc?.connectionState})),rows:window.runtime&&await runtime.rows(runtime.capture()).then(rows=>rows.map(r=>({status:r.status,attempts:r.attempts,nextAttempt:r.nextAttempt})))})).catch(()=>null));}throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
